### ISSUE TITLE
Display Mean and Calculation with Results

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#102]
**As a** *consultant and BCWS employee* **I want** *to see the results of the 90% calculations* **So That** *I can validate values based on my needs and document it in my report *

**Acceptance Criteria**
- [x] display mean values of all selected stations
- [x] display data used to calculate percentile 
- [x] Given a calculation is made when i view the results then I can see the years of data used and the core fire season used to calculate the results
- [x] Given a calculation is made when i view the results then I can see the mean values of BUI, FFMC, ISI

**Comment by jakemorr** [comment]
Dev technical discussion required prior to estimation, need to discuss cancel calls scenarios
