### ISSUE TITLE
First iteration of Fire behaviour advisory

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#1091]
**As a** *FBAN/Forecaster * **I want** *to calculate HFI, ROS, Fire Type and Fire Size* **So That** *so that I can generate a fire behaviour advisory for different fuel types*

**Additional Context**
- Very technical - glue things together - make it all work.

**Acceptance Criteria**
- [ ] Verify sample of calculated results using the redbook.
- [x] Make all fuel types return a not broken response. (200OK with data that displays)
- [ ] Validate against coastal centre HFI spreadsheet.
- [x] Lint passes.
- [x] HFI Calc still works.
- [x] Tests run in pipeline on github.

**Comment by andrea-williams** [comment]
my investigation of the second half of the fuel type list (accuracy of FIREBAT! against Red App) has been posted into our Teams General channel (and consequently in the Files section)
