### ISSUE TITLE
Windspeed and FFMC Tolerence using diurnal adjustment table

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#1093]
**As a** *(User Type/Persona)* **I want** *to know how much. theFFMC or Windspeed would need to change to increase the HFI to specific thresholds* **So That** *So they know what conditions would change the danger class during the day*

**Additional Context**
Tolerences:
- when the HFI is going to cross the 4000 kw/h
- when the HFI is going to cross the 10000 kw/h

**Acceptance Criteria**
- [ ] ~~Given I've selected 1+ stations in FireBat, When I click the "Calculate" button, Then I can see the critical FFMC value at which HFI is >= 4000~~
- [ ] ~~Given I've selected 1+ stations in FireBat, When I click the "Calculate" button, Then I can see the critical FFMC value at which HFI is >= 10,000~~
- [ ] Given I've selected 1+ stations in FireBat, When I click the "Calculate" button, Then I can see the "critical hours" for which diurnally adjusted FFMC is >= the critical FFMC value for HFI >= 4000
- [ ] Given I've selected 1+ stations in FireBat, When I click the "Calculate" button, Then I can see the "critical hours" for which diurnally adjusted FFMC is >= the critical FFMC value for HFI >= 10,000
- [ ] ~~Given I've selected 1+ stations in FireBat, When it's not mathematically possible for HFI to go up to 4,000 (holding all other values constant), Then I can see the corresponding HFI value when FFMC is at its max (101)~~
- [ ] ~~Given I've selected 1+ stations in FireBat, When it's not mathematically possible for HFI to go up to 10,000 (holding all other values constant), Then I can see the corresponding HFI value when FFMC is at its max (101)~~
- [ ] ~~Given I've selected 1+ stations in FireBat, When it's not mathematically possible for HFI to go down to 4,000 (holding all other values constant), Then I can see the corresponding HFI value when FFMC is at its minimum (0)~~
- [ ] ~~Given I've selected 1+ stations in FireBat, When it's not mathematically possible for HFI to go down to 10,000 (holding all other values constant), Then I can see the corresponding HFI value when FFMC is at its minimum (0)~~
- [x] Given I've selected 1+ stations in FireBat, When I manually adjust the value of the station's wind speed and click the "Calculate" button, then I can see the ISI value for the change in wind speed, and I can see the resultant HFI value for the corresponding change in ISI

Deleted some of the AC because I think they're no longer needed

**Comment by andrea-williams** [comment]
Progress update: the functionality in the API to calculate critical FFMC values for HFI of 4000 and 10,000 (the first 2 items in AC) has been completed, but this data isn't displayed in the frontend yet.

**Comment by tessmgood** [comment]
SE-FC user Q (for discussion?): 
"I would be curious to know how it handles the noon adjustment of values. For example, if rainfall doesn’t show up in the calculation until 12:00 the HFI could be above 4000 at 10:00 in the morning drop below at 12:00 for an hour or two then be back above 4000 again.
Since WeatherPro shows this noon discontinuity visually it is easy to figure out what is going on. If the web app simply spits out a time of 11:00 for crossing the 4000 threshold, how would one know if there is a discontinuity at noon or not?"

**Comment by andrea-williams** [comment]
^ In regards to that question, we can return a list of critical time ranges, e.g. output "Critical Hours: [11:00, 13:00-18:00]" to indicate that noon presents a discontinuity.

That's great context for me to know as I implement this - I doubt I would have otherwise thought of this scenario.
