### ISSUE TITLE
order table by selected column

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#1095]
**As a** *Forecaster/FBAN* **I want** *to sort the rows of the table any selected column* **So That** *I can interpret the data in a way that makes sense to me*

**Additional Context**
use cases:
- to sort by zone because thats how i populate the FBA
- to sort by fuel type to do analysis
- to sort by ISI to analysis (looking for fire behaviour cues to prioritize where they should start when everything is bad)
- to sort by HFI for analysis and prioritization
- wind speed to organize the scenarios I am running in FIREBAT

**Acceptance Criteria**
- [ ] all columns sortable
- [ ] I can sort the table by column with numbers from highest value to lowest value and lowest value to highest value
- [ ] I can sort the table by column starting with letters from A to Z and Z to A

**Comment by conbrad** [comment]
Deploying: https://github.com/bcgov/wps/pull/1215 once built and tested in dev.

Will create a follow up PR implementing the rest of the columns as sort options soon after.
