### ISSUE TITLE
Pipeline + Unit Tests

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/wps#110]
**Describe the task**
Add available unit tests to the pipeline.

**Acceptance Criteria**
- [x] Find tests
- [x] Add them
- [x] Failing the test = Pipeline does not pass the code
- [x] Pipeline runs the tests
- [x] Dockerfile for deploying wps-web

**Comment by Nkuruba** [comment]
@jakemorr 
For running unit tests of wps-web during the build process, a docker file is required and a new task is required to produce this docker file. Should we go ahead and create a separate task for it and append it as a blocker to this task?

CC: @DerekRoberts
