### ISSUE TITLE
Reference R code source and constant inputs

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1106]
**As a** *(User Type/Persona)* **I want** *understand how values are being calculated* **So That** *I trust the output*

**Additional Context**
- We should be very clear on how the values are calculated.
- We should reference the underlying library we're using:
- https://r-forge.r-project.org/projects/cffdrs/
- Also we should reference the constants for crown fuel load as per "Development and Structure of the Canadian Forest Fire Behaviour Prediction System" from Forestry Canada Fire Danger Group, Information Report ST-X-3, 1992
- TG ACTION: write CTA 
- SS ACTION: license compliance - ensure compliance with R Code Library (GPL v?) 

**Acceptance Criteria**
- [ ] Given I reading the FireBAT disclaimer, when I have questions or curiosities, Then a call to action encourages me to contact the PSU team (PSU email)

**Comment by conbrad** [comment]
I've been thinking if this should be surfaced on the UI as well for transparency.

Some sort of dialog/banner/message that describes all assumptions/constants, where they originate from, etc. IMO if I were a user I'd want to know these things right off the bat.

**Comment by conbrad** [comment]
As a data point, feedback from describing us using the published `ccfdrs` R package was very position
