### ISSUE TITLE
Improve usability

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1117]
Double clicking is weird. Single clicking is problematic when you double click. Either way - we want a clue that it's a dropdown!

**As a** *FBAN/Forecaster* **I want** *an easy to understand interface* **So That** *I can quickly and confidently calculate information to generate FBAs*

**Additional Context**
- 15-20 folks typically generate FBAs
- people do this task as early as 6am
- lots of new folks are coming in to support this work, I did a usability session with someone Friday who's arrived from the Maritimes 3 days ago to help, and is using this calculator heavily (KFC)
- a clear interface that follows common conventions ensures folks parachuting in to help can use this calc. with clarity and confidence

const handleClick = (params: GridCellParams, event: any) => {
    if ('value' in event.target) {
      // clicked on value in cell?
    } else {
      // click on cell
      params.api.setCellMode(params.id, params.field, 'edit')
    }
  }
..
..
..
onCellClick={handleClick}

**Acceptance Criteria**
Minimum release:
- [ ] Don't populate "default" / "1st" station in dropdown (questions around error handling)
- [x] Dropdown prompt
- [x] Single click (easy)

**Comment by tessmgood** [comment]
Interface conventions to indicate it is a dropdown:
- visible controls (drop down arrow) 
- empty state ("select weather station") rather than populating it with the first in the list

**Comment by tessmgood** [comment]
Resources: 
- https://material.io/components/data-tables#behavior (see inline menus)
- https://www.smashingmagazine.com/2019/02/complex-web-tables/
![complex-web-table-article-table-06.webp](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/cbff3212-2a5e-46e0-8f5f-23970ae83c67)

**Comment by conbrad** [comment]
Dropdown prompts working, default selection placeholders will require some rejigging.
