### ISSUE TITLE
Additional UI improvements

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1121]
Make UI better

**As a** *FBAN/Forecaster* **I want** *an easy to understand interface* **So That** *I can quickly and confidently calculate information to generate FBAs*

**Additional Context**
- 15-20 folks typically generate FBAs
- people do this task as early as 6am
- lots of new folks are coming in to support this work, I did a usability session with someone Friday who's arrived from the Maritimes 3 days ago to help, and is using this calculator heavily (KFC)
- a clear interface that follows common conventions ensures folks parachuting in to help can use this calc. with clarity and confidence

**Tech Context**
- For select field prompt alignment, try to make the select fields in data grid a proper select component: https://material-ui.com/components/selects/ (I found this broke the formatting of the grid table)
- For default/placeholder values, the default non-station needs to be added to the valueoptions list for station and fuel type lists. It code formatting logic will need to be able to handle it and it would be nice to use the built-in placeholder prop field in material ui to make it look nice OOTB
- Searchable dropdown - try to make use of the autocomplete field from morecast station list

**Acceptance Criteria**
Minimum release:
- [ ] Don't populate "default" / "1st" station in dropdown (use placeholder prompt) (questions around error handling)
- [x] Align prompt icons to right of cell
- [x] Searchable dropdown (risky - lot's of unknowns)
- [x] Dropdown station list list consistent with rest of site (name + code combo)
- [x] Click selection of select item should collapse the option list
- [ ] Inline editing of grass cure percentage number shouldn't expand the cell / cause misclicks

**Comment by conbrad** [comment]
Moved empty state fix and number box to #1130
