### ISSUE TITLE
Add Zone code to FIREBAT table

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1129]
**As a** *FBAN/Forecaster* **I want** *to see the zone code of each weather station* **So That** *I can easily populate my FBA document, as it is often done by Zone*

**Additional Context**
- we get firezone code from WF1 API
- Kamloops starting with K (K2, 4, 5, 6, 7)
- Prince George starting with G (G1, G3, G4/5, G6, G7, G8, G9)
- Northwest starting with R (R1/2, R3/4, R5/8, R9)
- Cariboo starting with C (C1-4)
- Southeast starting with N (numbers from WFWX) 
- Coastal starting with V (numbers from WFWX)

**Acceptance Criteria**
- [ ] when I look at the firebat table i know what firezone a weather station belongs to
- [ ] when i look at the table i see the zone code  (we do not want full firezone name)
- [ ] if there is no zone code the cell is empty

**Comment by andrea-williams** [comment]
back-end generates zone code; not being displayed on front end until the inline table branch is merged into main.
