### ISSUE TITLE
Add default empty state, single click number edits, keybaord usability  FIREBAT 

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#1130]
**Describe the task**
Adding a new row in the data input table should have an empty default state with placeholder label prompt, e.g. "Select a station"

**Acceptance Criteria**
- [x] Don't populate "default" / "1st" station in dropdown (use placeholder prompt) (questions around error handling)
- [x] Have clear button set cell back to empty state
- [x] Keyboard navigation is supported and works well, see notes on backspace behaviour in comments
- [x] Single click number field edits

**Additional context**
- Currently the first items in the menu options are set by default in a new row.
- handling undefined as the empty state and sorting out what a controlled and uncontrolled component is

**Comment by tessmgood** [comment]
Minor QA notes on mouse/keyboard navigation: 
- overall it's working really well but there's weird behaviour if I mix keyboard nav and clicks. To reproduce:
-- click the station cell twice (deselects the text) I can only backspace once, then it stops working (deletes one character)
-- example flow: add row, click station dropdown arrow, select a station, my cursor is active in the cell (pulsing), but backspace only deletes one character, then nothing happens

**Comment by conbrad** [comment]
Moved some of the new table work back to this ticket from #1141 that I had started on Friday. #1141 captures the desired end state, this ticket will capture a subset of that.
