### ISSUE TITLE
grass cure and wind speed shouldnt expand cell

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#1135]
**Describe the task**
currently entering a number in either wind speed or grass cure cause the cell to expand, causing misalignment of cells and misclicks and it requires a double click to edit

**Acceptance Criteria**
- [ ] Inline editing of Grass Cure percentage number shouldn't expand the cell/cause misclicks
- [ ] Inline editing of Wind Speed number shouldn't expand the cell / cause misclicks
- [ ] single click allows editing rather than double click
- [ ] keyboard navigation works for grass cure and wind speed

**Additional context**
- Currently when tabbing from fuel type to grass cure it only allows you to press 1 number so you cannot enter double digits

**Comment by conbrad** [comment]
This is fixed by the PR for #1141
