### ISSUE TITLE
Investigate Fuel Type C1

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#1136]
**Describe the task**
investigate why our output for fuel type C1 is different from either Redapp or the coastal spreadsheet

**Acceptance Criteria**
- [x] Either we correct the problem and we match spreadsheet and redapp or we have the rationale for why our output is accurate as it is
OR
- [x] Confident that we aren't doing anything wrong and this is escalated to SME

**Additional context**

**Comment by Sybrand** [comment]
REDapp seems to use a value of 144 for the date of minimum foliar moisture content. (I can't find this in code, but through trial and error I get the same values for fmc using this value);

`FMC_Calc = jnius.autoclass('ca.cwfgm.fuel.FMC_Calc')
for i in range(0, 365):
    fmc_calc = FMC_Calc()
    fmc_calc.setAttributeValue(16801, i)
    result = fmc_calc.fmc(lat, long, elv, day_of_year)
    print(f'REDapp: {i} fmc:{result}')`

We should find the source for this value.
