### ISSUE TITLE
Research Wildfire preparedness

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#114]
**research the preparedness planning functions**

**Acceptance Criteria**
- [x] Map decisions made by wildfire preparedness staff
- [x] Identify which personas are users for preparedness planning
- [x] identify key contacts for user research on preparedness planning
- [x] update Wiki with findings

**Comment by PrakritiM** [comment]
Updated Glossary:
https://github.com/bcgov/wps/wiki/Glossary

**Comment by PrakritiM** [comment]
BCWS Positions for Preparedness (in yellow)
https://miro.com/app/board/o9J_kwsj7gk=/

**Comment by PrakritiM** [comment]
Summary of discussion

https://miro.com/app/board/o9J_kvf9lAQ=/
