### ISSUE TITLE
Front-end table: inline, add zone, color code hfi

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1141]
**As a** *FBAN/Forecaster* **I want** *an easy to use table* **So That** *I can quickly scan information and complete my tasks (review/comprehension, analysis, copy/paste) with confidence and efficiency*

**Additional Context**
- https://miro.com/app/board/o9J_lWy3dqw=/?moveToWidget=3074457361437102505&cot=14
- this is ideation and guidance only - a starting point as we explore our table solution 
- hierarchy of buttons (placement, size)
- copy writing for empty states 
- column dividers, grouping sets of data together visually
- alignment of header text (bottom)
- frozen columns on scroll, so that location and fuel context is visible beside FireBAT calcs. (HFI +) 
- editable cell styling 
- placement of table on page (whitespace) 
- alignment of BC Gov header (container widths) 

**Acceptance Criteria (ordered by priority)**
- [x] Inline results in input table
- [x] auto-calculate on exit focus and on enter
- [ ] Adding zone column -- just the code (e.g. K2) #1129
- [ ] Color code HFI ( >= 3000 HFI <= 3999 is outlined orange, HFI >= 4000 orange fill, HFI >= 10000 red fill) [Figma for hex codes](https://www.figma.com/file/AUhBnTB50dnY7ysoxBSqPN/New-Fire-Behaviour-Tool-2021?node-id=375%3A2015)
 

**Additional context**
- Currently the first items in the menu options are set by default in a new row.
- handling undefined as the empty state and sorting out what a controlled and uncontrolled component is

**Comment by conbrad** [comment]
Investigating this as an alternative: https://react-table.tanstack.com

**Comment by conbrad** [comment]
And this: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/

**Comment by conbrad** [comment]
Working on a prototype table implementation of react-table linked above since it's completely open source, updated frequently, and supports MaterialUI.

**Comment by conbrad** [comment]
Ran into issues with how `react-table` orders the row data when building the table cells. Going to remove that dependency since it's not adding much / saving us a lot of work at the moment.

**Comment by tessmgood** [comment]
@conbrad 
**keyboard nav** 
- When I type a station, hit the down arrow, hit enter, then hit tab it logs my station and moves me to fuel. When I select a non-grass fuel I do the same, type fuel name, down arrow and enter to select, hit enter again or tab and it calculates
- For grass cure required... same as above but I select O1a as my fuel, grass input is outlined in red as soon as I select the fuel, if i try to tab to grass cure input, it calculates instead (with a status of "error"), then on page re-load when I hit tab (wanting to go to grass cure) I'm focused on the top left checkbox (check all)

**adjusted wind speed cues**
-we lose the bold styling on the wind speed value when it's adjusted, now that the tables are merged and wind speed is always/only an input.
- In the old table "adjusted" status and wind speed value were both bold to tie them together.
- can we colour the border of the wind speed input when its adjusted? one tester didn't notice the bolding, too subtle, so I wanted to add colour regardless
- new proposed solution: when a user adjusts wind speed, change the status to "**adjusted**" bold and change font color, apply same color to adjusted wind speed **input** field. If possible, I will provide a colour

**bookmark links**
If I load a bookmark, it calculates automatically as there is no cue about what to do with an semi-populated table without the calculate button
