### ISSUE TITLE
Research/decide on daily vs. noon vs. peak data for percentile calculations

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#115]
Note from Jesse E. from Anaconda Sprint Review Miro board:

For Brady and the team to consider:  Daily values use noon weather to calculate a forecast FFMC & ISI using a diurnal model that I believe is the same for all stations (although I'm not sure about that).  In reality, the diurnal effect at each station is a little different (sometimes a lot different), so I suggest thinking about running these calculations on the peak hourly FFMC and ISI values from each day rather than the daily values.  Note: I wouldn't suggest running percentile reports on all hourly data since this would be skewed by all the low values each night.  BUI has only one value per day and is not affected by the diurnal curve.  I hope this feedback is in an acceptable format - I think I recall someone saying you don't want to be told what to do but I don't know how to word this without telling you what I think should be done.  Cheers

**Additional Context:**
- is this something that needs more research/feedback from SMEs?
- look at posting app on Slack with question around how do we calculate 90% weather values? Talk to Dana.

**Comment by jowand** [comment]
I agree with Jesse's comments above. We are interested in maximum values, not noon values. Some values will only have one input per day but for the remainder, we should be using daily max.

@andrea-williams, what values are we currently using?

**Comment by Sybrand** [comment]
@jowand we are using the values from the daily weather table - my assumption is that those are noon values but to confirm it you'd have to ask someone else who knows more about the weather database.

**Comment by jowand** [comment]
@Sybrand we will stick with daily values but we need to add wording around this in the disclaimer and above the tables so that users are aware that it's the 90th percentile daily values (which are noon values polled from weather stations).
