### ISSUE TITLE
Adjust Critical Time diurnal calculations

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1158]
Assumption that fire weather indices were for 13:00 was incorrect, they are for peak burning time of 17:00. 
This means our diurnal calculations for Critical Time were off, and in some cases providing critical hours, suggesting a FBA is issued, for days that the HFI would not cross the 4,000 threshold at peak burning time.

1. Modify calculation 
2. Modify copy in disclaimer box, using language similar to Fire Behaviour Forecast templates (1300 hrs Wx and FWI Indices for 1700 hrs) to replace the Solar Noon Outputs copy. 

- Drop all asterisks from FFMC, ISI, FWI, Critical Hours
- Remove colour on Critical Hours columns
- Copy:
< h4 >Forecasted weather outputs are for 13:00 and FWI Indices for 17:00 PDT.< /h4 >
< p >These fire behaviour calculations assume flat terrain.< /p >

![Screen Shot 2021-07-26 at 8.57.08 AM.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/ec053642-e633-4765-9278-98f8c2a4f940)

Additional Context
- BB was collaborating with DP of Pacific Forestry Centre and identified the faulty assumption when using the tool
- Follow up may be required: the WFWX team are under the impression the values are for 13:00. DH confirmed it's 17:00.

**Comment by Sybrand** [comment]
I think this is done? @andrea-williams to confirm everything is copacetic.
