### ISSUE TITLE
MeteoStar Software Discovery

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#116]
Explore the possibilities to import and use products and data that is available through Meteostar software.

**Acceptance Criteria**
- [ ] Developer set up with access
- [x] Understanding of current system and setup (Call with Robert Rowson)

**Additional context**
- Identify a developer to take this on. Will need to get them set up with access through CITRIX
- Current platform is shared with BC Hydro and is deployed on Hydro servers. For security reasons we need to be behind hydro's firewall and this creates some limitations for what we can do.
- Some work on integration has been done by IITD to be able to import some of the products in image format. Matthew Barnes (IITD) and Robert Rowson (contract weather forecaster) are main contacts
- We have talked about the option of breaking away from partnership with Hydro so that we can expand functionality. Need to explore the full potential to see if the value is there?
- Brady can provide dev access

**Comment by Sybrand** [comment]
Waiting on a meeting with Robert and access.

**Comment by bradyholliday** [comment]
Request for access and initial meeting with Robert was sent March 16

**Comment by bradyholliday** [comment]
BC Hydro is working on setting up aceceess and has emailed @Sybrand and @Nkuruba the authorization forms for access to their facilities. I sent an invite to arrange a call with Robert for Monday. Feel free to change it as needed.

**Comment by Sybrand** [comment]
I've completed the relevant documentation and sent to Alexander at BC Hydro

**Comment by Nkuruba** [comment]
Signed and sent the policy documents from BC Hydro for access to Meteostar.

**Comment by Sybrand** [comment]
Have sent token

**Comment by Sybrand** [comment]
I have access to BC Hydro now! I'm in! Next step is figuring out how to get to Meteostar.

**Comment by jakemorr** [comment]
meeting setup for thursday April 30th

**Comment by Sybrand** [comment]
Have requested access Leads Client using the request catalog
