### ISSUE TITLE
Deploy Front End in Dev mode

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#119]
**Describe the task**
Deploying WPS-Web in dev mode (no sourced image, no Caddy) So we can continue to work with the container (testing variable changes, etc)

**Acceptance Criteria**
- [x] Build Docker file for Front End
- [x] WPS Web runs in Dev Mode
- [x] Deploys to a Pod
- [x] Consumable by Pipeline
- [x] Able to run Unit Tests

**Comment by DerekRoberts** [comment]
Reopening for bug fixes.
