### ISSUE TITLE
Use and Displaying the representative fire season alongside the selected weather station

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#121]
**As a** *Consultant/wildfires staff* **I want** *Representative core fire season dates associated with individual weather stations* **So That** *values are correctly associated with a geographical locations fire season*

**Additional Context**
- Look into linkage with preset weather zones and Danger regions
- will require SME time for further defining
- loose definition of what this looks like on Miro (see comments)
- need to establish who is going to own and maintain that relationship if it is not something that is currently in the database 

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by jakemorr** [comment]
Pull Dana and Jesse into zenhub so they can start providing information on tickets in the backlog

**Comment by jowand** [comment]
This looks like  90th percentile calc task, not a FWI calc task?

**Comment by jakemorr** [comment]
@jowand this is 90th Percentile, because currently the calulator uses the same date range for every weather station every year, this was to display that the information was to display  the fire season date range for the 90th percentile with the thought that eventually we would have different fire season date ranges for different locations.

**Comment by jowand** [comment]
@jakemorr cool I was just looking at the Epics and it's in FWI calc. Will change.
