### ISSUE TITLE
HFI Calculator: Graph View feasibility

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1213]
**Describe the task**
Rough wireframes were prepared for a Graph view of the HFI Calculator. They may not be feasible as represented - Dev / UX collaboration required. 

**Acceptance Criteria**
- [ ] UX and Dev to chat about the graphing engine and general feasibility
- [ ] UX to update wireframes accordingly

**Additional context**
- SME conversations may also be required / subsequent tickets
- [Figma file](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2021?node-id=207%3A2)

**Comment by jakemorr** [comment]
Graph was scrapped from MVP it was a filler because people said they wanted a graph after seeing MoreCast but had no idea what they wanted to display or what value it adds

**Comment by tessmgood** [comment]
@jakemorr that's fine, something I learned: senior folks such as DB want it for education purposes — he's concerned that FBANs, particularly new ones, aren't critically thinking about the data, and are missing interpretation opportunities. Big knowledge management and succession planning theme as we see a wave of retirements of veterans in BCWS. 

The graph is meant to address that (there could be other ways! seems worthy of UX exploration and ideation in the future)
