### ISSUE TITLE
HFI Calculator: Sticky Header behaviour

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1218]
**Describe the Bug**
The table container (height) extends beyond the viewport (table too tall). The header IS sticky to a point, but you can't view all rows by scrolling vertically (up/down) AND keep the header in view. 

**Expected Behaviour**
The table container sits within the viewport. I can scroll up and down within the table container, as I scroll the header remains sticky. 

**Actual Behaviour**
The table container is taller than the viewport. I can't scroll all rows in the table while keeping the header in view. To see the bottom-most rows I have to scroll within the browser, not the table (losing the header in the process). 

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to HFI Calculator and log in
2. Scroll mid-way down the table and note the sticky header behaviour
3. Scroll down to the last row of the table
4. See error: lost sticky header, had to scroll in browser 

You may also find yourself accidentally scrolling in the browser instead of the table to begin with, and struggle to activate the sticky header feature - pending type of mouse and user behaviour. 

**Screenshots**
 https://images.zenhubusercontent.com/235861506/ea1f501f-36b3-4846-bac6-4fb153dcca62/screen_recording_2021_08_10_at_1_48_07_pm.mov

**Desktop (please complete the following information):**

**Additional context**

**Comment by conbrad** [comment]
@tessmgood is this fixed with the recent header change?

**Comment by tessmgood** [comment]
@conbrad yeah I think we're in good shape now, we can close this one
