### ISSUE TITLE
HFI Calculator: Freeze first column on horizontal scroll

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1220]
**As a** *FBAN* **I want** *to keep my place in the table as I scroll (know which stations I'm looking at)* **So That** *I can easily and accurately interpret the table*

**Additional Context**
- Location column sticky on horizontal scroll _when_ scrolling is required in table (responsive/browser width)
- this will become more relevant as the final columns are added to daily view
- this will become MOST relevant for the weekly view as it will likely be much wider

**Acceptance Criteria**
- [ ] Given I am using the HFI Calculator weekly view, When I scroll to the right, Then the  Checkbox, Location, Fuel Type, Grass Cure columns freeze and remain visible 
- [ ] Given I am using the HFI Calculator weekly view, When I scroll to the right, Then the Fire Centre (e.g. Kamloops) and Planning Area (e.g. Lillooet K7) freeze and remain visible 
- [ ] Given I am using the HFI Calculator daily view, When I scroll to the right, Then the  Checkbox, Location, Fuel Type, columns freeze and remain visible 
- [ ] Given I am using the HFI Calculator daily view, When I scroll to the right, Then the Fire Centre (e.g. Kamloops) and Planning Area (e.g. Lillooet K7) freeze and remain visible 
- [ ] consider copy/pasting workflow: whatever that solution is #1290, it must keep working

**Comment by Sybrand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1220?planning-poker) with ZenHub @andrea-williams @conbrad
