### ISSUE TITLE
FireBAT: empty table state (instructions)

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1246]
**As a** *New FireBAT user* **I want** *to be set up for success with interface feedback* **So That** *I understand what steps to take and what is possible*

**Additional Context**
- lower priority, nice to have
- when table is empty, show instructions [Figma](https://www.figma.com/file/AUhBnTB50dnY7ysoxBSqPN/New-Fire-Behaviour-Tool-2021?node-id=207%3A2)

**Acceptance Criteria**
- [x] Given I visit FireBAT, When no bookmark has been loaded or stations added, Then I see a piece of instructional/welcome copy in the empty table container

**Definition of Done**
- [x] Ready to Demo in Sprint Review
- [x] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [x] Peer Reviewed by 2 people on the team
- [x] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by Sybrand** [comment]
@JulianForeman while you're at it - can you drop the word Prototype from the top?
