### ISSUE TITLE
Round up Mean Intensity Group values

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#1269]
**Describe the Bug**
Mean Intensity Group value rounds to the nearest integer, when actually it should always round up (e.g., 2.1 should round to 3. Right now it gets rounded to 2.)

**Expected Behaviour**
Mean Intensity Group values should always round up to the next integer.

**Actual Behaviour**
Mean Intensity Group values get rounded to the nearest integer.

** Steps To Reproduce**
It's self-explanatory.

**Additional context**
Have confirmed with PO that rounding up is the desired behaviour for Mean Intensity Group.

**Comment by conbrad** [comment]
Only applies to MIG, not prep levels. Need to change prep level calculation to not use ceiling function.

**Comment by conbrad** [comment]
Confirming desired requirements for rounding.

**Comment by conbrad** [comment]
Based on the spreadsheet we're emulating [here](https://miro.com/app/board/o9J_lQR8YI8=/), prod already expresses the desired behaviour (MIG shows decimal number based on average, prep levels don't).
