### ISSUE TITLE
HFI Calc: Date picker 

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1284]
**As a** *HFI user* **I want** *clear, consistent, easy to use patterns for selecting my desired date* **So That** *I can easily select which day in a prep cycle I am looking at*

**Additional Context**
- Instead of previous/next navigation, implement our standard date picker so that users can easily jump to the date they're looking for, and have more context, e.g. day of the week (Monday and Thursday being highly relevant days) 
- [Figma ](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2021?node-id=207%3A2)
- DatePicker can be reused: https://github.com/bcgov/wps/blob/main/web/src/features/fbaCalculator/components/DatePicker.tsx
- Do not save Date parameter in URL

**Acceptance Criteria**
- [x] Given I am using the HFI calculator, When the page loads, Then data for today's date is displayed
- [x] Given I want to change the date, When I click the calendar icon in the date selector, Then a calendar appears 
- [x] Given I select a date on the calendar that differs from the current selection, When I select a day, Then the HFI calculator re-loads
- [x] When the HFI calculator refreshes on date change, Then I see a loading indicator
- [x] The Firebat date picker is reused

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by JulianForeman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1284?planning-poker) with ZenHub @conbrad @andrea-williams @Sybrand

**Comment by Sybrand** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1284?planning-poker) with ZenHub @JulianForeman
