### ISSUE TITLE
Create Jenkins ON_GH_EVENT for PR-Cleanup

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/wps#138]
**Describe the task**
When Pull Requests are closed without merge they leave a trail of OpenShift build artifacts.  This can be fixed by using a Jenkins GitHub event (ON_GH_EVENT) to clean up.

**Acceptance Criteria**
- [x] Learn about Jenkins structure and where to edit
- [x] Write a call in Groovy
- [x] Commit to our wps repo for future instances
- [x] Apply to our Jenkins for current instance
- [ ] tested across all repos

**Comment by Nkuruba** [comment]
Changes added to wps repo and the updated script is able to delete resources post PR closure.

**Comment by Nkuruba** [comment]
Tested with https://github.com/bcgov/wps-web/pull/48 and clean up works fine. Waiting for pipeline setup for api to test it out.

**Comment by DerekRoberts** [comment]
This will likely only stay declined if we leave Jenkins.  It's going back into the backlog for reassessment.
