### ISSUE TITLE
HFI Calc: Errors in daily and weekly view

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1405]
**As a** *R/ZWCO* **I want** *clear, actionable interface feedback* **So That** *if there is a data problem (e.g. missing variable) I can work around it or follow up with someone to resolve it*

**Additional Context**
- modelling in [Figma ](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2021?node-id=863%3A559)
- as a general rule we want to show an error in two places: the origin (for action/follow-up, e.g. the missing weather index) and final consequence in the flow (e.g. Prep can't be calculated because of the missing index) but not every fail point in the middle... that's not helpful.
- don't forget that as soon as one index is missing: HFI, ROS, FIG and Prep cannot be calculated regardless of which one or how many are missing for that station 
- this also addresses interface issues surfacing in user testing. previous ux-dev collaboration came to the agreement that we would address continuous row and column borders in this ticket
- requesting that a dev works with a forecaster to test / generate scenarios 

**Acceptance Criteria**

Scenario 1: no forecast
- [x] Given I am using the HFI Calculator **daily** view, When there is no (zero) forecast data, Then an error icon is displayed in status column
  - hover copy on the error icon reads: _Forecast not available. Please check WFWX or contact a Forecaster._
- [x] Given I am using the HFI Calculator **daily** view, When there is no (zero) forecast data, Then an error icon is displayed in M/FIG column (planning area row)
  - hover copy on the error icon reads: _Forecast not available for one or more stations. Please exclude station(s) displaying errors._   
- [x] Given I am using the HFI Calculator **daily** view, When there is no (zero) forecast data, Then an error icon is displayed in Prep column
  - hover copy on the error icon reads: _Forecast not available for one or more stations. Please exclude station(s) displaying errors._   
- [x] Given I am using the HFI Calculator **weekly** view, When there is no (zero) forecast data, Then the cells are empty (no data) but row and column borders are still displayed — see Figma
- [x] Given I am using the HFI Calculator **weekly** view, When there is no (zero) forecast data, Then an error icon is displayed in the Prep column for affected day(s)
  - hover copy on the error icon reads: _Cannot calculate prep level. Please exclude station(s) displaying errors._
- [x] Given I am using the HFI Calculator **weekly** view, When there is no (zero) forecast data, Then an error icon is displayed in the Final Calculated Prep column 
  - hover copy on the error icon reads: _Cannot calculate prep level. Please exclude station(s) displaying errors._
- [x] Given I am using the HFI Calculator **weekly** view, When there is no (zero) forecast data for 1+ days, Then  display the highest daily FIG, understanding that it is excluding the days with errors/no data

Scenario 2: technical issue — consistency with FireBAT
![Screen Shot 2021-09-15 at 2.45.42 PM.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/cff5aa51-6d61-4a8e-8e3e-6715a9f4d1a7)
- [x] Given I am using the HFI Calculator daily or weekly view, When there is a technical issue, Then a banner displays at the top of the page 
  - banner copy reads: The following errors have occurred. Please refresh the page. If the problem persists, please <contact us>. Bullet: list error/code (e.g. 500) 

Scenario 3: incomplete forecast (e.g. grass cure missing, temp missing)
- [x] Given I am using the HFI Calculator **daily** view, When there is partial forecast data - meaning one or more but not all indices are missing, Then we display the data we can, and display an error icon in column(s) with missing data
  - Hover copy on the error icon reads: _[index], [index] cannot be null. Cannot calculate [impacted fire behaviour indices]_
- [x] Given I am using the HFI Calculator **daily** view, When there is partial forecast data - meaning one or more but not all indices are missing, Then an error icon is displayed in the Mean FIG column 
  - Hover copy on the error icon reads: _Incomplete data from WFWX for one or more stations. Please exclude station(s) displaying errors._    
- [x] Given I am using the HFI Calculator **daily** view, When there is partial forecast data - meaning one or more but not all indices are missing, Then an error icon is displayed in the Prep column 
  - Hover copy on the error icon reads: _Incomplete data from WFWX for one or more stations. Please exclude station(s) displaying errors._   
- [x] Given I am using the HFI Calculator **weekly** view, When there is partial forecast data - meaning one or more but not all indices are missing, Then an error icon is displayed in the daily and final Prep column(s) 
  - Hover copy on the error icon reads: _Cannot calculate prep level. Please check the daily forecast using the tabs above._

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by andrea-williams** [comment]
@tessmgood  do you think that any of these error scenarios will need to also be translated over to the CSV export functionality? That might be a separate ticket that would follow sequentially after this one is done.

**Comment by tessmgood** [comment]
> @tessmgood do you think that any of these error scenarios will need to also be translated over to the CSV export functionality? That might be a separate ticket that would follow sequentially after this one is done.

good Q. For HFI we have the copy to clipboard (not export) function — a ND in cells that are missing data would be great (do we do this now?). We don't need to provide the feedback/error messages in the copy/paste workflow.

**Comment by conbrad** [comment]
Thank you for the detailed and unambiguous acceptance criteria @tessmgood 
I feel like I could already start work on this.

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1405?planning-poker) with ZenHub @andrea-williams @conbrad @Sybrand

**Comment by tessmgood** [comment]
missing 1+ specific index from Wx# (station issue) or not entered (Forecasting gap)
temperature cannot be null  (impacts DMC, BUI, ROS, HFI, FIG, Prep) 
RH cannot be null (impacts FFMC, ISI, ROS, HFI, FIG, Prep) 
wind speed cannot be null (impacts FFMC, ISI, ROS, HFI, FIG, Prep) 
wind direction cannot be null - exclude! 
precipitation cannot be null (impacts DC, BUI, ROS, HFI, FIG, Prep) 
grass cure cannot be null (impacts ROS, HFI, FIG, Prep)
