### ISSUE TITLE
Stop using BC Fire Weather Phase 1 

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1411]
**Describe the task**
Stop using BC Fire Weather Phase 1. Start using API

**Acceptance Criteria**
- [x] All cronjobs switched to the WF1 API.
- [x] All urls, usernames and code relating to the phase 1 site removed.
- [x] If there's already a forecast stored in our DB, and it differs from the forecast coming from WF1 API, then we handle that as a new forecast.
- [x] If there's already a forecast stored in our DB, and it does NOT differ from the forecast coming in from the WF1 API, then we handle it as an existing forecast and do not duplicate the forecast in our DB.

**Additional context**
- There may some issues around how forecasts work on the API.
- Historic forecasts aren't stored in their API; we will have to store all copies of forecasts as they're updated in our DB. Need a mechanism for figuring out that the forecast has changed (or not). (WF1 API has some fields such as `updatedDate` that may be able to be used. Will probably have to modify the structure of our DB slightly to record updated timestamp/datestamp).

**Comment by conbrad** [comment]
Hourly actuals already come from WFWX: https://github.com/bcgov/wps/pull/987

**Comment by conbrad** [comment]
Waiting on test data from forecasters to verify correctness.

**Comment by conbrad** [comment]
We can drop `danger_rating` completely -- the scope of our applications don't need it
