### ISSUE TITLE
HFI Weekly Table Day Headers should be sticky

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#1421]
**Describe the Bug**
Day headers on Weekly HFI table should be sticky, but they are not.

**Expected Behaviour**
When you scroll down on the Weekly HFI table, the day headers should stay in view atop the indices headers.

**Actual Behaviour**
The indices headers are sticky when scrolling, but the day headers disappear

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to Weekly HFI table page
2. Scroll down so that headers are not in view
3. See that only the indices headers are still in view

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by andrea-williams** [comment]
Closing this ticket. It appears to have already been fixed.
