### ISSUE TITLE
Update MaterialUI from v4 to v5

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#1424]
**Describe the task**
- Migrate MaterialUI from v4 to v5
- Make use of their codemods to automatically migrate: https://mui.com/guides/migration-v4/#run-codemods
- Most migration work will most likely be migrating from JSS

**Acceptance Criteria**
- [ ] Frontend builds and runs with v5

**Additional context**
- https://mui.com/guides/migration-v4/
- https://blog.wavebox.io/a-55-performance-improvement-upgrading-material-ui-from-v4-to-v5/
- https://mui.com/guides/interoperability/
- https://mui.com/system/basics/#installation
- https://mui.com/guides/styled-engine/
- https://github.com/mui-org/material-ui/tree/next/examples/create-react-app-with-styled-components-typescript

**Comment by conbrad** [comment]
Will also need to migrate `@material-ui/pickers` package too: https://mui.com/guides/pickers-migration/

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1424?planning-poker) with ZenHub @andrea-williams @conbrad @Sybrand

**Comment by conbrad** [comment]
Closed in favor of #1896 and #1898
