### ISSUE TITLE
FireBAT Map: Show Fire Zone outline

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1435]
**As a** _FBAN_ **I want** _to see the fire zone outlines_ **So That** _I can orient myself on the map in more detail (zones within a fire centre)_

**Additional Context**
- also applies to Fire Centre ticket: the Fire Centre are available as raster and vector layers from openmaps.gov.bc.ca ; the raster layers are ugly, and the vectors are too big. To get a nice display going, we're may to have to do something intelligent with the vector layers. (fastest way is to just use the rasters to begin with)
- For more about what layers are available, and how to use them, look at https://github.com/bcgov/smk and https://github.com/smnorris/bcdata
- See this excellent presentation on using DataBC open web services: https://docs.google.com/presentation/d/1ilacT1b3g1PlpxMtHgGsJD3xV3RQPQpBPzNmfJ1Iuc4/edit?usp=sharing
- It may be possible to query the zone polygons for a fire centre, but it's much easier to just use the raster layer.

**Acceptance Criteria**
- [x] Given I land on the new advisory page, and have selected a fire centre, Then I see the fire zones for the selected fire centre and the surrounding fire centres.
- [x] The fire zone polygon/raster data comes from openmaps.gov.bc.ca as described in additional context

**Definition of Done**
- [x] Ready to Demo in Sprint Review
- [x] Does what I have made have appropriate test coverage?
- [x] Documentation and/or scientific documentation exists and can be found
- [x] Peer Reviewed by 2 people on the team
- [x] Manual testing of all PRs in Dev and Prod
- [x] Merged

**Comment by Sybrand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1435?planning-poker) with ZenHub @andrea-williams @conbrad @JulianForeman

**Comment by andrea-williams** [comment]
1st AC: I don't think there is a "default" fire zone? There may be a preferred fire centre set in local storage, but I didn't think we were doing the same for zones bc the dropdown is only for fire centres? And aren't FBAs created on a per-FC basis, not per-zone?

**Comment by Sybrand** [comment]
> 1st AC: I don't think there is a "default" fire zone? There may be a preferred fire centre set in local storage, but I didn't think we were doing the same for zones bc the dropdown is only for fire centres? And aren't FBAs created on a per-FC basis, not per-zone?
> 
> IMO 1st AC should be rephrased: Given I land on the new advisory page, When I select a fire centre, then I see all zones within the fire centre rendered on the map

@andrea-williams I've edited it (sorry - that was copy/paste leftovers) - really what we want - is we want to see fire zones for the selected fire centre, and surrounding fire centres - in a way that isn't gross and confusing.
