### ISSUE TITLE
Keycloak implementation

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#147]
**Describe the task**
We need to have a keycloak instance for any of our products that will require authentication. 

**Acceptance Criteria**
- [x] File an issue on BCDevOps repository to request for Keycloak
- [x] BCeID Users can authenticate in dev and test environment
- [x] IDIR Users can Authenticate
- [x] Keycloak realm for dev environment
- [x] Keycloak realm for test environment
- [x] Keycloak realm for prod environment
- [x] Deny Access to users without IDIR or BCeID credentials

**Additional context**
- BCeID identity provider will not be enabled in the production realm until the IDIM team has given the approval. To speed up the process, initiate a conversation with the IDIM team at idim.consulting@gov.bc.ca on the details about BCeID usage ASAP!
- Shelly's team is currently in the phase of getting prepared for KeyCloak SSO service migration in which urls of these realms are changing from `sso.pathfinder.gov.bc.ca` to `oidc.gov.bc.ca`. There is no immediate actions to update our application or KeyCloak realms yet but there will be once we start using these realms. Reference can be found [here](https://developer.gov.bc.ca/BC-Government-KeyCloak-(RH-SSO)-Service-Migration-Plan)

**Keycloak Realm Links**
https://sso-test.pathfinder.gov.bc.ca/auth/admin/8wl6x4cp/console/
https://sso-dev.pathfinder.gov.bc.ca/auth/admin/8wl6x4cp/console/
https://sso.pathfinder.gov.bc.ca/auth/admin/8wl6x4cp/console/

**Comment by Kyubinhan** [comment]
@bradyholliday In order to create Keycloak Realms we need to answer all these required questions

![image](https://user-images.githubusercontent.com/36203857/77016105-fac9d000-6933-11ea-8238-88181b67ae6d.png)

![image](https://user-images.githubusercontent.com/36203857/77016251-6744cf00-6934-11ea-852f-2f7ab2eec8d4.png)

![image](https://user-images.githubusercontent.com/36203857/77016206-4aa89700-6934-11ea-8cc8-a221ca6ac46b.png)

**Comment by bradyholliday** [comment]
1. Organization Details:
Organization-Division-Branch-Program
Ministry FLNRORD -  BC Wildfire Service - Predictive Services

Executive Sponsor: Mary Myers, BC Wildfire Service, Mary.Myers@gov.bc.ca
Project Management / Business Lead: Brady Holliday, BC Wildfire Service, brady.holliday@gov.bc.ca
Technical Lead: Derek Roberts
Privacy Lead: Pawan Yadav, BC Wildfire Service, Pawan.Yadav@gov.bc.ca
Security Lead: Pawan Yadav, BC Wildfire Service, Pawan.Yadav@gov.bc.ca
Communications Lead: Brady Holliday, BC Wildfire Service, brady.holliday@gov.bc.ca 

2. Service
Name of Service: Wildfire Weather Calculator
Estimated Volume of Initial Users: 100
Growth over 3 years: 1500

3. Project
Date of release: 2020-05-01
Date of first use: 220-06-01

**Comment by Kyubinhan** [comment]
Keycloak Realms for test, dev, and prod have been created!

https://sso-dev.pathfinder.gov.bc.ca/auth/admin/8wl6x4cp/console/
https://sso-test.pathfinder.gov.bc.ca/auth/admin/8wl6x4cp/console/
https://sso.pathfinder.gov.bc.ca/auth/admin/8wl6x4cp/console/

**Comment by Kyubinhan** [comment]
Memo:
If you are requesting for BCeID to be integrated, please pay attention here: BCeID identity provider will not be enabled in the production realm for you until the IDIM team has given the approval. To speed up the process, initiate a conversation with the IDIM team at idim.consulting@gov.bc.ca on the details about BCeID usage ASAP!
