### ISSUE TITLE
Point at our own Fider Instance

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#148]
**Describe the task**
Currently our calculator application points at an instance of Fider create by Gary Wong, We need to point t the instance that Sy stood up. 

**Acceptance Criteria**
- [x] when I click the bug/contact button on the calculator our own instance of Fider opens
- [x] invite all the users that attend our sprint review

**Comment by Nkuruba** [comment]
Fider link URL updated and invitations sent to all sprint review attendees.
