### ISSUE TITLE
FireBAT Map: On load, show BC - or remember my last Fire Centre selection 

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1481]
**As a** *FBAN* **I want** *to see broad context (all of BC) if it's my first visit, or my last selected Fire Centre if I've used the tool previously* **So That** *I am served the most relevant and helpful experience/map context*

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] If there is no fire centre selected then we show entire province on the map
- [ ] Given I land on the new advisory page and page remembers my fire centre selection, Then I see the remembered fire centre rendered on the map 

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by Sybrand** [comment]
This is a duplicate of #1482
