### ISSUE TITLE
FireBAT Map: Zooming in on my fire centre

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1482]
**As a** *FBAN* **I want** *my selected Fire Centre to fill the map container (zoomed in)* **So That** *my view is focused on the region relevant to my job and I can see a reasonable amount of detail to begin my tasks*

**Additional Context**
- Implementation relies on the ability to query a geospatial server with the bounds of the Fire Centre.
- This is highly dependent on if we use ESRI or the WMS server.

**Acceptance Criteria**
- [x] If there is no fire centre selected then we show entire province on the map
- [x] Given I land on the new advisory page, the page remembers my previous fire centre selection, and the selection is zoomed in to the extent that the edges (boundaries) of the fire centre fill the map container 
- [x] When I select a fire centre, the map is zoomed in to the extent that the edges (boundaries) of the fire centre fill the map container.

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by Sybrand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1482?planning-poker) with ZenHub @andrea-williams @conbrad @JulianForeman
