### ISSUE TITLE
Fire Behaviour Calculator (OG tool): Table and Disclaimer are smushed together — where did the whitespace go? 

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1485]
**Describe the Bug**
Previously, there was whitespace between the table container and disclaimer table. Now they are stacked on top of each other, and this breaks the Design Law(TM) (proximity, grouping). 

**Expected Behaviour**
There is whitespace between page elements — e.g. margin-top 24px on disclaimer table (not a dev)
![Screen Shot 2021-10-27 at 2.46.33 PM.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/54f5333f-e558-45c9-8de0-b356f08a15c8)

**Actual Behaviour**
Smushed! Design jail. 
 ![Screen Shot 2021-10-27 at 2.40.51 PM.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/0155e1ad-43a7-4c92-962e-49307f274975)

** Steps To Reproduce**
Steps to reproduce the behaviour:

**Desktop (please complete the following information):**

**Additional context**
- Optional: read this for context https://medium.muz.li/gestalt-principles-in-ui-design-6b75a41e9965

**Comment by conbrad** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1485?planning-poker) with ZenHub @Sybrand
