### ISSUE TITLE
User Research on Zone Wildfire Officer Workflow

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#149]
**Describe the task**
Research on the preparedness staff in wildfire services starting with Zone level staff.

**Acceptance Criteria**
- [x]  Interview with Zone Wildfire Officer
- [ ]  Documentation on Zone Wildfire Officer Workflow
- [x]  Determine appropriate platform for user

**Comment by bradyholliday** [comment]
Email was sent to all fire centre SWOO's to canvas for names of people to interview for ZWCO and RWCO positions. I have heard back from Kamloops and Cariboo and have passed names on to Prakriti. Names are also posted on the Preparedness Miro Board https://miro.com/app/board/o9J_kvf9lAQ=/

**Comment by PrakritiM** [comment]
[Uploading... Preparedness Staff User Experience Interview Questions.docx ]

**Comment by PrakritiM** [comment]
Filled Questionnaire


[https://app.zenhub.com/files/235861506/ce16428c-f3f3-4b2e-a789-6b69c2bbf95a/download](https://app.zenhub.com/files/235861506/ce16428c-f3f3-4b2e-a789-6b69c2bbf95a/download)

**Comment by PrakritiM** [comment]
Skype interview updated  questionnaire

[https://app.zenhub.com/files/235861506/295129d2-43da-4e94-869d-d848fbfc302e/download](https://app.zenhub.com/files/235861506/295129d2-43da-4e94-869d-d848fbfc302e/download)

**Comment by PrakritiM** [comment]
Documentation 
https://miro.com/app/board/o9J_ku7DTZQ=/
