### ISSUE TITLE
FireBAT Make Header Tooltips Not Scroll Off Table

### ISSUE THREAD

**Issue by JulianForeman** [bcgov/wps#1492]
While using FireBAT I want tooltips to show up when headers are hovered and not overflow off the table if the cell is too close to the right

**Additional Context**
- Scroll table over so that a long header is touching the right side of the table and hover over it, it should move the tooltip to the left instead of having it cut off

**Acceptance Criteria**
- [x] When any tooltip is hovered the full thing is shown, not cutoff and does not expand the table

**Definition of Done**
- [x] Ready to Demo in Sprint Review
- [x] Does what I have made have appropriate test coverage?
- [x] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by Sybrand** [comment]
I started writing some code for this - it worked for me - just needs some tinkering.

```
return (
    <Paper elevation={1}>
      <ThemeProvider theme={fireTableTheme}>
        <TableContainer
          data-testid={'fire-table'}
          id={'fire-table'}
          className={useStyles().tableContainer}
        >
          <Table data-testid={props.testId} stickyHeader>
            {props.children}
          </Table>
        </TableContainer>
      </ThemeProvider>
    </Paper>
  )
```
```
const hover = (e: MouseEvent<HTMLDivElement>) => {
    const fireTable = document.getElementById('fire-table')
    if (fireTable) {
      const child = e.currentTarget.children[0] as HTMLSpanElement
      // clone the span, throw it into the dom, and measure the length of the text.
      const clone = child.cloneNode(true) as HTMLSpanElement
      clone.style.visibility = 'hidden'
      clone.style.position = 'absolute'
      e.currentTarget.appendChild(clone)
      const textWidth = clone.getBoundingClientRect().width
      clone.remove()
      if (
        e.currentTarget.getBoundingClientRect().left + textWidth >=
        fireTable.getBoundingClientRect().right
      ) {
        const delta =
          fireTable.getBoundingClientRect().right -
          (e.currentTarget.getBoundingClientRect().left + textWidth)
        setLeft(delta)
      } else {
        setLeft(0)
      }
    }
  }
```

**Comment by Sybrand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1492?planning-poker) with ZenHub @andrea-williams @conbrad @JulianForeman
