### ISSUE TITLE
Display Zone code in FireBat even if weather data not available for station

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#1499]
**As a** *user of the tinkering FireBat tool (Tinkerbell? TinkerBat?)* **I want** *to be able to see the zone code corresponding to each fire station in the table* **So That** *I always know what zone/planning area the station belongs to, regardless of the availability of WFWX data for the station*

**Additional Context**
- right now the zone code for the station is only displayed in the table if retrieval of weather data is successful
- **UX:** omitting the zone makes it difficult for FBANs to manage their list of stations - they think in Zones, and want to see stations that are erroring out in order - it better fits their process of evaluating the indices and calcs., zone by zone. **UX goal:** this is a consistent approach in all table based interfaces that include a zone column

![Screen Shot 2021-11-10 at 10.50.57 AM.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/55905bc0-49b9-4a00-863e-2dcd0f50d553)

**Acceptance Criteria**
- [ ] Given I am in TinkerBat, When I select a weather station from the dropdown, Then the station's zone code is immediately displayed in the table
- [x] Given I am in TinkerBat, When I select a weather station for which there is no weather data available (e.g., select a date in the future, but no forecast has been issued), the Zone Code appears in the table even though no weather data is displayed

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by conbrad** [comment]
This should just be adding `zone_code` to `StationResponse` and `FBAStation` since `WFWXWeatherStation` already has it no?

**Comment by andrea-williams** [comment]
`FBAStation` appears to already have a `zone_code` property. I don't have a clear enough mental picture of all the different data models and how they fit together to be able to answer this question with confidence.

But in short, it shouldn't be a difficult fix.

**Comment by Sybrand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1499?planning-poker) with ZenHub @andrea-williams @conbrad
