### ISSUE TITLE
User Research Zone Wildfire Coordination officer

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#150]
**Describe the task**
Research on the preparedness staff in wildfire services starting with Zone level staff.

**Acceptance Criteria**
- [x]  Interview with Zone Wildfire Coordination Officer
- [x]  Documentation on Zone Wildfire Coordination Officer Workflow
- [x]  Determine appropriate platform for user

**Comment by bradyholliday** [comment]
Email was sent to all fire centre SWOO's to canvas for names of people to interview for ZWCO and RWCO positions. I have heard back from Kamloops and Cariboo and have passed names on to Prakriti. Names are also posted on the Preparedness Miro Board https://miro.com/app/board/o9J_kvf9lAQ=/

**Comment by PrakritiM** [comment]
https://miro.com/app/board/o9J_ku72qP8=/
