### ISSUE TITLE
Switch to https://maps.gov.bc.ca/arcserver/rest/ for FireCenter layer

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#1504]
**Background**
Currently our Fire Center map layer talks to the openmaps.gov.bc.ca WMS server to get the fire centers displayed on the map.
WMS exposes a set of capabilities, which includes styles; the styles published for fire centers are limited and colors/labels are static. It is possible to request specific colors for things through Styled Layer Description requests (https://www.nrcan.gc.ca/earth-sciences/geomatics/canadas-spatial-data-infrastructure/styled-layer-descriptor-sld/8926#Functional%20Description)

The above is a cumbersome assembling of XML formats without tooling to quickly test it.

https://maps.gov.bc.ca/ess/hm/imap4m/ shows a differently colored Fire Center layer and it uses customized colors. 
Inspecting it's requests shows that it's talking to an ARCGIS rest server.

We also talk to an arcgis rest server for MoreCast: https://github.com/bcgov/wps/blob/b30d07c2d1ad8d8edb4e4d228e94751cbe45c302/web/src/features/fireWeather/components/maps/constants.ts#L4

**Describe the task**
- Figure out how to get the FireCenter layer from https://maps.gov.bc.ca/arcgis/rest/
    - Probably best to talk to Michelle Douville
- Replace our WMS layer in new FireBAT to use a layer that talks to arcgis
- Color map outlines with a color other than orange to 

**Acceptance Criteria**
- [ ] Fire Center map layer talks to https://maps.gov.bc.ca/arcgis/rest/, not WMS
- [ ] Fire Center outlines are not orange so that it doesn't confuse with orange HFI color

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by conbrad** [comment]
Polygon layer available at: https://governmentofbc.maps.arcgis.com/home/item.html?id=2940b49bcf9a458191a55c21d58f922f

**Comment by conbrad** [comment]
OpenLayers esri polygon support and example: https://openlayers.org/en/latest/examples/vector-esri.html

**Comment by conbrad** [comment]
I think we can close this, the current PR I'm working on uses the arcserver for drawing polygons:https://github.com/bcgov/wps/pull/1516

As we've run into some issues performance wise with this, maybe we change this ticket to implement perf improvements (client side caching of polygons)? Or close this ticket and open a new one.

**Comment by Sybrand** [comment]
@conbrad agreed. this task now redundant.
