### ISSUE TITLE
Demonstrate an end to end test

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#151]
**Describe the task**
Demonstrate an end to end test

**Acceptance Criteria**
- [x] Demonstrate an end to end test running on a local machine.
- [x] Test should go from disclaimer, all the way through to calculate.
- [x] Always use three default stations - by index, e.g. no 2, 6, 8
- [x] Test should not rely on any particular calculation response.

**Additional context**
- Testing platform may be decided by developer.
- We want a repeatable test - no random aspect.

**Comment by Nkuruba** [comment]
Updated test case to use options with indices 1,2,3 by default, irrespective of weather station names.
