### ISSUE TITLE
Vector proxy

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1524]
**Describe the task**
Proxy server that serves up to vector tiles, but uses a vector server as backing.

e.g.

Openlayers -> [ vector tiles ] -> Proxy -> [ Vectors ] -> Vector Server

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by conbrad** [comment]
Looks like this is our best option for now.
