### ISSUE TITLE
FireBAT Map: Add labels to the map

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1526]
**As a** *FBAN/FBS* **I want** *Fire Centre, Zone, and Weather Station labels displayed on the map* **So That** *I can quickly orient myself when reviewing the map and crafting advice*

**Additional Context**
- all labels are black (font colour) 
- let's collaborate: intent it to start showing the labels as soon as it makes sense on a zoom level 
- future ticket (?) this displays 'nicely' (labels are legible) when zoomed to a FC not only in FireBAT but when captured in the PDF: end-users/recipients of FBAs can read the labels
- context: FBANs know the province and their FCs well, but still can't be expected to pinpoint the location of every weather station on a map by name. It's also easy to forget which zone which station is in, by name only. During the summer, FBANs can support other FCs (not their main/home Centre) - making this context even more important. 
- see examples: https://openlayers.org/en/latest/examples/vector-label-decluttering.html and https://openlayers.org/en/latest/examples/vector-labels.html

**Acceptance Criteria**
- [x] Given I am using FireBAT, When the map loads for the first time (all of BC), Then I only see Fire Centre labels
- [x] Given I am using FireBAT, When I select or zoom to a Fire Centre, Then I see the Zone labels 
- [x] Given I am using FireBAT, When I select or zoom to a Fire Centre, Then I see the Weather Station labels  
- [x] Given I am using FireBAT, When I select or zoom to a Fire Centre, Then I do not see the Fire Centre label
- [x] #1586 Duplicate Fire Centre labels are no longer duplicating  
- [x] Single label for a fire center/fire zone at any one time in the map view

**Definition of Done**
- [x] Ready to Demo in Sprint Review
- [x] Does what I have made have appropriate test coverage?
- [x] Documentation and/or scientific documentation exists and can be found
- [x] Peer Reviewed by 2 people on the team
- [x] Manual testing of all PRs in Dev and Prod
- [x] Merged

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1526?planning-poker) with ZenHub @andrea-williams @conbrad @Sybrand

**Comment by Sybrand** [comment]
I want to scope creep this story and include the duplicate label issue in here - I think they need to be solved together.
