### ISSUE TITLE
FireBAT Table: Add columns to be included in the FBA

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1537]
**As a** *FBAN/FBS* **I want** *to see a summary of fire behaviour indices and calculations* **So That** *I can quickly scan the context (e.g. severity) for stations crossing thresholds, and so that the required information per OSWS #5 is automatically generated*

**Additional Context**
- Does this need to be sticky (header, first columns)? I want to see what happens with our layout
- Andrea to add the branch name

**Acceptance Criteria**
- [ ] Conor: Make a story for re-evaluating the grid/table
- [x] Given I am using FireBAT, When I view the table, Then I see the following columns with headings:
  - Zone (just the code)
  - Weather Station 
  - Fuel Type
  - Grass Cure 
  - Wind Speed
  - HFI 
  - Critical Hours 4,000 Kw/m
  - Critical Hours 10,000 Kw/m 
  - ROS
  - 30 min Fire Size
  - 60 min Fire Size 
  - Fire Type 
- [ ] Implemented consistently with Fire Behaviour Calculator (styling, labels) 
- [x] Table should be 50% of screen, Map is still 50% of screen
- [ ] Remove nested scroll windows for table
- [ ] Make table header row sticky when scrolling vertically
- [ ] Make zone, station, & fuel type columns sticky when scrolling horizontally (confirm this w/ TG)
- [ ] Add loading indicator for table data
- [ ] Fix sorting by zone - in Coastal FC, zone order appears as V1 > V10 > V2... Should be V1 > V2 > ... > V10.

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1537?planning-poker) with ZenHub @andrea-williams @conbrad @JulianForeman @Sybrand

**Comment by andrea-williams** [comment]
This is outstanding work to do as of start of innovation sprint:

- [ ] Remove nested scroll windows for table
- [ ] make table header row sticky when scrolling vertically
- [ ] make zone, station, & fuel type columns sticky when scrolling horizontally (confirm this w/ TG)
- [ ] add loading indicator for table data
- [ ] fix sorting by zone - in Coastal FC, zone order appears as V1 > V10 > V2... Should be V1 > V2 > ... > V10.
- [ ] separate PR to pluralize CFFDRS still in progress (CB)
- [ ] speed up algorithm for calculating critical hours (right now it's brute-forcing. Need it to be faster). Possibly use Newton's method (algo implement in scikit), apply it to vector of values using pandas' `apply()`

**Comment by andrea-williams** [comment]
Pluralizing CFFDRS has been made into a separate ticket - #1660 
Speeding up calculations for critical hours has been made into a separate ticket - #1794

**Comment by conbrad** [comment]
Split this out into 2 tickets, #1902 and #1903
