### ISSUE TITLE
Missing zone polygons on map

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#1547]
**Describe the Bug**
The fire bat advisory map is missing fire zones. Eric pointed out Horsefly and 100 Mile zones are missing from the Cariboo fire center.

**Expected Behaviour**
Horsefly and 100 Mile zones should show on the map within the Cariboo fire center.

**Actual Behaviour**
No Horsefly and 100 Mile zones show up!

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://wps-prod.apps.silver.devops.gov.bc.ca/fire-behaviour-advisory
2. Wait for polygons to load
3. Select Cariboo Fire Center
4. See missing zones

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
This may be a CORs issue with our requests:
![Screen Shot 2021-11-17 at 1.55.17 PM.png](https://images.zenhubusercontent.com/60464f96048353febabb5c8d/b263a98f-68f3-4baf-a029-65ddbbce2569)

**Comment by Sybrand** [comment]
I say we hold off on this until we have clarity on the direction we're taking. If we're going to be using the geoserver, then this may fall away.

**Comment by Sybrand** [comment]
Switching to pg_tileserv resolved this.
