### ISSUE TITLE
Research Team Coco's Github Action Pipeline Solution

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#155]
**Describe the task**
Investigate Coco's GitHub Actions pipeline.  Come up with a list of questions or suggestions for them.  Beginning planning a WPS implementation of GitHub Actions.

**Acceptance Criteria**
- [x] Research Coco's GH Actions
- [x] Research alternatives (e.g. Red Hat's offering)
- [x] GH Actions in general
- [x] List of unknowns to be discussed with PSU Team / Team Coco
- [x] Book Coco meeting

**Additional context**
Here are those comments/suggestions:
1. Will you or WPS be continuing development?
2. Providing project admin rights to a stranger's Docker build is scary.
3. Makefile is quite rigid.
4. There's a Red Hat offering. https://github.com/redhat-developer/openshift-actions
5. No option to consume our own buildconfigs.
6. No option to consume our own deploymentconfigs.
7. No option to consume our oc scripts, which is a deal breaker.

**Comment by DerekRoberts** [comment]
https://github.com/bcgov/openshift-launchpad-deployment
