### ISSUE TITLE
HFI Calculator: Convert Fire Starts cell to a drop down in Planning Area row

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1551]
**As a** *R/ZWCO* **I want** *to adjust the number of predicted fire starts using historical fire starts for that day plus current local risk (e.g. long weekends, festivals, weather events)* **So That** *I can calculate an accurate Prep Level*

**Additional Context**
- until we get further down the road with FOP prediction, we need a way to adjust Fire Starts, given that starts are a key part of the Prep equation **(Mean Intensity Group x Fire Starts = Prep Level)**
  - users should always like to be able to adjust the Fire Starts value, even with a perfect predictive FOP model there are still human variables to account for, for example a big music festival on the weekend (higher risk of human starts)
- DECISION - USE SAME STARTS (KFC) FOR ALL FCs: #1627 KFC uses a different range of Fire Starts to calculate their Prep Levels - as we bring in the other 5 Fire Centres, do we load a different range for them (the current 'official' range) or do they adjust to KFC range? (this creates operations work for them, impacting their prep sheets, policies/procedures)
- [figma](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2021?node-id=1126%3A18185)

**Acceptance Criteria**
- [ ] Given I am using the HFI Calculator, When I am using the weekly or daily views, Then the Fire Starts cells in a planning area row are a dropdown with ranges 
- [x] The Fire Start ranges for ~Kamloops~ all Fire Centres are 0-1, 1-2, 2-3, 3-6, 6+
- [x] Given I select a Fire Start range, the Prep Level is (re)calculated accordingly (Mean Intensity Group x Fire Starts = Prep Level)
- [x] The Fire Start value will be a default value of 0-1 to start, understanding that a blank loading state is likely a better approach, for a future ticket? ([Figma for what empty and partial states would look like](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2022?node-id=1123%3A12944))
- [ ] The selected Fire Start value and resulting Prep Level are reflected in the copy-to-clipboard workflow 
- [ ] TBD Given a Prep Level is recalculating, the relevant planning area row uses a shimmer effect when loading (same as Fire Behaviour Calculator) - if fast, this is unnecessary

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by andrea-williams** [comment]
I think another item for acceptance criteria in this ticket (or maaayyybe it's a separate ticket?) is adjusting the Copy-to-Clipboard-as-CSV functionality to also reflect the Fire Starts value. Right now it's hard-coded to '0-1' in the clipboard logic too

**Comment by conbrad** [comment]
Does this require the permissions infrastructure we discussed in daily?
