### ISSUE TITLE
HFI Calculator: Include/Exclude number of days in prep cycle (weekly view)

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1552]
**As a** *Z/RWCO* **I want** *to choose how many days are in each prep period* **So That** *the calculated prep is averaging the correct number of days*

**Additional Context**
- a prep period can be 2-5 days long, depending on long weekends and whether its a Monday or a Thursday prep day
- presently we're providing a rigid 5 day prep period (per HFI Workbook)
- the problem: if a prep period is only 3 or 4 days, but we're including a 5th day, the Calculated Prep level may be incorrect (too high or too low, if the extra days bump it up or down)
- path 1: dropdown, path 2: slider - at dev discretion (fastest) 
- how might we ensure that this change is visible to all users of the HFI Calculator _within the same Fire Centre_? 
- insert screenshots here (sorry @conbrad - missed this). [Figma ](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2022?node-id=1117%3A6279)
![Hide Prep Days 1.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/71659545-fe68-4fc4-b61d-b31918c07981)

**Acceptance Criteria**
- [ ] Given I am using the HFI Calculator, I see a default of 5 days in a prep period (the maximum)
- [ ] Given I am using the HFI Calculator, I can exclude 1-3 days in that prep period (the minimum: 2 days) by interacting with a slider or dropdown. Valid values are 2, 3, 4, or 5 days in a prep period 
- [ ] Given I change prep period to 4 days, it removes 5th day from table view and daily tabs 
- [ ] Change persists for user per browser session, pending #1634 decision 
- [ ] Changing number of days in prep period is captured in copy-to-clipboard workflow

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by andrea-williams** [comment]
Do we have wireframes for what the interface would look like for excluding/adding a day (and saving the changes)?

**Comment by conbrad** [comment]
Sounds like this also needs permissions infra, and some configuration database for each fire center.

**Comment by tessmgood** [comment]
@andrea-williams I have a proposal, it relies on #1570 - a design pattern Ambrose wireframed, now I understand why.  We dropped it because we/I didn't realize the significance, or we just went for a simpler technical implementation. 
[Figma link ](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2021?node-id=635%3A3452)
![Screen Shot 2021-11-23 at 3.10.59 PM.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/6f595c5c-42a1-4151-98eb-31a5ae63ff3d)

**Comment by Sybrand** [comment]
@tessmgood does this have to persist across the entire fire centre?

**Comment by tessmgood** [comment]
@Sybrand yes, that's what I mean by the final bullet under additional context. Otherwise, a ZWCO and an RWCO both accountable on prep morning are possibly seeing different prep levels.
