### ISSUE TITLE
HFI Calculator: Swap toggle order - display weekly view (prep period) first

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1557]
**As a** *Z/RWCO* **I want** *to see the prep cycle context on launching the web app* **So That** *I can quickly see the prep context for the next few days*

**Additional Context**
- digging into the dailies is a secondary analysis task 
- see #1570 (how AY originally wireframed the flow, prep/weekly first, then all the days in the prep cycle) 

**Acceptance Criteria**
- [x] Given I am using the HFI Calculator, When I open the app, Then I see the weekly context first - clarification: the order of the toggle is now Weekly - Daily
- [x] Given I am using the HFI Calculator, The weekly toggle is renamed to 'Prep Period'

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1557?planning-poker) with ZenHub @conbrad @JulianForeman @Sybrand
