### ISSUE TITLE
HFI Calculator: Adjust colour coding of Mean FIG and FIG cells

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1558]
**As a** *Z/RWCO* **I want** *the prep values to grab my attention* **So That** *I can focus on the most relevant values and reduce the risk of human error (mistaking FIG for Prep)*

**Additional Context**
- [Figma](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2021?node-id=635%3A3452)
- error prevention (happens now in HFI Workbook) and clarity - this tool needs to support fast decision making, it must be crystal clear and deeply trusted to be effective, users can sometimes confuse FIG and Prep and set the wrong prep level 

**Acceptance Criteria**
- [x] Given I am using HFI Calculator, When I view the weekly table/Prep Period, Then only Prep is colour coded, FIG is not
- [x] Given I am using HFI Calculator, When I view the daily table, Then only Prep is colour coded, FIG is not
- [x] Given I am using HFI Calculator, When I view the weekly table/Prep Period, Then daily Prep values are outlined with a border, white fill (per prep level colour coding, see Figma) 
- [x] Given I am using HFI Calculator, When I view the weekly table/Prep Period, Then the final Calculated Prep value is filled (per prep level colour coding, see Figma) 

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1558?planning-poker) with ZenHub @andrea-williams @conbrad @JulianForeman @Sybrand
