### ISSUE TITLE
HFI Calculator: Add daily buttons for each day in the prep period 

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1570]
**As a** *Z/RWCO* **I want** *to quickly, easily see the daily context (weather, fire behaviour) underpinning the calculated prep level* **So That** *I can assess the situation accurately, confidently make decisions, and act quickly*

**Additional Context**
- AY wireframed this, it got dropped [Figma](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2022?node-id=1117%3A6279)
 ![Hide Prep Days 1.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/808ddb4b-d9c1-4f14-8325-ff6dd3162c52)

**Acceptance Criteria**
- [x] Given I am using HFI Calculator, I see a 5 day prep period by default at the top of the tool 
- [x] "Prep Period" = current weekly table
- [x] Similar to the weekly table logic, Day 1 is either a Monday or a Thursday 
- [x] Clicking a specific day loads that 'daily' view
- [x] Each day is labelled as Day X (1-5), then displays an abbreviated day of week (Mon Tue Wed Thur Fri Sat Sun), abbreviated Month (Jan, Feb, Mar... etc.), and day of the month (1-31)

**Definition of Done**
- [x] Ready to Demo in Sprint Review
- [x] Does what I have made have appropriate test coverage?
- [x] Documentation and/or scientific documentation exists and can be found
- [x] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by conbrad** [comment]
Does this mean the daily and weekly toggle is removed, and clicking on a day shows that daily view?

**Comment by tessmgood** [comment]
@conbrad sorta. Toggle isn't removed, just expanded and label changes. 
Weekly is renamed to Prep Period, and ordered first. Daily is duplicated 5x with more precise labels.
