### ISSUE TITLE
HFI Calculator: Add blue border to top of planning area row

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1571]
**As a** *Z/RWCO* **I want** *to easily scan and differentiate information in the table* **So That** *I can quickly, confidently understand what I'm looking at and make decisions*

**Additional Context**
-  in testing, users are finding it difficult to tell which data is related to each other, they're asking for better interface cues to clarify grouping of information 
- [Figma ](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2021?node-id=635%3A3452)
 

**Acceptance Criteria**
- [x] Given I am using HFI Calc., When I am viewing the weekly view, Then there is a 2px blue (003366) border at the top of the planning area row
- [x] Given I am using HFI Calc., When I am viewing the daily view, Then there is a 2px blue (003366) border at the top of the planning area row

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1571?planning-poker) with ZenHub @conbrad @JulianForeman @Sybrand
