### ISSUE TITLE
SPIKE - HFI Calculator: Investigate IDIR Permissions (edit) 

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1572]
**Describe the task**
Investigate what would be involved in assigning specific IDIRs edit permissions for the HFI Calc., to ensure that only the folks with prep day responsibilities are able to tinker with fuels and FOP. And ensure that their changes are visible to all users. 

**WHY?** This tool is meant to get each Fire Centre to a final calculated Prep Level for a given prep period, starting on a Monday or Thursday. 
- Some values need to be changed, such as Predicted Fire Starts (Fire Occurrence Prediction), to calculate Prep Level. 
  - It is anticipated that users will be able to modify the number of days in a prep cycle (2-5, depending on start day and long weekends) which impacts final calculated Prep Level, and fuel types may also be editable. 
- Many folks collaborate on prep day - ZWCOs and RWCOs. If they all modify the table locally, and therefore see different numbers, operations chaos is likely to ensue. 
  - consider that once this exists and people are aware of the tool, more folks at the Provincial, Fire Centre, or Zone level are likely going to want to open this tool for a quick Preparedness scan. _This may even introduce new requirements for interface feedback, indicating that Prep Levels have been confirmed/approved by RWCO and prep is 'set'_ (date/time stamp, IDIR?)
- If each Z/RWCO can see different numbers based on their local changes, this would not facilitate fast operations decisions and would instead introduce offline communications requirements, friction, doubt, additional time, and may impact trust/adoption of HFI Calc. 

_What is the leanest way of mitigating this risk?_

**Acceptance Criteria**
TBD: 
- [ ] consensus on what the "admin" interface is. (the place where our p.o. will be assigning roles & permissions)
- [ ] technical demonstration of how permissions are to be checked on the API. (.e.g. post fails without "write" permission)
- [ ] technical demonstration of how permissions are to be checked on the front end. 
- [ ] proposal on naming & granularity of different permissions - this needs to be forward looking to ensure that the permissions we create are future proof. (this may be a working document to serve as guidance for administrators to understand what rights they're assigning.) e.g. "modify hfi calculator fuel type", as opposed to just "edit".
- [ ] proposal on construction of groups & permissions - will establish the level of granularity of permissions we're concerned with.   (e.g. the role: "hfi edit" may consist of the permissions : "modify hfi calculator fuel type" and "modify hfi calculator fire occurance")
- [ ] investigate
- [ ] collaboration with design and product
- [ ] findings / requirements captured / stories written

**Additional context**

- As an HFI Calc. user, when I log in with an IDIR, if I have edit permissions I see select or edit fields for fuel type, grass cure, FOP
- As an HFI Calc. user, when I log in with an IDIR, if I have edit permissions and change a select field (fuel/grass cure, FOP) I get a popup telling me that my changes will be reflected for all users. I can accept, cancel, and select 'don't show me this again'
- As an HFI Calc. user, when I log in with any IDIR, if I have not been granted edit permissions, I do not see any select or editable fields
- As an HFI Calc. user, when I log in, regardless of my permissions, I see any changes made by users with edit permissions
- Sr. Wildfire Officers - Ops have indicated that they can provide a list
- considerations around the generic IDIRS: RWCO,OPS,Dispatch in each fire centre? should they always have access? any risks? 
- clarify admin interface:
  - Need to be able to switch gears quickly (TEAMS or outside Province resources coming in) - how and who can grant permissions? where? 
    - all outside resources get an IDIR  
    - everyone in PSU can grant permissions?
    -  how might we plug into the TEAMS workflow for granting permissions? do we?
- auditing changes - do we need to surface this (front-end), what detail do we need? 
- common services working on this - token auth mechanism. Look into this 
- flag this with Vivid (P1, P2) IDIR vs BCID 
- priority: lean, fast adjustments (it's 6am, someone needs access NOW)
- leverage existing solutions. e.g. leverage keycloak as much as possible.

**Comment by Sybrand** [comment]
@tessmgood do outside resources have idir's or bceid or something else?

**Comment by Sybrand** [comment]
@tessmgood I removed reference to "view" permissions - since that would imply that we have to grant users permission to view the HFICalc. I'm working on the assumption that anyone with an IDIR can see stuff - it's not a role, it's just what you get by default. (I may be wrong, let me know - for example - it may be that we need to assign view permissions before someone is able to see the site at all)
