### ISSUE TITLE
MoreCast  2.0: MVP Wireframes

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1578]
**Describe the task**
A clear and concise description of what the task is.

**Acceptance Criteria**
- [x] make sense of workshop
- [ ] wireframe
- [ ] schedule feedback / collaboration follow up w Forecasters, Dev, Product (scope, feasibility, refinement)

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by NicolasLivanos** [comment]
https://www.figma.com/proto/F07weH0KqPEWBQVVUm5CcW/MoreCast-Template?node-id=1%3A80&scaling=min-zoom&page-id=0%3A1

**Comment by rajpersram** [comment]
There's no mockup coming up for this as far as I can see. Not much detail here anyhow. Probably a candidate for closing.
