### ISSUE TITLE
Deduplicate map labels

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#1583]
**Describe the task**
Deduplicate feature labels for fire centers and fire zones.

**Acceptance Criteria**
- [ ] Single label for a fire center/fire zone at any one time in the map view

**Additional context**
- Fire center and zone features are returned in multiple chunks depending on your zoom level, the feature styling will return a label for the polygon for every feature. Need a way to deduplicate the feature labels

**Comment by nmathava** [comment]
This work is included in ticket 1526
