### ISSUE TITLE
[FEATURE] 90% Weather Calculator

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/wps#16]
90% Weather is one of the factors that is used in funding applications through the Community resilience Investment Program (CRIP).
 https://intranet.gov.bc.ca/bcws/provincial-programs/prevention/crip

90% Weather Calculator will ensure a standard method for calculating this value to ensure consistent and accurate evaluation of proposals. 

Community communication initiatives (?)
Simulating effects of wildfires near communities
Uses weather stations (290) to calculate indexes
Massaging numbers, looking for work in communities

Build a calculator:
 - Pull from weather database
 - Look at indexes
 - Calculate - consultant "90% weather statuses, calculate consistent numbers"
 - Open, transparent
 - Current weather db ~400 MB, 1954 onward
 - Analysis for: climate change, decades in varying timeframes
 - Narrow down to certain attributes
 - Consultants, current staff; on current website?
 - Towards allocating millions of dollars (~12.5M?) in funding

Indexes:
 - fine fuel moisture (will a fire start?)
 - initial spread index (is it going to start and spread?)
 - build up index (if starts, will it consume and produce heat energy)
 - more available

Data:
 - 13:00 readings report, 17:00 calculated 90% daily, 24 daily indexes/blocks
 - relative humidity, dew point, elevation
 - analysis on core season (May 15 - Sept 15?, June 1 - Aug 31?)
 - start collecting when snow-free, end late October

=> Use this work as a proof of utility/viability!

dana.hicks@gov.bc.ca
brady.holliday@gov.bc.ca

BCWS Notes:
 - works at a different pace than we might be used to
 - days vs weeks

**Comment by DerekRoberts** [comment]
Brady
=> "@danahicks2 has Story boards for this calculator. Need to start story mapping and start scoping out what the development of this will involve."

Jake
=> "User Groups:
- anybody who is preparing a Community protection plan/funding proposal
- Consultants from private companies engaged by a community
- Internal BCWS Staff involved in reviewing funding applications (Prevention Staff)

Prevention Staff persona (Zone, Regional, Provincial)
Consultant Persona
?Community Staff involved in funding request submission?"

Brady
=> "Brady
 => "@jake_morris @danahicks2 Can you think of any other user groups for this service? Do you have people in mind that we could reach out to as the end users?"

**Comment by bradyholliday** [comment]
Here is the initial story requirements for the 90% Weather calculator
[https://app.zenhub.com/files/235861506/dfd3d2f2-ceee-4e13-907b-50bba2ea18bd/download](https://app.zenhub.com/files/235861506/dfd3d2f2-ceee-4e13-907b-50bba2ea18bd/download)

**Comment by DerekRoberts** [comment]
[https://app.zenhub.com/files/235861506/ce25741b-7edc-44ed-8b42-92168c35ff6e/download](https://app.zenhub.com/files/235861506/ce25741b-7edc-44ed-8b42-92168c35ff6e/download)
