### ISSUE TITLE
HFI Calculator: Math differs between KFC and other FCs

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1627]
**As a** *Z/RWCO* **I want** *the calculated Prep Level to reflect the Fire Occurrence Prediction ranges relevant to my Fire Centre* **So That** *I can calculate Prep accurately which facilitates resourcing decisions - e.g. a Prep 3 means X resources needed, a Prep 4 means X + Y resources needed*

**Additional Context**
- Kamloops sees a lot of fire activity, so they modified their Prep Level calculation (predicted fire starts variable) - people are aware of this shift, but it does deviate from the Provincial process followed by all other FCs
  - KFC predicted starts: 0-1, 1-2, 2-3, 3-6, 6+
  - Other FCs predicted starts: 0-2, 3-5, 6-10, 11-14, 15+
  - Previously DH indicated to go ahead with these values, and that they may become a new standard
  - For now, I believe we need to do both calculations (Kamloops math, other 5 FCs math) given that the resulting Prep Level maps to a lot of resourcing decisions 
  - Kamloops ![KamloopsFC_HFIcalc_PrepLevelMath.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/9e7514f2-b763-4c60-a2e4-5cf985ab6944)
  - Other 5 FCs ![SoutheastFC_HFIcalc_PrepLevelMath.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/1f2197b5-b018-4d22-a9d8-25e47652ab85)

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by andrea-williams** [comment]
decision from Dana: use Kamloops's math. Daily starts
