### ISSUE TITLE
Investigate "ProtocolError("Connection broken: InvalidChunkLength" error in Patroni instance in PROD

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#1631]
**Describe the task**
The logs for the Patroni pods in PROD are largely full of Error messages saying
`ERROR: ObjectCache.run ProtocolError("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))`

I don't know what the cause of this is, but it seems like it's something that should be investigated and resolved, otherwise it's just flooding our Patroni logs.

**Acceptance Criteria**
- [ ] Determine what the cause of this repeated error message is
- [ ] If warranted, resolve the cause of the issue. Otherwise, it would be nice to turn the warning off so it doesn't get logged.

**Additional context**
![Screen Shot 2021-12-22 at 8.58.51 AM.png](https://images.zenhubusercontent.com/5e331ea54a0d32f8650c9a25/eb70f693-6b65-45fc-880a-b0399f74cd67)

**Comment by conbrad** [comment]
We're running crunchydb deployment now, no patroni errors
