### ISSUE TITLE
HFI Calc: All users see same information vs. local changes 

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1634]
**As a** *Z/RWCO* **I want** *everyone to see the same information* **So That** *there is no uncertainty and collaboration between Z/RWCOs is supported on prep morning*

**Additional Context**
Decision taken to go with path 1
- path 1: changes to values such as FOP and number of prep days in cycle are visible to all users
- path 2: changes to values such as FOP and number of prep days in cycle are local to that user - collaborators would see different information - OPERATIONS RISK 
- assumption: a final version of the prep levels is saved as spreadsheet / PDF
- how might we prevent a user from leaving the page without saving changes? 
  - [javascript prompt if someone hits back, refresh, etc](https://www.geeksforgeeks.org/how-to-display-warning-before-leaving-the-web-page-with-unsaved-changes-using-javascript/). (they can choose not to save, the warning is the important part)

**Acceptance Criteria**
SS: I'm not sure how to start on acceptance criteria, so I'm going to throw out some premises to get a conversation going:
Premise 1. : Changes are only persisted when a big fast save button is pressed - and said save button informs user that changes will affect all users.
Premise 2.: If two of us are changing things at the same time, whomsoever presses save last, is going to overwrite the other persons work.
Premise 3.: To start with, we don't need fancy stuff like seeing who made the change when and what the default value is/was.

- [x] Extract "load" action.
- [x] Extract "change fire starts" action.
- [x] Extract "select/deselect station" action.
- [x] Extract "pdf" action.
- [x] Extract "change prep period" action.
- [x] Remove save changes button.

State 1: No changes made. Save button disabled 
- [x] Given I open the HFI Calculator, When no inputs are changed (fuel, fire starts), Then the new 'Save changes' button is disabled (nothing to save) - download function is available
![No changes - Save disabled, Download active.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/7cbc3087-d92f-4d5f-b40d-6bf51ba5b540)

State 2: Changes made. Save button active, Download PDF disabled
- [x] Given I **change** a value in one of the select fields (fuel type, fire start), Then the 'Save changes' button becomes available - indicating action is required 
- [x] Given I **change** a value in one of the select fields (fuel type, fire start), Then the 'Download PDF (current: copy to clipboard) button is disabled - I cannot download this data until saved
![Changes pending - Save button active - download disabled.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/269a332f-cb8d-44e7-8269-b792b7addceb)

State 3: Successful save communicated by toast message (snackbar) - Save button disabled, Download PDF available.
- [x] Given I **change** a value in one of the select fields (fuel type, fire start), When I press 'Save' and it is successful, Then a green success toast message (BC success #2E8540) displays and download function becomes available
![Successful Save - Toast.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/e81b76d3-504e-4342-a2bb-94d256cb9b68)

State 4: Unsuccessful save (e.g. someone was saving at the exact same time, or something went wrong)
- [x] Given I **change** a value in one of the select fields (fuel type, fire start), When I press 'Save' and it is unsuccessful, Then a red error toast message (BC error #D8292F) displays and download function remains unavailable. Further, the fields that did not save are outlined with the same red error colour 
![Unsuccessful Save - Toast (1).png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/329be323-390c-4137-bb0d-c79c07eda0d6)

State 5: I made changes, but I didn't save them, and now I'm leaving my browser tab / hitting back / hitting refresh, etc. 
- [x] Given I **change** a value in one of the select fields (fuel type, fire start), When I try to leave the webpage without pressing 'Save', Then a javascript prompt reminds me to save before leaving, with the option to cancel if I don't want to save those changes  

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1634?planning-poker) with ZenHub @andrea-williams @conbrad @Sybrand
