### ISSUE TITLE
HFI Calculator: Add C7b Fuel Type 

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1637]
**As a** *FBAN, Z/RWCO* **I want** *to be able to use a modified C7b fuel type* **So That** *I can more accurately calculate risk based on grass curing (C7 assumes 100% grass curing - can result in fire behaviour calculations that don't reflect reality throughout the season)*

**Additional Context**
- Adding C7b in the HFI Calculator does NOT imply implementation in the Fire Behaviour Calculator and Fire Behaviour Advisory Tool (with map). Doing say will most probably be a separate ticket.
- [NewC7b - C7 with curing3 spreadsheet here](https://bcgov.sharepoint.com/:x:/t/01324/EeQQM1ckzmJImI0MgchuG9wBeRpgo8N2CzQjnx7gs3Sepg?e=YRIOCr), please consult DH
- DH Q: will grass curing come from WFWX or is it a requirement that it is editable in HFI interface? A new process was mentioned where forecasters input grass curing - where has this landed? DECISION: NOT EDITABLE, API

**Acceptance Criteria**
- [x] Given I'm viewing the HFI calculator, When there is a station with C7b, Then all fields are calculated, displayed and exported appropriately as they would be for any other fuel type.

**Definition of Done**
- [x] Ready to Demo in Sprint Review
- [x] Does what I have made have appropriate test coverage?
- [x] Documentation and/or scientific documentation exists and can be found
- [x] Peer Reviewed by 2 people on the team
- [x] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by conbrad** [comment]
We have a ticket to change harcoded fuel types to dropdown inputs: https://app.zenhub.com/workspaces/wildfire-predictive-services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1555

Not sure where it lands on the roadmap, it may be a big change.

**Comment by andrea-williams** [comment]
re: impact on Fire Bat Tool & Calculator - I thiiiiiiink that the work done for this ticket will almost automatically translate over to FireBat without any additional work needed. Except possibly for making Grass Cure a mandatory field when C7b is selected??

**Comment by andrea-williams** [comment]
We'll need more info from a SME on what values should be used as defaults for Percentage Confider, Crown Base Height, etc. for C7b in order to be able to do the redapp calculations.

**Comment by Sybrand** [comment]
@andrea-williams  re. firebat impact - depending on how the calculations are presented, it's not going to automagically appear in firebat. We're chaining together a bunch of function sin the cffdrs library - I don't think we can necessarily just slot in c7b and have it work in both places. If it work - that's awesome, but I want to be sure we limit the scope.

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1637?planning-poker) with ZenHub @andrea-williams @conbrad @JulianForeman @Sybrand
