### ISSUE TITLE
HFI Calculator: Final output workflow: Download PDF

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1638]
**As a** *RWCO, or Plans/Ops person* **I want** *to save the calculated prep levels* **So That** *I have a moment-in-time capture and record of Prep Level decisions, knowing that data can change later that day or in following days. This is a requirement for approval, record keeping, and any future information requests that could arise following an incident.*

**Additional Context**
- Decision: PDF output that captures Prep Period and all dailies 
- relates to #1634 save/download interactions
- current workbooks appear to be [optimized to print to PDF](https://bcgov.sharepoint.com/:b:/t/01324/EZFNBDqPB5hDt24h6oCW35UBc3xkwwixEklD9Sxv3JCc9Q?e=ssrQod): landscape orientation, legal size, narrow margins, scaled to fit with no page breaks — TG creating word mockup now, will test w/ users (Ops Group)
![Screen Shot 2022-02-14 at 4.37.55 PM.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/a2e2eac9-d752-4638-ad4c-74c2ee5430a0)
- The expectation is that the we'll account for all the information being present in this pdf, but the layout and styling will be best effort. We expect that we'll iterate on the styling and layout - so the focus must be on information.
 
**Acceptance Criteria**
- [x] 'Copy to clipboard' is changed to 'Download PDF' _insert Figma w icon and placement_
- [x] The PDF output contains the Prep Period and all Daily Tabs per the prep range selected per #1671
- [x] The document contains the date and time that it was generated.
- [x] The document contains the idir of the user who generated it.
- [x] The filename of the download must contain the follow the format FIRECENTRENAME_HFICALCULATOR_DATEDOWNLOADED_IDIR.pdf

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1638?planning-poker) with ZenHub @andrea-williams @conbrad @JulianForeman @Sybrand

**Comment by conbrad** [comment]
Based on where are current tickets are at, I think we're well positioned to tackle this. AC is clear and I don't see any other blockers or questions at the moment, besides the formatting as @tessmgood pointed out.

**Comment by andrea-williams** [comment]
I liked Sy's proposal discussed recently - first iteration should just be getting the necessary data into a PDF, largely ignoring formatting, then make a second iteration with the nice formatting. So, assuming we're taking that approach, is this ticket just to dump the data into a PDF and ignore formatting? Secondly, do we have a mockup or some kind of example of what the nicely-formatted PDF should look like? At this point I'm struggling to imagine how we could fit a full-width table onto an A4 sheet.
