### ISSUE TITLE
HFI Calculator: Restructure page header

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1650]
**As a** *Z/RWCO* **I want** *a clear interface* **So That** *I can easily understand the info and actions as displayed and make clear decisions*
  
**Additional Context**
![Screen Shot 2022-01-17 at 9.37.49 AM.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/3307ed96-d737-477b-a2d9-e2bc9f66a6bb)

**Acceptance Criteria**
- [x] remove 'Predictive Services Unit' as primary header - change to 'HFI Calculator' 
- [x] change 'Contact' link to include this context: 'Contact Predictive Services Unit'
- [ ] move date selection and fire centre dropdown to secondary menu bar (similar to MoreCast header) 
- [ ] move 'About this data' modal link to the secondary header (right side)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by conbrad** [comment]
Easy to move the date selector up to the page title, tricky bit will be styling it with colors, and padding to fit in the hardcoded 60px height of the page header.

**Comment by andrea-williams** [comment]
Since my current ticket (#1626) includes adding a dropdown to select the fire centre, I could just include these AC in my current ticket...

**Comment by Sybrand** [comment]
@andrea-williams I'd advise against scope creep in #1626...

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1650?planning-poker) with ZenHub @andrea-williams @conbrad @JulianForeman @Sybrand
