### ISSUE TITLE
HFI Calculator: Relabel date picker and disable non-prep days  

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1655]
**NOTE: This is likely to be replaced by 1671** 

**As a** *Plans/Ops person, Z/WCO* **I want** *clear interface feedback and support* **So That** *I understand how to navigate between prep cycles, and then work within prep cycles/daily context*

**Additional Context**
- the date picker is for navigating between prep periods, UI and functionality changes to clarify this 
![Prep start date - selective picker.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/f9353020-254a-4b4c-8ea4-fdc5f7f582bd)
-
```
&lt;KeyboardDatePicker
        data-testid="date-of-interest-picker"
        label={props.label ? props.label : 'Date of Interest (PST-08:00)'}
        inputVariant="outlined"
        value={props.date}
        format="yyyy/MM/dd"
        allowKeyboardControl={true}
        shouldDisableDate={(day: MaterialUiPickersDate) =&rt;
          day?.weekday !== 1 && day?.weekday !== 4
        }
...
```

**Acceptance Criteria**
- [ ] Default date in the select component is the same date as the start of the table/prep period (e.g. if today is Tuesday, Jan 18 the date picker defaults to Monday, Jan 17 - the start of the prep period)
- [ ] Date selection relabelled to 'Prep start date' 
- [ ] Non-prep days are disabled, you can only select Mondays and Thursdays 

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by andrea-williams** [comment]
what happens when Monday is a stat holiday - is Monday still considered the first day of the prep period?

**Comment by tessmgood** [comment]
^ good question for workshop today and DH in standup (decision). If prep day isn't always Mon/Thurs (current assumption) [I do have a proposed solution](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2022?node-id=1158%3A3838) - it would change our prep period table logic and date picker structure

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1655?planning-poker) with ZenHub @andrea-williams @conbrad @JulianForeman @Sybrand

**Comment by tessmgood** [comment]
PAUSE - re-evaluate per #1671

**Comment by tessmgood** [comment]
Declined - new requirements emerged
