### ISSUE TITLE
HFI Calculator: Solution for "Blended - BL" fuel type 

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1658]
**As a** *Prep day user in Coastal FC (Z/RWCO, Plans/Ops)* **I want** *to see an adequate replacement to the unofficial BL Blended fuel type in my current HFI Workbook spreadsheet* **So That** *the calculations in the HFI Calculator are as accurate as possible given fuels and geography in Coastal Fire Centre*

**Additional Context**
- Decision: use M2 25% Conifer for Blended but duplicate it in the table
  - BL abbreviation but M2 25% Conifer 
- Assumption: Users will be educated / informed and know that M2 25% Conifer is to be used in place of blended fuel type. 
- Not sure there's much to do re. implementation here, other than ensuring we have stations with this fuel type configured, as all the coding should already be in place. (We already have M2 25% in FireBAT)

**Acceptance Criteria**
- [ ] Given I have selected some prep period / day, then stations that would traditionally be allocated the "Blend" fuel type, will have the fuel type "M2 25%" but it will be labelled as Blended on the front-end
- [ ] Given I download the csv data for some prep period / day, then stations that would traditionally be allocated the "Blend" fuel type, will have a the fuel type "M2 25%"

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by andrea-williams** [comment]
For HFI calc, I believe all that needs to be done for this ticket is to update the wx stations (all in Coastal FC?) that have BL specified in their HFI workbook, but which will have C5 as their assigned fuel type at the moment. Just need to update these stations in our DB to use M2 25% instead - it's an easy fix.

**Comment by conbrad** [comment]
+1 to @andrea-williams's comment
