### ISSUE TITLE
Add bash script for deploying to Openshift from local

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#1670]
**Describe the task**
Add a devops script to our codebase that allows for making a full deployment to Openshift from local.

**Acceptance Criteria**
- [x] Script exists in codebase that allows for deployment to a parameterized location in Openshift (once user has authenticated via Openshift CLI)
- [x] Script includes a required parameter for specifying the suffix (i.e., PR #) for deployment
- [ ] Script's code should be shared with `production.yml` to avoid code duplication

**Additional context**
- There recently has been a need for a script that does this since sometimes deployment is blocked by certain failed GitHub Actions that shouldn't be failing - e.g., Codecov analysis sometimes hangs for days and can't be restarted.
- Conor & Andrea have mostly-complete versions of this script in their local. Minor cleanup required

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1670?planning-poker) with ZenHub @andrea-williams @conbrad @Sybrand
