### ISSUE TITLE
HFI Calculator: Iteration — Prep start flexibility (not always Monday/Thursday)

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1671]
**As a** *Z/RWCO* **I want** *flexibility when setting the prep period, including start day of week (beyond Mon/Thur)* **So That** *I can still produce accurate calculated Prep Levels when stat holidays, long weekends, shoulder season, and other similar scenarios arise*

Thursday is the primary prep day - the main event
- Monday is a check in and recalibrate as necessary

For clarity: if extra days are included in the prep period, e.g. a stat holiday came up:
- in advance of the stat, I would have set a longer prep on Thursday (Thursday to Tuesday - 6 days) 
- coming back from the stat on Tuesday would be the next prep day (not Monday)
- if Monday were included in this new prep period (per current logic) it would be included in the mean calculation for final prep level, and could risk skewing the numbers 

Also: this fall/winter Northwest, Coastal were using 7 day prep periods, others may do the same in shoulder seasons
A prep period could also be a single day

**Additional Context**
- [Material Design pattern / docs](https://material.io/components/date-pickers#anatomy)
- !date range is a ['pro' Material UI](https://mui.com/components/date-range-picker/) component 
- A default prep-period must be pre-loaded into the database. There's no point writing user interactions for a use case that would only every happen once (e.g. there's only on time that a fire centre would not have a prep period saved).
- ![Prep range - date range.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/716c6066-12a4-44bc-9b1b-b429061d065d)
- ![Prep range - date range-1.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/33606f95-308f-449f-b5fb-63e708308ec5)

**Acceptance Criteria**
- [x] Given I've navigated to the HFI Calc Page, Then there is no longer a "prep days" dropdown (i.e. current functionality to select duration of prep is gone).
- [x] Given I've navigated to the HFI Calc Page, Then the most recently persisted prep period is populated. (see additional context - there will ALWAYS be a prep period saved)
- [x] Given I've selected the date range picker, I am only able to select a valid prep period.
- [x] Given I've changed the prep period, Then pressing the save button will persist the prep period, for the selected fire centre for all users.
- [x] Given I'm using the date range picker, I am limited to a prep period between 1 and 7 days inclusive.

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by andrea-williams** [comment]
Questions/Things to Consider:

- do we implement this before or after #1634 ?
- does anyone with an IDIR have permission to set the prep start date?
- If the implementation we go for is something similar to the date picker in the screenshot above, presumably we'd need a way to set a max (7 days?) for the number of days that can be selected in a prep period.

**Comment by conbrad** [comment]
I have the same questions as above for me. Also, I think we can use the range picker I used for FWI calculator for now, but would be nice to migrate to Material UI v5 and use their implementation instead.

The one I used in FWI has a CSS bug I'm not sure how to fix:
![Screen Shot 2022-02-01 at 1.15.54 PM.png](https://images.zenhubusercontent.com/60464f96048353febabb5c8d/9c705297-a016-467d-8f81-8643c17d2969)

**Comment by tessmgood** [comment]
Thanks @conbrad I think that maps to my alternate option linked in the body of the ticket (Figma link) — Prep Period could be a single day, is that easy with the FWI pattern?

**Comment by conbrad** [comment]
> Thanks @conbrad I think that maps to my alternate option linked in the body of the ticket (Figma link) — Prep Period could be a single day, is that easy with the FWI pattern?

Sorry @tessmgood, which part of the Figma link? Is it the screenshot of the existing single day picker we use for the prep start day? If so, yes that could work. Although we do need to upgrade that component to Material v5 at some point too.

**Comment by andrea-williams** [comment]
Free alternatives to Material UI's paid date range component:
DateRangePicker by rsuitejs - https://rsuitejs.com/components/date-range-picker/
