### ISSUE TITLE
HFI Calculator: Iteration — Update Planning areas and weather stations (Fire Centre feedback)

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1673]
**As a** *Z/RWCO* **I want** *to see the list of representative weather stations, grouped by planning area, in an order that supports prep day operations* **So That** *the calculated Prep Level is generated with the correct weather station points in my fire centre and the HFI tool fits seamlessly into my prep workflows*

**Additional Context**
- DH sourcing list from each FC, building a spreadsheet - 
https://bcgov.sharepoint.com/:x:/t/01324/ERUFb3IkzmhJmWH3i2u6QMwBh_D5Ln3RtdIpSbmWGoEsLw?e=1MDJoD

- Sr. Wildfire Officers - Operations will give a final stamp of approval for each Fire Centre (Ops CoP meeting?) 
- This is really something we're going to have to devolve to users with an admin interface, to take us (developers) out of the loop. This is really something that we could limit to the PSU super to do.
- Decision on BL fuel for Coastal: use M2 25% Conifer for Blended but duplicate it in the back-end
  - we will essentially have two M2 25% conifers: BL abbreviation = M2 25% Conifer + the regular M2 25% option (thinking ahead to when we have a dropdown) 

**Acceptance Criteria**
- [x] Given have selected a fire centre, When interacting with page, Then I see the expected weather stations group in planning areas that match. (see spreadsheet in additional context)
- [x] The order of the stations need to match the order in the spreadsheet.
- [x] Given I have selected some prep period / day, then stations that would traditionally be allocated the "Blend" fuel type, will have the fuel type "M2 25%" but it will be labelled as Blended on the front-end
- [x] Given I download the csv data for some prep period / day, then stations that would traditionally be allocated the "Blend" fuel type, will have a the fuel type "M2 25%"

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by andrea-williams** [comment]
I took a quick peek at the spreadsheet that DH has pulled together so far (for 2 fire centres). There aren't fuel types specified for the weather stations in that new file. 
*If* a fire centre wants to add a weather station that hasn't previously appeared in the HFI workbooks, we'll also need to know their desired fuel type, otherwise it will become a blocker during implementation.

**Comment by conbrad** [comment]
+1 to @andrea-williams 's comment

**Comment by nmathava** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1673?planning-poker) with ZenHub @Sybrand

**Comment by nmathava** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1673?planning-poker) with ZenHub @JulianForeman
