### ISSUE TITLE
HFI Calculator: Remove station code numbers from the weather station names (applies to all products)

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1674]
**As a** Z/RWCO **I want** see the weather stations names without station codes  **So That** *less confusing to general users*

**Additional Context**
- JE mentioned that station code is redundant.

**Acceptance Criteria**
- [x] Given I'm on the HFI , Whenever I look at a station, Then there's no station code visible.

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by andrea-williams** [comment]
This would just be a matter of removing ${station.code} from the HFI weekly and daily view tables. 30-second fix. Stations would still be referenced by their codes in the background.

**Comment by andrea-williams** [comment]
As a point of curiosity - was it only JE who requested this change in sprint review, or have there been requests from other people too?

**Comment by conbrad** [comment]
+1 to what @andrea-williams  mentioned

**Comment by tessmgood** [comment]
We've been talking about this for a while - it first came up from Ben. Users don't know the stations by codes, I've done some digging and haven't found any of our users who finds this info to be helpful context, re: our products and associated tasks. 
- some questions I asked: what happens if two weather station names are similar and you need to differentiate them (e.g. Blue River 2 vs. Blue River DL) can station code help you do that? 
- I believe it was Ben who demo'd that you can't even look up weather station numbers in WFWX for example, not searchable — redundant info for our group
