### ISSUE TITLE
HFI calculations are done on the backend

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#1685]
**Describe the task**
Currently the calculations are performed in the frontend in `hfiCalculationSlice.ts` They should be computed on the backend so it can be leveraged for generated a PDF.

**Acceptance Criteria**
- [x] Migrate calculations from frontend to backend
- [ ] Frontend now requests the calculations from the backend instead of doing them on the frontend

**Additional context**
- All calculations and data structures can be found in `hfiCalculationSlice.ts`

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1685?planning-poker) with ZenHub @conbrad @JulianForeman @Sybrand
