### ISSUE TITLE
HFI Calc: All users see same information - the basics

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1686]
**As a** *Z/RWCO* **I want** *everyone to see the same information* **So That** *there is no uncertainty and collaboration between Z/RWCOs is supported on prep morning*

**Additional Context**
- Changes to values such as FOP and are visible to all users.
- Prep period is NOT persisted/saved - every time you go to the page, you have to select the period.
- User's won't see changes other users are making until they re-load.
- If multiple users are making changes at the same time, they may be over-writing each others changes.
- There is a follow up ticket (#1634) that addresses many UX issues.

**Acceptance Criteria**

- [x] Given I **change** a value in one of the select fields (fuel type, fire start), Then when I press the save button, the change will be persisted for all users.
- [x] Given I **check/unhcheck** a station, Then when I press the save button, the change will be persisted for all users.
- [x] Given a value in a select field has been saved, Then when I load data, I see the modified value.
- [x] Given a station has been **check/unchecked** and save has been clicked, Then when I load data, I see the modified value.

**Additional tasks**
- [x] Add more tests (don't have good tests to validate calculations at the moment)
- [ ] Have to address the date nightmare on the front end. Too much jumping between different date time formats!!!
- [ ] Some refactoring (moving code out of hfi router, to app.hfi module)
- [ ] Other code cleanup

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1686?planning-poker) with ZenHub @conbrad @JulianForeman @Sybrand
