### ISSUE TITLE
HFI PDF generated on backend

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#1687]
**Describe the task**
Instead of copying a CSV generated on the frontend, the user can download a ~~excel spreadsheet~~ PDF with the weekly prep sheet *and daily outputs* that are generated on the backend.

**Acceptance Criteria**
- [ ] ~~Spreadsheet~~ PDF output uses the calculated HFI results from #1685
- [ ] Initially just include station name and prep level columns
- [ ] Copy to clipboard button becomes download ~~excel~~ ~~spreadsheet~~ PDF button, clicking on it downloads the ~~spreadsheet~~ PDF from the backend

**Additional context**
- Remove CSV code on frontend.
- For XLS: consider: openpyxl : https://openpyxl.readthedocs.io/en/stable/ ; https://pypi.org/project/openpyxl/

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1687?planning-poker) with ZenHub @Sybrand @conbrad @JulianForeman
