### ISSUE TITLE
Update our API interaction with WF1 to work with WF1's API changes

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#1689]
**Describe the task**
On ~Feb 22, WF1 will be rolling out a new version of the API that involves changes to their schema - particularly the `station` object (among others). We'll need to ensure that our API remains compatible with WF1's new schema(s).

**Acceptance Criteria**
- [x] Update PSU test environment to point to a wfwx instance with the new api changes.
- [x] ~~Test~~ Integration environment for any breaking changes.
- [ ] Get a list of all the changes they're making with their new API version / update documentation - store updated documentation in our teams folders.
- [ ] Create a ticket for fixing any issues found.

**Additional context**
- DylanH's message: https://chat.developer.gov.bc.ca/channel/wildfire-wfwx?msg=ft3b8zJLFrSpMFvjd
- If we get their Test environment access details, we should hook up to their test environment too

**Comment by conbrad** [comment]
Use integration credentials to set up test environment, still waiting on test env creds.
