### ISSUE TITLE
HFI Calculator: Adjust Mean Intensity Group rounding 

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1707]
**Describe the task**
Mean Intensity Group rounding adjustment was requested by Ops CoP: higher than x.8 round UP, lower than x.8 round DOWN

**Context**
- There is a Mean Intensity Group for every day in the prep period 
  - It is the mean of all weather station intensity groups in that planning area
- The Mean Intensity Group (MIG) should be rounded up or down, per the acceptance criteria, then used to calculate prep level 
  - rounded MIG x fire starts = prep level 
  - ![Screen Shot 2022-02-15 at 2.26.34 PM.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/7925e671-a7b0-48d0-a18a-ee9e69fecfe8)

**Acceptance Criteria**
- [x] When a mean intensity group is x.8 or higher, round up 
- [x] When a mean intensity group is lower than x.8, round down

**Comment by conbrad** [comment]
Looks go to me, no questions.

**Comment by Sybrand** [comment]
@tessmgood I think the math is wrong.
Shouldn't the second condition be:  "lower than x.8, round down"?

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1707?planning-poker) with ZenHub @andrea-williams @conbrad @Sybrand
