### ISSUE TITLE
User Research Weather Forecasters

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#171]
**Describe the task**
user research with forecasters regarding meteostar software, preparedness workflow, what data they are interested in and how they currently get that data

**Acceptance Criteria**
- [x] Contact weather forecasters
- [x] create questionnaire for interview
- [x] Conduct Interview
- [x] Workflow documented
- [x] list of data sources used by forecasters

**Additional context**
- we see these forecasters as a primary user for the FWI calculator
- linked but not dependent on user research on Fire Behaviour Analyst

Contacts are:
Jesse Ellis Jesse.Ellis@gov.bc.ca
Paul Emmett Paul.Emmett@gov.bc.ca
Robert Rowson wxrowson@shaw.ca
Christina Van Eaton wxvaneaton@gmail.com
Robert Pigott envirobc@telus.net 
David Jones meteorologistdavidjones@shaw.ca

**Comment by PrakritiM** [comment]
[https://app.zenhub.com/files/235861506/bf9c7297-8399-4167-8388-272c9317471a/download](https://app.zenhub.com/files/235861506/bf9c7297-8399-4167-8388-272c9317471a/download)

**Comment by PrakritiM** [comment]
List of Data Sources:

![image.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/bc377d65-76f2-4662-9a98-08aa72570303)

**Comment by PrakritiM** [comment]
https://miro.com/app/board/o9J_ktow2OY=/

**Comment by PrakritiM** [comment]
Christina's interview pending
