### ISSUE TITLE
HFI Calculator: Adjust position of forecast time stamp

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1710]
**Describe the task**
The tickets for restructuring the HFI header and forecast timestamp happened in an order that pushed forecast timestamp into a temporary position. As a follow-up, moving the timestamp up beside the Fire Centre dropdown. 

![Screen Shot 2022-02-15 at 2.39.09 PM.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/c3dd0c05-8a5a-4a20-8e69-254d21a65020)

**Acceptance Criteria**
- [x] when visible, the forecast last updated timestamp is placed beside the date range selector
- [ ] all elements: Fire Centre, Date Range, Timestamp are 8px apart

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by andrea-williams** [comment]
Straightforward. Don't see any issues with this one.

**Comment by conbrad** [comment]
+1 to @andrea-williams 's comment above

**Comment by nmathava** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1710?planning-poker) with ZenHub @andrea-williams @conbrad @Sybrand
