### ISSUE TITLE
Import Daily Actual Weather Data

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#174]
**As a** *meteorologist and fire behaviour specialist * **I want** *to import actual weather data from the BCWS weather database* **So That** *I can perform analysis on actual data as well as have a starting point to calculate FWI indices on forecast data*

**Additional Context**
- need access to WxPh3 API
- Will need to decide whether we import raw weather data or data with calculated indices 

**Acceptance Criteria**
- [ ] Given I have provided all parameters, When I select a weather station(s), Then actual weather data is imported
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by jowand** [comment]
superseded by #238
