### ISSUE TITLE
HFI Calculator: API failure results in forever spinner - need some kind of error message.

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1795]
**Describe the Bug**
Any failure on the back-end, will result in the spinner spinning forever. We need to handle errors (500, 404 etc. etc.) from the back end, so that user can take appropriate action.

**Expected Behaviour**
Pattern: There is an error - refresh - contact us. Specific error code. 

![Screen Shot 2021-09-15 at 2.45 1.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/a25bd972-cd75-41af-84f2-0405674ac211)

**Actual Behaviour**

**Steps To Reproduce**
Steps to reproduce the behaviour:
Easiest, as a developer, stop your database server - it will result in API giving 500 errors.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by conbrad** [comment]
We already have an error catch all message on the frontend. Can you provide reproduction steps?

**Comment by conbrad** [comment]
There's probably an API error we're not subscribing to, or there's been a regression: https://github.com/bcgov/wps/blob/62d314e4d0fea9f883144ddd3d319d6025e6a122/web/src/features/hfiCalculator/pages/HfiCalculatorPage.tsx#L274

**Comment by conbrad** [comment]
Design is modelled in figma in the original ticket: https://app.zenhub.com/workspaces/wildfire-predictive-services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1405
