### ISSUE TITLE
HFI Calculator: Daily tables - move grass curing beside fuel type

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1796]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- Grass cure is in the correct position in prep period table
- in daily table, grass cure is between the weather parameters and fire behaviour indices, please move beside fuel type (per prep period table) 

**Acceptance Criteria**
- [ ] Given I am using HFI Calc., When I click a 'daily' tab, Then grass cure column is immediately after the fuel type column
- [ ] This change is reflected in the PDF export  
 
**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by conbrad** [comment]
Clear and straightforward

**Comment by andrea-williams** [comment]
Possibly missing an AC re: moving GC column in the PDF too?

**Comment by Sybrand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1796?planning-poker) with ZenHub @andrea-williams @conbrad @JulianForeman
