### ISSUE TITLE
HFI Calculator: Colour code the HFI thresholds (4,000+ and 10,000+) 

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1797]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- colour code HFI values 4000-9999 as orange and 10000+ as red, consistent with Fire Behaviour Calculator 
- users want to have their attention quickly called to high HFI values (HFI x fire starts = prep level) 
- the colour coding supports contextual decision making and attention-grabbing in the interface, it is not critical in the PDF export at this time (if/when we do eventually export colour coding, e.g. prep levels, we should export this as well)

**Acceptance Criteria**
- [ ] Given I am using HFI Calc., When HFI for any station in prep or daily table is 0-3999, Then no additional styling is applied
- [ ] Given I am using HFI Calc., When HFI for any station in prep or daily table is 4000-9999, Then the cell is highlighted in orange, per FBCalc.
- [ ] Given I am using HFI Calc., When HFI for any station in prep or daily table is 10000+, Then the cell is highlighted in red, per FBCalc. 
- [ ] Do not do this for PDF.

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by conbrad** [comment]
Looks straightforward

**Comment by andrea-williams** [comment]
Would this styling also apply to the PDF?

**Comment by tessmgood** [comment]
> Would this styling also apply to the PDF?

Good Q. Not at this time. No colours are being exported aside from some basic planning area row styling for scannability - clarified under additional context.
