### ISSUE TITLE
HFI Calculator: Calculate/display danger class in daily tables

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1798]
**Additional Context**
- users have asked us to keep this column (we discussed removing)
- **the danger class column is always empty: why?** 
- danger class *should* be coming from wildfire 1

**Acceptance Criteria**
- [x] Given I am using HFI Calc., When I am viewing a daily table, Then I see a danger class for all selected weather stations 
- [x] Given I export to PDF, Then the danger class column is included 

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by andrea-williams** [comment]
I consider this ticket to already be groomed.

**Comment by Sybrand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1798?planning-poker) with ZenHub @andrea-williams @conbrad @JulianForeman

**Comment by conbrad** [comment]
Waiting on response from WFWX: https://chat.developer.gov.bc.ca/channel/wildfire-wfwx?msg=zBkmQLR6cve8E3ohK

**Comment by conbrad** [comment]
FYI: https://wfapps.nrs.gov.bc.ca/pub/wfwx-danger-summary-war/dangerSummary
