### ISSUE TITLE
HFI Calc - selecting different FC doesn't reset to Weekly View

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#1800]
**Describe the Bug**
After looking at one of the daily tabs in HFI Calc, changing the fire centre creates confusion because it's not clear what date the table is displaying data (that might not exist) for.

**Expected Behaviour**
Changing the selected fire centre should automatically reset view to Prep Period summary.

**Actual Behaviour**
Changing the selected fire centre after viewing a Daily table keeps the view on the same date, even if that date is no longer relevant to the newly selected FC.

** Acceptance Criteria **
- [ ] Need a unit test to ensure this doesn't break again.

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to HFI Calc
2. Select a random date in the past, and a random fire centre. Wait for the page data to load
3. Select Day 1 in the daily view tabs
4. Select some different fire centre; wait for page data to load
5. Table with load with skeleton of daily view, but table likely has no data in it, and none of the tabs are highlighted blue, so user doesn't know what date they're looking at.

**Screenshots**
 ![Screen Shot 2022-03-18 at 4.34.52 PM.png](https://images.zenhubusercontent.com/5e331ea54a0d32f8650c9a25/eeb78e1f-0a0d-4098-9e48-26f16821c82d)

^ Here I selected a date in Sept 2021 for Prince George FC, clicked Day 1 of tabs, then selected Coastal FC. After network call complete, this is the view I get. What date am I looking at? Well I'm probably looking at the September date I originally requested for PG, but UI suggests I'm looking at a prep period in March 2022. Clicking on any of the tabs shown will then actually give me the results for Coastal for March 18 prep.

**Comment by conbrad** [comment]
Clear and straightforward

**Comment by andrea-williams** [comment]
Have confirmed that this bug still exists with the new prep date range structure.
