### ISSUE TITLE
HFI Calculator: Interface usability — proximity principle in header (placement of fire centre and date picker fields, alignment of prep period bar)

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1815]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- A and I previously worked on this, but recent changes may revert this work. This is a placeholder for now.
- the gestalt (cognitive psychology x ui) principle of proximity matters because it tells a user how our interface works without using any words. In this case, the fire centre and date picker fields are the first two decisions that go together to generate your desired prep tables. Grouping them close together signals a relationship, or 1 step in the process. 
- the other alignment issues (vertical leftmost orange bar) may be related to our grid and better addressed in upcoming responsive tickets? open to suggestions/implementation insight

![Screen Shot 2022-03-28 at 8.52.46 AM.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/4ffbf7f8-b81c-47cd-9fd9-e02eccb8ef4b)

![proximity.gif](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/e0867bee-ec04-4498-a9c4-34e37321ff4d)

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by conbrad** [comment]
Relates to: https://app.zenhub.com/workspaces/wildfire-predictive-services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1827
