### ISSUE TITLE
Deploy C-Haines Graphic Chart in Openshift

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#183]
**As a** *Fire Behaviour Analyst)* **I want** *to be able to view the latest C-Haines display* **So That** *I can use this information to make better fire behaviour predictions*

**Additional Context**
- Look alternate method to be able to pull the C-Haines graphic out of Meteostar and into Openshift where it can be put onto a web dashboard for use by FBANS
- Joanna Wand is the contact that has started this work with Robert Rowson and IITD
- Call set up on April 1 to go over the FTP transfer process

**Acceptance Criteria**
- [ ] Given Automated scheduled workflow is set up in LEADS, When new data comes in, Then an updated C-Haines chart is displayed on the dashboard.
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by Sybrand** [comment]
@jakemorr not quite a duplicate - but I think this has been superseded?
