### ISSUE TITLE
Migrate away from CFFDRS if they don't move away from rgdal

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#1835]
**Describe the task**
If we continue to use R for CFFDRS, the `rgdal` library we depend on will be unsupported by the end of 2023.

`Please note that rgdal will be retired by the end of 2023,
plan transition to sf/stars/terra functions using GDAL and PROJ
at your earliest convenience.`

**Acceptance Criteria**
- [ ] Get our stack to work with `sf/starts/terra`

**Additional context**
- https://github.com/rspatial/terra

**Comment by Sybrand** [comment]
@conbrad don't know that this is in our control. It would be on CFFDRS to make the appropriate change. If they don't do it, we'd have to fork CFFDRS and make the change there.
