### ISSUE TITLE
HFI Calc: Pop up to notify folks not to tinker, their changes are visible to the whole fire centre

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1839]
**Describe the task**
I want to make sure it is crystal clear to folks that they shouldn't tinker with the tool given that prep has started in some fire centres. This URL is everywhere, I see a lot of risks with the lean permissions/persist approach we've taken. 

This brings up a question: how do people learn/explore the tool without mucking up prep?
- is there training aside from demos and sprint reviews?

Also, do we need a dev or staging environment - for us, and others?

https://mui.com/components/alert/
- banner
- dismiss-able with an X to close
- warning level 
- Warning. Any changes made to dates or fire starts will be reflected for all users in this Fire Centre and captured as an official decision. More nuanced controls and permissions are presently in development. 
- Behaviour: show every time someone visits the page, don't remember dismiss on repeat visits 
  
![Don't change things!.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/f0f48be9-d04c-47e2-a1e7-17680951774c)

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by conbrad** [comment]
Related to:
_> Also, do we need a dev or staging environment - for us, and others?_

From a technical perspective we could do this. Right now everything we merge to main is already in production. It follows some release pattern @Sybrand explained to me during onboarding -- I just forget the name.

Another way we could do it is have a staging environment like you mentioned, where we deploy to staging when we merge to main. We could then do releases to prod periodically. Users could do whatever in staging, etc.

We'd need some release process if we wanted to add a staging environment which would add time and effort to releases. I believe a major motivation for our current process is how fast it is.
