### ISSUE TITLE
Upgrade React 17 to 18

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#1845]
**Describe the task**
Upgrade react from v17 to v18 and test/fix any issues in our products.

**Acceptance Criteria**
- [ ] Upgrade react, react-dom and testing-library
- [ ] Upgrade typings fore react and react-dom
- [ ] All products work after the upgrade
- [ ] Also upgrade testing-library: https://github.com/bcgov/wps/pull/2287, https://github.com/bcgov/wps/pull/2654
- [ ] Fix issue with esri-leaflet not compiling with webpack (eject cra? migrate to vite? kill chaines?)

**Additional context**
- Associated renovate PRs: 
- https://github.com/bcgov/wps/pull/1844
- https://github.com/bcgov/wps/pull/1843
- https://github.com/bcgov/wps/pull/1842
- https://github.com/bcgov/wps/pull/2289
- https://github.com/bcgov/wps/pull/2290

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/1845?planning-poker) with Zenhub @andrea-williams @dgboss

**Comment by conbrad** [comment]
HFI Calculator keeps reloading components after this update, most likely due to the changes to StrictMode in React 18. Possibly fix: https://react.dev/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development

**Comment by conbrad** [comment]
Done
