### ISSUE TITLE
Add 2 new stations in Kamloops FC

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#1849]
**As a** *PE the forecaster* **I want** *West Kelowna and Station Bay 2 stations added to Kamloops FC in HFI Calc* **So That** *I can include those stations' weather data in my calculations for prep.*

**Additional Context**
- Andrea wrote a new Alembic migration script to add West Kelowna station in Penticton. Station appears locally and in dev envs in the database, but isn't showing up on the front end. Investigation revealed that `fetch_paged_response_generator()` in `wfwx_api.py` isn't including West Kelowna (1227) in `iterator` response. I've tried removing caching with `use_cache=False` and setting `cache_expiry_seconds=0`, and neither have worked. More troubleshooting required for this.
- after getting to this point, I decided it was going to be too much work to take this on on the fly - it deserves a ticket in the backlog. DH has also indicated that we should be limiting the number of times we make changes to the selected prep stations for HFI Calc, due to time constraints.
- see https://github.com/bcgov/wps/tree/task/add_west_kelowna for in-progress branch
- Remember to add mappings for fire starts

**Acceptance Criteria**
- [ ] Given I've navigated to Kamloops Fire Centre in HFI Calc, When I look at the Penticton planning area, Then I can see the West Kelowna - 1277 station second in the planning area list, with fuel type C7
- [ ] Given I've navigated to Kamloops Fire Centre in HFI Calc, When I look at the Vernon planning area, Then I can see the "Station Bay 2 - 1359" station third in the planning area list, with fuel type C5

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by Sybrand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1849?planning-poker) with ZenHub @conbrad @andrea-williams

**Comment by conbrad** [comment]
What are the net new station codes?

**Comment by conbrad** [comment]
1277 does not exist in WFWX API, 1359 does.

**Comment by conbrad** [comment]
Ok now 1277 is there...
