### ISSUE TITLE
User Research RWCO - interview and compile results

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#185]
**Describe the task**
user research with Regional Wildfire Coordination Officers (RWCO) regarding preparedness workflow, what decisions the make, data they are interested in and how they currently get that data

**Acceptance Criteria**
- [x] Conduct interview
- [x] Workflow documented
- [x] list of preparedness data sources used by RWCO's
- [x] list of preparedness decisions made by RWCO's

**Additional context**
- Linked with the ZWCO research
- People to Interview: Brad Litke, Dale Bojhara, Shelly Harnden, Derek Williams

**Comment by PrakritiM** [comment]
https://miro.com/app/board/o9J_ku7DTZQ=/

**Comment by PrakritiM** [comment]
Brad's overview of prep
https://miro.com/app/board/o9J_ksTQpME=/
