### ISSUE TITLE
Investigate Plumber as an option for running CFFDRS as an API service

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#1853]
**Describe the task**
Explore Plumber as a framework for creating a CFFDRS API service.

**Acceptance Criteria**
- [ ] Create 1-2 API endpoints that can be used to call cffdrs functions (supporting arrays inputs, not just singular scalar values)
- [ ] Measure the speed/performance of this (should be on the scale of milliseconds)
- [ ] Based on the above, decide whether it's worth our time pursuing a CFFDRS API service (and if it is, create another backlog ticket to do the remaining work)

**Additional context**
- Related to #1793
- See branch https://github.com/bcgov/wps/tree/task/cffdrs_api_spike/1793
- in branch above: was able to create a dummy endpoint with Plumber (just echoed whatever string was passed to it) - worked fine and was very simple & straightforward to implement. Ran into problems when trying to create an endpoint that called a `cffdrs` package function - kept getting "there is no package called 'cffdrs'" errors. But my local R env is broken and needs attention first
- for Plumber docs, see https://www.rplumber.io/, but see readme in linked branch for running Plumber locally - the instructions in Plumber's docs are outdated and don't work
- Is another ticket required for exploring other alternatives? (either alternative packages to Plumber, or alternative methods for running the `cffdrs` R package - `rpy2` is letting us down)

**Comment by Sybrand** [comment]
I think the output from the R spike @andrea-williams did invalidates this as approach.
