### ISSUE TITLE
HFI Calculator: UI Feedback - demonstrate when each planning area of a Fire Centre is 'ready' (fuel and fire starts adjusted by ZWCO)

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1859]
**As a** *RWCO or Plans stakeholder* **I want** *crystal clarity on the status of the HFI Calculator on prep morning* **So That** *in the context of fast-paced decision making I know if I'm looking at 'good' (ZWCO decisions) or 'bad' (default) data without having to manually communicate with ZWCOs and distract them from their task*

**Additional Context**
- toggle icon beside planning area name [FIGMA](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2022?node-id=1483%3A1602)
  - import ToggleOffOutlinedIcon from '@mui/icons-material/ToggleOffOutlined';
  - import ToggleOnOutlinedIcon from '@mui/icons-material/ToggleOnOutlined'; BC Validation Green #2E8540
- on hover: IDIR and date/timestamp when it was marked ready
- NOTE: not recommending a 'not ready' hover - if people don't use this feature (e.g. an RWCO who does the entire process themselves - this is a known use case, this could introduce issues)
- logic: if a user changes fire starts > marks as ready > then excludes a station, changes a fire start, or a fuel type > we switch toggle back to 'not ready'  
- R and ZWCO need permissions to make changes in a planning area 
- NOTE: bigger picture/future state (per user requests: allows a Z or R to hone in and focus on a given planning area, makes for a cleaner, clearer UI for everyone else to support information comprehension and fast decision making: '[edit planning area' pattern in Figma](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2022?node-id=1404%3A1319), or as close as we can get to it (WIP) see #1886

Ready for Review Toggle: Permissions 
![DECISION_ Ready for Review Toggle_ Editing.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/39e70cca-a23b-4635-832b-f50af15fbadb)

Ready for Review Toggle: No permissions 
![DECISION_ Ready for Review Toggle_ Read only.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/90f46697-9704-4167-9b36-21bdd0b6cbd9)

**Acceptance Criteria**
Given I an using the HFI Calc with Permissions to edit Planning Area (R/ZWCO):
- [ ] When I load the product on prep morning, all planning areas are in a 'not ready' toggle state:import ToggleOffOutlinedIcon from '@mui/icons-material/ToggleOffOutlined';
- [ ] When I am ready, I can manually change the status of a single planning area to 'ready' by clicking the toggle: import ToggleOnOutlinedIcon from '@mui/icons-material/ToggleOnOutlined'; BC Validation Green #2E8540
- [ ] When a planning area has been marked as ready, there is a hover state that says: Marked as ready by [IDIR] on [timestamp]
- [ ] When a user makes a change to that planning area after marking it ready (include/exclude, fuel, fire starts) the status is auto-reverted back to not ready
- [ ] When a planning area has been marked as ready or is auto-reverted, a success toast is generated

Given I an using the HFI Calc withOUT Permissions to edit Planning Area (read only or other role):
- [ ] When I visit the product, all toggles are visible but in a disabled state - I cannot click them and this is clear to me
- [ ] When I visit the product, the hover state on 'ready' planning areas is available to me

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**TMI** 
- This applies to any of the roles collaborating on prep mornings, e.g. Fire Weather Forecasters could be an interested party.
This is also a usability win - if someone gets interrupted in a prep morning task they can easily tell where they left off - in a spreadsheet there would be empty cells, in our product it will be default values. Usability heuristic: don't rely on memory/recall. 
- This process varies across Fire Centres, in some FCs the RWCO makes all the decisions (number of days, fuels, starts), in other FCs many ZWCOs will make decisions within their respective planning area using their on-the-ground context, and the RWCO will want to review the final result
- There may also be other Ops/Plans/Exec stakeholders who will want to peek at the HFI Calc on prep days and be clear on what is happening: are these default values, or has someone made decisions today? Having to wonder about this on a busy prep morning, especially if a busy season and pressure is on, would be frustrating 
- the request is for interface feedback at the planning area level to indicate the planning area is "ready" - this will likely involve a status label and a button/control

**Comment by Sybrand** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1859?planning-poker) with ZenHub @andrea-williams

**Comment by Sybrand** [comment]
@conbrad altering the json (hfi_request) is probably the way to go yes. The database currently doesn't have any understanding of planning areas - or much else. Wouldn't want to split the ready state between database and json.

So you'd be editing `HFIResultRequest` - adding another list maybe - `planning_area_ready : Dict[int, bool]` ? and a boolean like `fire_centre_read: bool`?

**Comment by conbrad** [comment]
Makes sense. Yes that's probably the best/easiest option. Thanks!
