### ISSUE TITLE
User Research PWCO preparations

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#186]
**Describe the task**
user research with Provincial Wildfire Coordination Officer regarding preparedness decisions and workflow, what data they are interested in and how they currently get that data

**Acceptance Criteria**
- [x] Contact PWCO
- [x] create questionnaire for interview
- [x] Book interview times

**Additional context**
- Linked to RWCO and APL user research
- People to interview: Brad Litke, Todd Nessman, Derek Williams (Brady to confirm)

**Comment by PrakritiM** [comment]
[https://app.zenhub.com/files/235861506/7ed0e086-a338-4c40-a503-4edebbe2c4ce/download](https://app.zenhub.com/files/235861506/7ed0e086-a338-4c40-a503-4edebbe2c4ce/download)


Interview questions.
