### ISSUE TITLE
Certificate renewal is failing

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1862]
**Describe the task**
There is something wrong with the certificate renewal process. Entrust is declining "www.psu.nrs.gov.bc.ca" and failing renewal. This may be a bug in the certbot project we're using (https://github.com/BCDevOps/certbot) or it could be an issue in our configuration.

"
Your Entrust Service administrator has declined your request for the following SSL Certificate :
     cn=www.psu.nrs.gov.bc.ca, o=Province of British Columbia, l=Victoria, st=British Columbia, c=CA
The following reason was given for declining the request:
Duplicate. The DNS name with www. is included automatically, and does not require a separate ACME request 
"

**Acceptance Criteria**
- [ ] psu.nrs.gov.bc.ca certificate is renewed

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by conbrad** [comment]
https://chat.developer.gov.bc.ca/channel/devops-how-to?msg=qW6xN3TGKz9kwMYSc

**Comment by conbrad** [comment]
"When it’s approved, it’ll get the new certificate data - it’ll store that info on PVC… and then patch your routes with the new certificates on the fly."

**Comment by conbrad** [comment]
Fixed via Jeremy's instructions in the above RC thread, and setting debug to true
