### ISSUE TITLE
SPIKE - How to interrogate access token from frontend to discover user roles

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#1866]
**Describe the task**
Research how to interrogate the access token within the frontend so as to determine a user's roles (and therefore access rights).

**Acceptance Criteria**
- [ ] Document (where - wiki? readme in code? somewhere easy to find for later reference) how to determine user rights from access token stored in browser

**Additional context**
- A user's role/s (and therefore rights) will be stored in the token received from Keycloak
- Based on Apr 7 discussion with Z's team, it's best that we strictly use Roles in a Client within Keycloak - these Client Roles will port over to the new Gold upgrade seamlessly
- Will need to know user role/s on FE to determine whether station selection should be disabled, whether fire starts & fuel type dropdowns should be disabled, etc.
- Keycloak docs: https://www.keycloak.org/docs/latest/server_admin/#con-client-roles_server_administration_guide

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1866?planning-poker) with ZenHub @conbrad @Sybrand

**Comment by conbrad** [comment]
See findings here: https://bcgov.sharepoint.com/:w:/t/01324/EV1OOXcFlkpDokbe3s2eH5oBy7C-fEmJBQj_hs5Dpwpcpw?e=dyISwL

**Comment by conbrad** [comment]
Working implementation that decodes and stores roles in redux store here: https://github.com/bcgov/wps/pull/1879
