### ISSUE TITLE
SPIKE - How to interrogate access token from backend to determine user rights

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#1867]
**Describe the task**
Research how our backend code can interrogate a user's access token (passed from the frontend) to verify that user has the correct roles in our Keycloak client in order to submit GET or POST requests.

**Acceptance Criteria**
- [ ] Document (either in our wiki or in a readme in our codebase) how to perform access token interrogation from the backend. Need to not only check for authentication, but also fine-grained user roles (e.g., rights to edit specific fields in HFI Calc)
- [ ] Document (perhaps using an example?) how to write & run backend unit tests to check for roles. Will need these unit tests to mock GET and POST requests to our API for retrieving/editing data in HFI Calc

**Additional context**
- A user will only be allowed to make a POST request if they have edit permissions in their assigned role/s. A user should be allowed to make a GET request as long as they're IDIR-authenticated.
- Based on Apr 7 discussion with Z's team, it's best that we strictly use Roles in a Client within Keycloak - these Client Roles will port over to the new Gold upgrade seamlessly
- Keycloak docs: https://www.keycloak.org/docs/latest/server_admin/#con-client-roles_server_administration_guide

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1867?planning-poker) with ZenHub @conbrad @Sybrand

**Comment by conbrad** [comment]
Simpler than expected, have an implementation for all endpoint permissions working: https://github.com/bcgov/wps/pull/1878

Just needs tests

**Comment by conbrad** [comment]
Document updated with details: https://bcgov.sharepoint.com/:w:/t/01324/EV1OOXcFlkpDokbe3s2eH5oBCROLaZTe4F2UWoy-ztbvQQ?e=tpw3LV
