### ISSUE TITLE
Add explicit permissions for editing fire starts

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#1869]
**As an** *RWCO/ZWCO/maybe forecaster* **I want** *To be able to edit the predicted fire starts for a planning area* **So That** *I can complete a prep sheet for my planning area/fire centre*.

**As an** *non-RWCO/ZWCO* **I want** *To be able to view a prep sheet, including predicted fire starts* **So That** *I can know how bad things are going to be in my area/fire centre, but I should not be able to edit the fire starts because I cannot be trusted*.

**Additional Context**
- Keycloak docs: https://www.keycloak.org/docs/latest/server_admin/#con-client-roles_server_administration_guide
- it's probably best to start on the backend of this ticket first
- See keycloak spike documentation: https://bcgov.sharepoint.com/:w:/t/01324/EV1OOXcFlkpDokbe3s2eH5oBCROLaZTe4F2UWoy-ztbvQQ?e=kaQ2tg

**Acceptance Criteria**
- [ ] Given I am logged in as some user with {fire starts edit} rights, When I navigate to a fire centre in HFI Calc, Then the fire starts values for each planning area appear as a dropdown, and I am able to change the selected fire starts value, and my change should persist for all future users.
- [ ] Given I am logged in as some user WITHOUT {fire starts edit} rights, When I navigate to a fire centre in HFI Calc, Then the fire starts values for each planning area appear as a non-editable text field (NOT a dropdown).
- [ ] Given I am logged in as some user WITHOUT {fire starts edit} rights, When I try to hack the system by modifying the network request to a POST request with a modified fire starts value for a planning area, Then the POST request fails and my attempted changes are not persisted.
- [ ] There exist unit tests covering all of the above AC.
- [ ] Permissions are set up for users as specified by Dana's spreadsheet

**Definition of Done**
- Ready to Demo in Sprint Review
- Does what I have made have appropriate test coverage?
- Documentation and/or scientific documentation exists and can be found
- Peer Reviewed by 2 people on the team
- Manual testing of all PRs in Dev and Prod
- Merged

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1869?planning-poker) with ZenHub @conbrad @Sybrand

**Comment by tessmgood** [comment]
Note: it is exclusively Plans in KFC who are changing fire starts. They export the PDF and share it with R/ZWCOs. If changes are needed, Plans makes the changes and re-distributes the PDF. (UXR session finding)
