### ISSUE TITLE
User Research Regional Planning Officer

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#187]
**Describe the task**
user research with Regional Wildfire Coordination Centre (RWCC) Planning Officer regarding preparedness decisions and workflow, HFI Calculation data and workflow, what data they are interested in and how they currently get that data, what products they currently produce.

**Acceptance Criteria**
- [ ] Conduct Interview
- [ ] Workflow documented
- [ ] HFI workflow documented
- [ ] list of data sources used by Planning Officer
- [ ] list of preparedness decisions made by Planning Officer

**Additional context**
- Linked to RWCO and APL user research
- People to interview: 3-4 contacts needed

**Comment by jowand** [comment]
This is an old ticket with a cross over between the conversation with Andrea and the RWCO/ZWCO user group.
