### ISSUE TITLE
User Research FBAN - interview and compile results

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#188]
**Describe the task**
user research with Fire Behaviour Analyst regarding preparedness products and workflow, what data they are interested in and how they currently get that data

**Acceptance Criteria**

- [x] Conduct Interview
- [x] Workflow documented
- [x] list of data sources used by FBAN
- [x] list of preparedness products made by FBAN

**Additional context**
- Linked to RWCO and APL user research
- People to interview: Dana Hicks, Marc Simpson...

**Comment by PrakritiM** [comment]
Contact:
Bradley Martin, Bryan Bowman(N-West)
Rory Colwell, Eric Kopetski (Cariboo)
Chris Spronken (Coastal)
Steve Levitt, Mike Morrow (South East)
Dana Hicks (Kamploops)

Interview with Min 4, max 8

**Comment by PrakritiM** [comment]
Interview documentation.
https://miro.com/app/board/o9J_ku7DTZQ=/

**Comment by jowand** [comment]
decision to go ahead with three FBANs. Jo will contact 4th (Chris Spronken)
