### ISSUE TITLE
HFI Calculator: Station Administration

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1886]
**As a** *member of the PSU* **I want** *add/remove/edit stations for fire centers* **So That** *any issues with stations that go down or are not reporting proper values can be addressed without having to go through software developers*

**Additional Context**
- enter text here
- proposal: edit planning area. Go into 'edit mode' for a single planning area at a time: the planning area is isolated, new controls drop-down, and away you go. Still working out some interaction challenges. WIP. We could restrict some actions (weather station mgmt) to RWCO only?
**SCREEN 1**
![Permissions B_ Edit is available.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/7c5328a8-d1b2-410b-9661-a8fdd5e7341e)

**SCREEN 2**
![Permissions C_ Actively editing.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/ad974b6f-58e9-4250-94dd-0493528fb883)
-[ check out this bulk-actions inspiration for enterprise tables](https://pencilandpaper.io/articles/ux-pattern-analysis-enterprise-data-tables/#:~:text=Multi%2Dselect%20%26%20bulk%20actions)

**Acceptance Criteria**
- [ ] Given I am an *TBD:*, When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by dthicks** [comment]
The RWCO permission is the way to go for edit permission for weather stations and fuel types

**Comment by Sybrand** [comment]
Replaced with focused stories.
