### ISSUE TITLE
Give us up to date Thessian polygons

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1888]
- Need list of stations in order to generate the polygons.

**Comment by Sybrand** [comment]
@nealmcloughlin looks very do-able with this python library: https://github.com/WZBSocialScienceCenter/geovoronoi - we could just write a ticket for it and have code we can use in our api from the getgo.

**Comment by nealmcloughlin** [comment]
I created an R script to generate Voronoi polygons from the GeoJSON weather station file that Sy provided from 2022-04-13. The script can be used to export the Voronoi polygons in both GeoJSON and ESRI Shapefile format. You can find my script and all of the inputs and outputs here: https://bcgov.sharepoint.com/:f:/t/01324/EsZgrBWX-DhPnScNLCuYB2gBLwzw1lMK21cE0VgYe1zCuQ?e=Ok5JNp

![weather_station_voronoi_polygons.png](https://images.zenhubusercontent.com/620bde3dcd6ceff7087c1f0d/e9129ca8-b422-4323-ba95-9eedecbeab4b)
