### ISSUE TITLE
HFI Calculator: Identify what account your logged in as

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1927]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- If users log in using Plans or R/ZWCO IDIRs (not personal IDIR) - we need to help them identify & switch accounts if their personal IDIR has persisted.
- There are realities of single sign we need to plan around — if someone logs into [the BCWS intranet] or anything in their browser using their personal IDIR (the typical behaviour per UX Research) then goes to use HFI Calculator, they will be automatically signed in with their personal IDIR and will only have 'read' access to HFI. What do they do next?
- ![Permissions clarity.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/32867e25-b3b4-4525-a122-e8aebf9749ea)
- https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2022?node-id=1535%3A1662

**Acceptance Criteria**
- [ ] Given I am a logged in user, When I am in the HFI Calculator, Then I can see what idir I am currently logged in as.
- [ ] Given I am a logged in user, When I am in NOT in the HFI Calculator, Then I cannot see what idir I am currently logged in as.

**Definition of Done**
- Ready to Demo in Sprint Review
- Does what I have made have appropriate test coverage?
- Documentation and/or scientific documentation exists and can be found
- Peer Reviewed by 2 people on the team
- Manual testing of all PRs in Dev and Prod
- Merged

**Comment by dthicks** [comment]
AARRRGG, this is never easy, can we set up the HFI Calculator to be only accessible after an idir log in no manner what mode the browser is in?? Looking for an easy fix :-)

**Comment by tessmgood** [comment]
@dthicks let's have a convo about it, probably easier. We're deviating from government-wide Single Sign On (SSO) logic - it will impact users beyond our product (one someone logs into HFI as Plans/RWCO, then open a new tab and try to do personal admin or access their sharepoint files - what do they do?). It's complicated - we believe Invasives have come up against this so are reaching out to them.

**Comment by Sybrand** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1927?planning-poker) with ZenHub @andrea-williams
