### ISSUE TITLE
Fire Weather Calculator Login

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#193]
**As a** *Wildfire Services Org* **I want** *to authenticate to get access to the fire weather calculator* **So That** *the data isn't misinterpreted by users who do not have adequate training of experience*

**Additional Context**
- Use Keycloak
- Chris Boreen contact re WF1 groups
- this does not include authentication on the API
- NO BCeID

**Acceptance Criteria**
- [x] Given I attempt to log in with proper IDIR credentials, When I login, Then I am given access to the FW calculator
- [x] Given I attempt to log in with incorrect IDIR credentials, When I login, Then I am denied access to the FW calculator
- [x] keycloak.js has to be pulled from https://sso.pathfinder.gov.bc.ca/auth/js/keycloak.js if at all possible

**Comment by Nkuruba** [comment]
React has an official keycloak library and it was used to configure IDIR login for fire weather calculator.

**Comment by Nkuruba** [comment]
Code added to pull keycloak.js from server.
