### ISSUE TITLE
HFI Calculator: KFC PDF - ordering of planning areas swapped for daily tables 

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1940]
**Describe the Bug**
The prep period table in PDF is the correct order: K2, K4, K5... but the dailies in PDF are displaying a different order: K5, K4, K2, K6, K7... The ordering issue is only in the PDF, not the interface. 

**Expected Behaviour**
The planning areas are ordered as requested, for Kamloops it's numerically by planning area/zone code starting with lowest number. This is consistent across the interface and and PDF. 

**Actual Behaviour**
The daily tables in the PDF are displaying a different order: K5, K4, K2, K6, K7

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to HFI Calc 
2. Click on Download PDF
3. Cross-reference the ordering between interface and PDF for prep table and daily table 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Sybrand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1940?planning-poker) with ZenHub @andrea-williams @conbrad

**Comment by andrea-williams** [comment]
@tessmgood  I'm also noticing that if a station is missing forecast data, that station is not showing up in the PDF at all - is this the desired behaviour, or should we have a mostly empty row for those stations to indicate that forecast data is missing?

**Comment by tessmgood** [comment]
@andrea-williams good catch. if a station is excluded, don't export it to PDF. If a station is included, export it. (is it used in decision making/does it inform the prep level, if yes - include). A station with no/missing forecast data should be erroring out, which requires exclude, which means it shouldn't be in the PDF.

**Comment by tessmgood** [comment]
@andrea-williams I just noticed more PDF gremlins - the daily tables are exporting a different number of weather stations by day - see the 25th vs 26/27th [https://app.zenhub.com/files/235861506/c7008ff6-83da-4d13-a6c9-6cfa5eae392d/download](https://app.zenhub.com/files/235861506/c7008ff6-83da-4d13-a6c9-6cfa5eae392d/download)

**Comment by andrea-williams** [comment]
Those poor gremlins are about to meet their mortal enemy... me.

**Comment by andrea-williams** [comment]
@tessmgood I know why it's exporting a diff # of stations on diff days, and it's related to my earlier question. Take for example French Bar in Lillooet (K7) - there's no forecast data available for it, but there is actual weather data available for the 25th. So you can see in the prep period table that after the 25th, French Bar's row ends bc there's no more data. That's why French Bar is only showing up in the daily table for the 25th, but not after. 

What's the desired behaviour in relation to PDF export if a station only has partial data available for the prep period?

**Comment by tessmgood** [comment]
gotcha! missed that. desired behaviour is same - partial data should cause an error: as soon as one index is missing: HFI, ROS, FIG and Prep cannot be calculated regardless of which one or how many are missing for that station. So station with partial data should be erroring out, exclude is required to unblock prep level, and therefore excluded. [Figma error modelling](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2022?node-id=863%3A559) if its helpful, but happy to answer Qs! Keep em coming
