### ISSUE TITLE
Research how teams are managing user groups in keycloak

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#195]
**Describe the task**
Research if other teams are automating user group management in keycloak with respect to assigning roles to users in keycloak using existing user role management systems. (e.g. if there some active directory group, in which users are currently being assigned roles, what would it take get those roles duplicated in keycloak)

**Acceptance Criteria**
- [x] determine if a solution already exists (check with 3 teams)
- [x] If there is no solution available explore Keycloak API to determine what is required technologically

**Additional context**
- is there Any way to use lists from outlook?
- check with Brady/WF1 team in how they are managing users

**Comment by Nkuruba** [comment]
Had a chat with @bradyholliday and came up with a classification of users.

Types of users based on use:

1. Heavy users
2. Casual users

Types of users based on role:

1. Forecasters
2. FBAN
3. Staff
4. Admin

**Comment by Sybrand** [comment]
Changed the description to make things a bit more clear.

**Comment by Nkuruba** [comment]
Found a way to import users and groups: https://github.com/BCDevOps/keycloak-admin/pull/3

Looking forward for more such solutions and discuss with team to find the best one to go ahead with.

**Comment by DerekRoberts** [comment]
Speaking with Clecio has make it pretty clear AD integration shouldn't be our first plan.  For more info we should prepare (at least problems to solve) and book a meeting.

**Comment by DerekRoberts** [comment]
I think a more seasoned dev should take over anything, if anything, left with this ticket.

**Comment by Sybrand** [comment]
I chatted some more to Clecio, and now have a clear idea on how we should go forward with user onboarding.

1) all wildfire apps should share the same realm (i.e. many teams and applications using the same realm)
2) teams should be focused on configuring the clients in their realm.
3) the existing wildfire onboarding process has to be adjusted to include onboarding users in keycloak for the wildfire realm
4) we need to establish some kind of "client administration authority" - this is a technical person, who has the rights to ensure that developers are given the appropriate rights to configure keycloak for their clients.
