### ISSUE TITLE
HFI Calculator: Permission status

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1976]
**As a** *Plans / RWCO / ZWCO / Forecaster* **I want** *a logout button in the HFI interface* **So That** *I can ensure I am logged in as the correct IDIR with permissions to do my work AND so I can log out of the 'general' Plans/R/ZWCO account and get back to my personal IDIR when I am done*

**Additional Context**
- [FIGMA](https://www.figma.com/file/FReMPNBDzxYeE8hlxRvsoB/HFI-Calc-(Prepski)-2022?node-id=1473%3A1502)
- Sample discussion/code for logging out of keycloak: https://github.com/bcgov/ocp-sso/issues/4
- New header elements:
  - icon: open/locked padlock
  - label: read only/editing 
  - IDIR that is logged in
![Screen Shot 2022-05-03 at 9.29.41 AM.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/36e78cbb-f405-4ec5-a418-ca49adc119f3)
![Screen Shot 2022-05-05 at 9.54.32 AM.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/3b2c1420-2458-455a-a07d-7d476afa3032)

**Acceptance Criteria**
Permissions:
- [ ] Given I am using HFI Calculator, When I have any editing permissions as a Forecaster, Plans, RWCO or ZWCO account, Then in the header I see: an open padlock icon: import LockOpenOutlinedIcon from '@mui/icons-material/LockOpenOutlined';
- [ ] Given I am using HFI Calculator, When I have any editing permissions as a Forecaster, Plans, RWCO or ZWCO, Then in the header I see: a label beside the open padlock icon: editing:
- [ ] Given I am using HFI Calculator, When I have any editing permissions as a Forecaster, Plans, RWCO or ZWCO, Then in the header I see: the IDIR I am logged in as beside the editing: label 
No Permissions:
- [ ] Given I am using HFI Calculator, When I log in with a personal IDIR or an account with no permissions, Then in the header I see: a closed padlock icon: import LockOutlinedIcon from '@mui/icons-material/LockOutlined';
- [ ] Given I am using HFI Calculator, When I log in with a personal IDIR or an account with no permissions, Then in the header I see: a label beside the closed padlock icon — read only:
- [ ] Given I am using HFI Calculator, When I log in with a personal IDIR or an account with no permissions, Then in the header I see: the IDIR I am logged in as beside the read only: label 
All cases: 

**Definition of Done**
- Ready to Demo in Sprint Review
- Does what I have made have appropriate test coverage?
-  Documentation and/or scientific documentation exists and can be found
- Peer Reviewed by 2 people on the team
- Manual testing of all PRs in Dev and Prod
- Merged

**Comment by conbrad** [comment]
Looks like this AC conflicts with the one above it:
" Given I am using HFI Calculator, When I have any editing permissions as a Forecaster, Plans, RWCO or ZWCO, Then in the header I see: the IDIR I am logged in as beside the editing: label"

**Comment by conbrad** [comment]
Looks like this AC conflicts with the one above it:
" Given I am using HFI Calculator, When I have any editing permissions as a Forecaster, Plans, RWCO or ZWCO, Then in the header I see: the IDIR I am logged in as beside the editing: label"

**Comment by conbrad** [comment]
AC and "As an X" story statement seem different. AC do not include cases for personal idir accounts **with** permissions so it seems incomplete.
I'm going to treat the "As an X" story description as the AC of this ticket until there is more clarity.

**Comment by conbrad** [comment]
Investigating further, it seems like the "As an X" story description is duplicated with the one in this ticket: https://app.zenhub.com/workspaces/wildfire-predictive-services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1956

**Comment by tessmgood** [comment]
@conbrad my understanding is personal IDIR's won't have permissions - I don't see any in the permissions spreadsheet. Which use cases/users are you aware of? re: incomplete AC. 
I'm not sure what you mean by orthogonal. 
We quickly split up all the permissions criteria from 1 to 3 tickets in planning ceremony, why you're seeing story overlaps. Happy to help clarify anything this morning.

**Comment by conbrad** [comment]
> _I'm not sure what you mean by orthogonal._
Ticket description at top writes about a logout button, AC talks about permissions
> _my understanding is personal IDIR's won't have permissions - I don't see any in the permissions spreadsheet. Which use cases/users are you aware of? re: incomplete AC._
Correct. I thought I read AC as only talking about personal IDIRs without permissions and not IDIRs in general.

Anyway, I wrote what I understand is the minimal set of AC for achieving the goals of this ticket in the PR: https://github.com/bcgov/wps/pull/1995
