### ISSUE TITLE
Split API&Web: Static content served from container

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1980]
**Describe the task**
Create a Dockerfile that builds static content, and container is configured to serve static content with basic templating.

**Acceptance Criteria**
- [x] Front end builds by itself in it's own Dockerfile.
- [x] Environment variables are used by template.
- [x] Easy to test on local machine.

**Additional context**
- The Dockerfile for this will be for a container that would very rarely be used on a developers computer. It will almost exclusively be used to serve static content in Openshift.
- This doesn't replace the "web" in docker-compose.yml ; That one is used for local development, and uses yarn run.
- Caddy can do this, but we can use whatever works. Have a look at what other projects are doing.
- **https://stackoverflow.developer.gov.bc.ca/questions/143**

**Comment by andrea-williams** [comment]
Resources:

- https://github.com/bcgov/s2i-caddy-nodejs - Platform Services repo to make a Caddy s2i builder image

**Comment by Sybrand** [comment]
@andrea-williams I worry that https://github.com/bcgov/s2i-caddy-nodejs hasn't had any commits in 2 years...

**Comment by conbrad** [comment]
Seems easy to run locally too: https://docs.konghq.com/gateway/2.8.x/install-and-run/macos/
