### ISSUE TITLE
HFI Calculator: On change - fuel type or fire starts - maintain my page position, don't scroll me to top

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#1983]
**As a** *Plans/R/ZWCO* **I want** *to maintain my position on the page as I make changes* **So That** *I can make multiple changes quickly and/or not lose my place or have to scroll up and down unnecessarily*

**Additional Context**
- technical input please

**Acceptance Criteria**
- [x] Given I am using HFI, When I change a fuel type, Then my position on the page is maintained as the data saves
- [x] Given I am using HFI, When I change a fire start, Then my position on the page is maintained as the data saves

**Definition of Done**
- Ready to Demo in Sprint Review
- Does what I have made have appropriate test coverage?
-  Documentation and/or scientific documentation exists and can be found
- Peer Reviewed by 2 people on the team
- Manual testing of all PRs in Dev and Prod
- Merged

**Comment by conbrad** [comment]
A simple solution: https://stackoverflow.com/a/59101106

**Comment by Sybrand** [comment]
Oh that's cool! (Much easier than only reloading the changed values....)
