### ISSUE TITLE
Fire Behaviour Calculator (old): User reported that changing wind speed does not change the FWIs aside from BUI  

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#2017]
**NOTE**
Sybrand has fixed the bug - it now just needs a unit test. (essentially just assert the value of the FWI in a unit test is as expected)

**Describe the Bug**
Fire Behaviour Calculator - adjusting wind speed isn't changing values aside from BUI. At a glance, all the values look a bit too same-same. 

Our SME (BB) is making a presentation tomorrow about Fire Weather Indicies and the numbers behind Prep values and how to think beyond prep and rationalize any changes that may be needed... and will be sharing/demo'ing this product.

**Expected Behaviour**
When I change the wind speed, the calculated FWIs adjust. 

**Actual Behaviour**
Changing the wind speed is only affecting BUI. 
![MicrosoftTeams-image (12).png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/58b366ac-73bc-4b57-991a-a33f8cb3a3ae)
![MicrosoftTeams-image (13).png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/297fbebe-7260-4820-9f0d-0e3f41cc7f1f)

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to Fire Behaviour Calculator. [Use this bookmark ](https://psu.nrs.gov.bc.ca/fire-behaviour-calculator?s=1339&f=c3&c=undefined&w=16.9,s=1339&f=c5&c=undefined&w=13.9,s=1339&f=c7&c=undefined&w=13.9,s=1339&f=s3&c=undefined&w=13.9)
2. Click on a wind speed field and adjust it up or down significantly
3. Note how the data in the table does/does not adjust

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Sybrand** [comment]
I cannot reproduce this bug :(
