### ISSUE TITLE
(UX Enhancement) View Map option needs to be more identifiable 

### ISSUE THREAD

**Issue by PrakritiM** [bcgov/wps#202]
**As a** *Consultant* **I want** * a view map button* **So That** *I immediately know where to access the map*

**Acceptance Criteria**
- [ ] "View Map" button with the map icon on the button instead of just the map icon

**Comment by andrea-williams** [comment]
![Screen Shot 2020-04-30 at 11.55.38 AM.png](https://images.zenhubusercontent.com/5e331ea54a0d32f8650c9a25/a7764095-b76c-40e2-aa9b-d277137a2291)
