### ISSUE TITLE
(UX Enhancement) Date range to select current year only if Fire Season has been observed

### ISSUE THREAD

**Issue by PrakritiM** [bcgov/wps#203]
**As a** *BCWS Staff Member and a consultant* **I want** *to be able to only select years that have entire fire season's worth of data * **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
- Need info on how API works
- Need to have defined fire season for each station
- Decision on roll over date

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by bradyholliday** [comment]
Need additional info in context before this can be completed
