### ISSUE TITLE
HFI Calculator: With permissions launched, remove warning banner 

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#2033]
**Describe the task**
Remove the warning banner: Any changes made to fuel types, fire starts or selected stations will be reflected for all users in this Fire Centre and captured as an official decision. More nuanced controls and permissions are presently in development.

**Acceptance Criteria**
- [ ] remove the banner

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by andrea-williams** [comment]
@tessmgood  what phrasing should be used for the update?
