### ISSUE TITLE
(UX Enhancement) Calculated Means should show before individual Wx info

### ISSUE THREAD

**Issue by PrakritiM** [bcgov/wps#204]
**As a** *Consultant* **I want** *to see the calculated means on the screen before the individual weather station info * **So That** *I don't need to scroll as much to see the information i will be using most*

**Additional Context**
- Prak wireframe

**Acceptance Criteria**
- [x] Given I am on the 90th percentile Calculator, When I press calculate, Then the results begin with the calculated means

**Comment by PrakritiM** [comment]
[Uploading... Main (result view)@2x.png ]

**Comment by andrea-williams** [comment]
![Screen Shot 2020-04-30 at 10.36.25 AM.png](https://images.zenhubusercontent.com/5e331ea54a0d32f8650c9a25/fd6c0f2a-e122-4301-9e47-7963b88b2c8b)
