### ISSUE TITLE
HFI Calculator: PDF refinement — ND (no data) use cases 

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#2040]
**As a** *FC admin* **I want** *to be able to access clear HFI / Prep Level decisions post-season* **So That** *I can easily investigate/verify decision making should there be a need to inquire or learn from prep, e.g. a lawsuit or negative outcome*

**Additional Context**
- presently, when data is missing there are gaps left in the PDF output. When you look at it side-by-side with HFI Calc in the moment you can likely figure out what is going on, but a non-HFI user reviewing the PDF record months later may perceive the output as broken or incomplete and won't know why - could this lower confidence in the output or create confusion/doubt that prep levels + cascading decisions were correct? Risk.
  - there _should_ be less gaps in data as the season picks up, but things happen, and we should consider the weather station network context this year 
- NA (Not Available) or **ND (No Data)** - which one is better? **Use ND**

**Acceptance Criteria**
- [ ] Given there are gaps in HFI data, When I export to PDF, Then ND (no data) displays in all relevant cells 

**Definition of Done**
- Ready to Demo in Sprint Review
- Does what I have made have appropriate test coverage?
-  Documentation and/or scientific documentation exists and can be found
- Peer Reviewed by 2 people on the team
- Manual testing of all PRs in Dev and Prod
- Merged

**Comment by andrea-williams** [comment]
Neal says ya.
