### ISSUE TITLE
SPIKE HFI Calculator: Errors when switching IDIRs (keycloak)

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#2044]
**Describe the task**
Is this a training item? (open a private browser/clear cache) 
Is there anything technical we can do? 
UX is getting contacted about this often as each FC adopts the tool - creating some support noise for us, and frustrating users

![Screen Shot 2022-05-16 at 8.51.42 AM.png](https://images.zenhubusercontent.com/60b527e413189cbf16c31d48/d96cb86e-4e46-43b0-a34e-e6f1271efffa) 

**Acceptance Criteria**
- [ ] SPIKE: what can we control? 
- [ ] Based on technical possibilities - engage with UX.

**Additional context**
- https://chat.developer.gov.bc.ca/channel/devops-how-to/thread/rZSzvibvugQmsZPeh?msg=rZSzvibvugQmsZPeh
- It may be possible to configure redirects in keycloak / or to establish the fact that the current token is expired and do somethin thing different in our code instead of letting keycloak take over.

**Comment by conbrad** [comment]
https://chat.developer.gov.bc.ca/channel/devops-how-to?msg=rZSzvibvugQmsZPeh

**Comment by conbrad** [comment]
See also: https://stackoverflow.developer.gov.bc.ca/questions/83
