### ISSUE TITLE
FBP Go: App controls - alternatives to sliders

### ISSUE THREAD

**Issue by tessmgood** [bcgov/wps#2045]
**Describe the task**
Users are struggling with the sliders — this is the most consistent feedback. 
Some values need to be more precise than others, but regardless it is frustrating to drag a slider and not have it end up where you wanted it (friction, slows you down, distracting, impacts perception of the app). 

[Flutter — Material Components](https://docs.flutter.dev/development/ui/widgets/material#Input%20and%20selections)

Quotes 
_For myself I found that while using the sliders on the phone it was difficult to input a specific number because as soon as I released the bar it would jump to another number. Maybe I am too clumsy, but I was getting a little frustrated, despite using it in a classroom setting. I’m not saying that the manual input is the solution, however I would like to see some changes to make it easier to set the numbers. Possibly dials similar to the alarm setting on the iPhone?_

**Acceptance Criteria**
- [ ] read user feedback (emails, testflight)
- [ ] design ideation - optimal mobile patterns
- [ ] document suggestion(s) in Figma, share with SS

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by Sybrand** [comment]
Let's hope it's closed! There's always the option of going back to input boxes instead of sliders.

**Comment by tessmgood** [comment]
@Sybrand I'll definitely monitor this closely as we test it with crew this spring/summer. I feel good about the iteration you developed, thanks again for making it happen :)
