### ISSUE TITLE
(Design Enhancement) Wx listed side by side 

### ISSUE THREAD

**Issue by PrakritiM** [bcgov/wps#207]
**As a** *Consultant* **I want** *up to 3 weather stations info shown side by side* **So That** *I am able to compare the results of each station more easily and on the same screen*

**Acceptance Criteria**
- [ ] Given I have used 3 weather stations to make a calculation, When i look at the results, Then I can see all 3 of the stations I used side by side

**Comment by bradyholliday** [comment]
@PrakritiM can you please provide more context?

**Comment by PrakritiM** [comment]
![Main (result view)@2x.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/b3ca7255-044b-41eb-b70c-714db5f5410c)


Users wish to have a comparative view as shown in the wireframe attached above.
