### ISSUE TITLE
Remove matomo

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#2071]
**Describe the task**
Matomo (analytics engine) is not used by anyone. It's using up resources. Remove matomo entirely.

**Acceptance Criteria**
- [x] Remove all references to matomo in code base and openshift templates.
- [x] Clean up all matomo resources in openshift (images, cronjobs, deployment configs, pods, everything!)

**Additional context**
- We're maxing out our CPU allocation in DEV. No-one is using matomo, so let's just remove it and free up some resources.

**Comment by conbrad** [comment]
Deleted `e1e498-dev/deploymentconfigs/matomo-db`, `e1e498-dev/persistentvolumeclaims/matomo-db`
