### ISSUE TITLE
oc_promote.sh - don't fail on prod tag not being present

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#208]
**Describe the task**
In the edge case that there is no production tag, oc_promote.sh will currently fail. 

Example: if (as happened on April 4 2020), the image for production disappears, a quick attempt to re-deploy will fail, due to the failure to delete an image that doesn't exist.

NOTE: An argument can be made that the deployment SHOULD fail, as this is an exceptional circumstance that must be highlighted. If that case this ticket should be re-written accordingly, and comments to that effect should be put in code/documentation at the appropriate place(s).

**Acceptance Criteria**
- [ ] Failure to delete image tag for production, does not cause script to fail.

**Additional context**
- There are of course manual workarounds for this, but ideally one should be able to use the normal deployment process without having to resort to manual workarounds.

**Comment by DerekRoberts** [comment]
@Sybrand This is covered by the script update related to missing imagestreams for wps-api.  Closing.

https://github.com/bcgov/wps/issues/216
