### ISSUE TITLE
FBP Go: Configure Stores -  MVP

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#2083]
**Describe the task**
Prepare for release (various screenshots, text etc. etc.)

**Acceptance Criteria**
- [ ] Configure google play store
- [ ] Configure apple store

**Additional context**
- Add any other context about the task here.

**Comment by NicolasLivanos** [comment]
iOS: 
https://apps.apple.com/app/fbp-go/id1605675034

Android: 
https://play.google.com/store/apps/details?id=ca.bc.gov.FBPGo
