### ISSUE TITLE
Instance of Fider in test

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#209]
**Describe the task**
Deploy an instance of Fider in our test environment.

**Acceptance Criteria**
- [ ] Instance of fider running in test environment.

**Additional context**
- We currently only have a production Fider instance, making it difficult to experiment with styling, backup & restore etc. without affecting users.
- There is no need for an instance in dev at this time.
- Fider depends on a posgresql database, for the purposes of this ticket, "an instance of Fider" includes that postgresql instance alongside it.

**Comment by Kyubinhan** [comment]
We don't use Fider anymore. Closing the ticket
