### ISSUE TITLE
FBP Go: For the web

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#2096]
**As a** *Fire Behaviour Specialist* **I want** *use a web version of FBP* **So That** *I have an alternative to installing the app through an app store*

**Additional Context**
- Some users may be blocked from installing the app. (e.g. some governments manage what apps users are allowed to install on their phones.)
- Some users may wish to use FBP Go on their desktop.
- Having a web version is very useful for demo & testing purposes.

**Acceptance Criteria**
- [ ] PR based deployment to dev endpoint of web build. e.g. fbp-go-pr-23.apps.silver.devops.gov.bc.ca (<- technically a task)
- [ ] When PR is merged to main, FBP Go is published to some endpoint, e.g. psu.gov.bc.ca/fbp-go/

**Definition of Done**
- Ready to Demo in Sprint Review
- Does what I have made have appropriate test coverage?
- Documentation and/or scientific documentation exists and can be found
- Peer Reviewed by 2 people on the team
- Manual testing of all PRs in Dev and Prod
- Merged

**Comment by NicolasLivanos** [comment]
https://sybrand.github.io/
