### ISSUE TITLE
Add Pine Creek Station to NWFC, Bulkley Zone

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2105]
**Describe the task**
SI from NWFC requested this station addition

**Acceptance Criteria**
- [ ] Pine Creek Station exists in Bulkley Zone with default fuel type C5

**Additional context**
- Email with subject title: Adding Pine Creek to HFI Calculator, June 15, 2022

**Comment by nealmcloughlin** [comment]
Would like to handle this request by providing the PSU group account with permission to add a station and having someone from PSU perform the task of adding Pine Creek station.
