### ISSUE TITLE
Share S3 connection info with DevH

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#2152]
**Describe the task**
DevH & GE need connection info to access our S3 object store to know where to push HFI geotiffs generated from SFMS.

**Acceptance Criteria**
- [ ] Create a separate bucket that's strictly for HFI geotiffs - maybe isn't necessary?
- [ ] Create a separate user/service account that GE's GIS job will use to write geotiff files to our object store
- [ ] First talk to the object store peeople to establish whether a separate bucket is necesary to restrict access. The GIS job needs to be able to write to our store without viewing any other data in the store, and without overwriting other data already in the store.
- [ ] Share the connection & account user with DevH

**Additional context**
- Contact for object store stuff is HH

**Comment by andrea-williams** [comment]
Email sent to HH July 12 afternoon.

**Comment by andrea-williams** [comment]
Update: rec'd response from HH July 18. She suspects they'll be able to create a new object storage user ID for GE & co., and will then apply an S3 bucket policy on our existing bucket so that the new user ID has write-only access. IITD Optimize team is investigating this further, will be getting back in touch with me later.

**Comment by andrea-williams** [comment]
Reply received from HH:

I began testing this by using two of my team’s buckets, nrs-iit (owner: nrs-iit-user) and hhdevtest (owner: nr-heatherhay-dev). A bucket policy was written for nrs-iit that gives the userID nr-heatherhay-dev write access to it but denies the ability to delete any objects or their versions. Preventing object overwriting is trickier because allowing "PutObject" and denying "PutOverwriteObject" to a user does not work, the bucket policy throws an error (in essence, they cancel each other out due to the way writes work in object storage). Research says the best way around this is to have [versioning](https://apps.nrs.gov.bc.ca/int/confluence/display/OPTIMIZE/Object+Storage+Versioning) applied to the bucket, which your bucket does as our team sets this up as a SoP. The number of versions kept and for how long can be adjusted to suit your needs, currently it keeps 1 version and non-current versions are deleted after 60 days. If there's a concern, users could "peek" at the file using S3 Browser or CyberDuck and [roll back the version](https://docs.aws.amazon.com/AmazonS3/latest/userguide/RestoringPreviousVersions.html) (programmatically or through one of the apps noted) if they wanted to.
 
I hope this helps, please let me know if it’s something you’d like to apply to your bucket or if you’d like us to investigate further.

**Comment by Sybrand** [comment]
@andrea-williams I'm going to say we should go ahead and close this. Tell them we've worked around the issue and no longer need to give an external party access to our bucket. At least for now!

**Comment by andrea-williams** [comment]
Closing. Not expecting any further action needed.
