### ISSUE TITLE
WPS-API Image Missing?

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/wps#216]
**Describe the Bug**
wps-api redeployed on the weekend, but failed.  The imagestream is missing.  Figure out why and prevent a repeat.

**Expected Behaviour**
Containers should be able to recover after interruption.  This was not the case.

**Actual Behaviour**
Image missing, failed on deployment recreation.

**Comment by Sybrand** [comment]
@DerekRoberts I've connected your promotion PR to this task.

Remember that we need a similar PR for api - that's the one that went missing after all...

**Comment by DerekRoberts** [comment]
Resolves #208

**Comment by DerekRoberts** [comment]
> @DerekRoberts I've connected your promotion PR to this task.
> 
> Remember that we need a similar PR for api - that's the one that went missing after all...

@Sybrand https://github.com/bcgov/wps-api/pull/35
