### ISSUE TITLE
ASA: Default Content to use and display

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2166]
**As a** *qualified or trainee FBAN * **I want** *to be able to navigate forecasts/actuals * **So That** *I can use the appropriate information*

**Additional Context**
- Navigating forecasts/actuals (includes all Advisories, Calculated HFIs, etc.) is performed through frontend interface
- All layers are showing
- Default behaviour is documented & known so that users understand what they're looking at
- "Forecast" in AC means any data relating to forecasts. E.g., the HFI map based on today's weather forecast is "today's forecast"

**Acceptance Criteria**
- [x] Given I look at AutoNeal at 13:00 or later, Then I see tomorrow's forecast
- [x] Given I look at AutoNeal before 13:00, Then I see today's forecast
- [ ] ~~Given I look at AutoNeal at any time, Then I can choose from the available forecasts what to display~~ this is captured in #2218 
- [x] Given I look at AutoNeal at any time, Then I can choose to see yesterday's actuals
- [x] Given I look at AutoNeal at any time, Then I know if I'm looking at a forecast or an actual
- [x] Given I look at AutoNeal at any time, Then I know the date and time a forecast/actual was generated
- [x] Given I look at AutoNeal at any time, Then I know which date an actual/forecast is for.
- [x] For Forecasts should indicate the issue date AND the date the forecast represents
- [x] Actuals should indicate the issue date - which by default is the date it represents

**Definition of Done**
- Ready to Demo in Sprint Review
- Does what I have made have appropriate test coverage?
-  Documentation and/or scientific documentation exists and can be found
- Peer Reviewed by 2 people on the team
- Manual testing of all PRs in Dev and Prod
- Merged

**Comment by conbrad** [comment]
"This forecast is for <date> issued on <date@13:00>"

**Comment by NicolasLivanos** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/2166?planning-poker) with ZenHub @conbrad

**Comment by NicolasLivanos** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/2166?planning-poker) with ZenHub @andrea-williams

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/2166?planning-poker) with ZenHub @Sybrand @conbrad
