### ISSUE TITLE
HFI Calc: Users can add the same station within a planning area more than once

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#2180]
**Describe the Bug**
On July 27, 2 different user accounts were able to add the same station (code 166) to the same planning area twice, where neither of them had the `is_deleted` flag. This caused problems on the frontend because the station was only listed once, but that meant the logic for calculating the planning area's Prep Level etc. broke

**Expected Behaviour**
There should exist logic that prevents a weather station from being added to the same planning area multiple times (checking to make sure that any weather station within a planning area only appears with `is_deleted = F` once).

**Actual Behaviour**

** Steps To Reproduce**
Steps to reproduce the behaviour:

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by NicolasLivanos** [comment]
brett.soderholm@gov.bc.ca
