### ISSUE TITLE
FireBAT: Same windspeed produces different critical hours, if input manually [ 1 DAY TIMEBOX ] Backend

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2189]
**Describe the Bug**
WFWX and our API (via CFFDRS) diverge in how we calculate indices, but we treat the the wind speed input to calculated indices interchangeably. 

If we supply the same wind speed input as the read wind speed from WFWX, we get different indices (FFMC, ISI, FWI)

**Expected Behaviour**
If user has not specified wind speed, use the values retrieved from WFWX
If user has specified wind speed and it is the same as WFWX wind speed, re-calculate FFMC & ISI with modified value of wind speed
If user has specified wind speed and it is different from WFWX, re-calculate FFMC & ISI with modified value of wind speed

**Actual Behaviour**
- If user has not specified wind speed, use the values retrieved from WFWX
- If user has specified wind speed, re-calculate FFMC & ISI with modified value of wind speed

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://localhost:3000/fire-behaviour-calculator?s=2230&f=c3&c=NaN&w=NaN
2. Select August 1, 2022, windspeed is 11.84, critical hours are 16:00 - 18:00	11:00 - 20:00
3. Change wind speed to 1, then change it back manually to 11.84 
4. Critical hours are 10:00 - 21:00	11:00 - 20:00

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by conbrad** [comment]
Potentially a discrepancy on which FFMC method is used between our API and WFWX (diurnal vs hourly calculation).

**Comment by NicolasLivanos** [comment]
HI again @conbrad - spoke w/ Eric about this bug.

He also reported similar behavior when adjusting precipitation.... the indices change as per this recording below: 

https://bcgov-my.sharepoint.com/:v:/g/personal/nicolas_livanos_gov_bc_ca/Ea1UxxSUx9tFsOqN0xe65-kBCMTV7YrEEVcGHYHXaEszkg?e=xMQi0l

Bringing this to your attention when spiking this.

Thanks!

**Comment by NicolasLivanos** [comment]
HI again @conbrad - spoke w/ Eric about this bug.

He also reported similar behavior when adjusting precipitation.... the indices change as per this recording below: 

https://bcgov-my.sharepoint.com/:v:/g/personal/nicolas_livanos_gov_bc_ca/Ea1UxxSUx9tFsOqN0xe65-kBCMTV7YrEEVcGHYHXaEszkg?e=xMQi0l

Bringing this to your attention when spiking this.

Thanks!

**Comment by NicolasLivanos** [comment]
Eric's bug recording: https://bcgov.sharepoint.com/:v:/t/01324/Eb5sYy76k1FGpsrRbMHoO0gBMWZ43CkgfigRXGsnXdrFPQ?e=k10eCK

**Comment by conbrad** [comment]
WFWX uses the Van Wagner method for computing critical hours.

**Comment by dgboss** [comment]
****NOTE****
To whoever picks up this ticket. I think the issue might be state management related on the front-end. I took a cursory look and it looks like the data coming back from our API is correct, but the UI is displaying data from the previous request.
