### ISSUE TITLE
ASA: Historical Advisory Records: Step back in time

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2191]
**As a** *Product Owner* **I want** *to demonstrate/prototype recommendations for automated FBAs* **So That** *help stakeholders provide meaningful input/facilitate change around the FBA process*

NOTE: This ticket has to be re-thought. We need to define why exactly we're going back in time. What risk are we mitigating or feature are we providing?

Archival and retrieval of past data. e.g.: if there's a request for data in a previous fire season - we'd need to make the data available.

**Additional Context**
- 2 to 3 weeks of data grids (advisories) to step back in time
- Not intended to be functional for production -- goal is to have a prototype
- What does archiving even mean?
- Even if we archive old inputs, our code is changing, so outputs will differ.
- What is our retention period.
- We could have a log of advisories (e.g. if there's some textual output - we can store that log)
- Capturing some kind of screenshot / or a database with numbers and tables.
- Move around various multiple dates
- Legal Requirements

**Acceptance Criteria**
- [ ] Given I visit the FBA tool, Then I can retrieve 3 weeks worth data from this fire season (2022) at any time

**Definition of Done**
- Ready to Demo in Sprint Review
- Does what I have made have appropriate test coverage?
-  Documentation and/or scientific documentation exists and can be found
- Peer Reviewed by 2 people on the team
- Manual testing of all PRs in Dev and Prod
- Merged

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/2191?planning-poker) with Zenhub @andrea-williams @conbrad @Sybrand
