### ISSUE TITLE
AutoNeal Spike: Investigate a queuing system

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2199]
**Describe the task**
Get a prototype working for a queuing system to queue processing of tiffs.

**Acceptance Criteria**
- [ ] A queue runs in Openshift that processes dummy messages

**Additional context**
- https://docs.nats.io/nats-concepts/jetstream
- SO recommendation: https://stackoverflow.developer.gov.bc.ca/a/493/16

**Comment by andrea-williams** [comment]
Updated "FBA Tech Design Doc" on our Sharepoint with notes on my research into queueing options (see Queueing section of doc).
