### ISSUE TITLE
SSO Migration: Deploy Gold cluster configuration in prod

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2205]
**Describe the task**
Adjust keycloak configuration handle both silver realm and gold team keycloak servers. 
After verifying gold works, remove configuration to silver.

**Acceptance Criteria**
- [x] Keycloak login continues to work in prod
- [x] Removed any/all references to previous Keycloak configuration/code/tests etc.

**Additional context**
- We've migrated to Gold, we just need to make sure there's no garbage left over.
- Ideally our realm in silver is entirely decommissioned.

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/2205?planning-poker) with ZenHub @andrea-williams @conbrad @Sybrand

**Comment by andrea-williams** [comment]
I believe I've deleted all references to Keycloak in Silver from our ConfigMaps in DEV and PROD Openshift namespaces. No Silver Keycloak variables exist in Secrets.
