### ISSUE TITLE
ASA: Fuel layer data accessible at zonal scale

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2208]
**As a** *fire fighter receiving a fire behaviour advisory* **I want** *I want to know what fuel types are of concern today, and where they are within my fire centre* **So That** *I modify my work safe practices if sent to one of these locations.*

**Additional Context**
- Example of data table to show on the front end is in sheet 1 here: https://bcgov.sharepoint.com/:x:/t/01324/EUBU6D7LipVBh9I0vPUtmboBAB7GjI21K6whSItN-z5fDQ?e=5uZyU1
- No need to consider sub zones at this point in time, we are starting of using Zonal polygon, but should be in a position to switch out to sub zone polygons if needed.
- CSV mapping fuel type IDs in SFMS fuel type layer to fuel codes: https://bcgov.sharepoint.com/:x:/t/01324/EQVixiTNReFDh_Jhz8NTQVIBcSER2IT-5Ya15MX5kai6QQ?e=ndjmb3 

**Acceptance Criteria**
- [ ] I can see at the fire centre scale, which fire zones are under advisory.
- [ ] I can see at a fire zone scale which fuel types are associated with the advisory. (e.g. C2 is of concern in Nadina Zone.)
- [ ] I can see for each zone that is under advisory/warning, in tabular format what fuel types are driving behaviour. (e.g. For Nadina Zone, 50% of C2 and 80% of C3.)
- [ ] Grids accessible for the analysis, start with fuel layer
- [ ] Use HFI threshold areas as a mask (polygon/raster/etc), extract out underlying values
- [ ] -> let's not click? Clicking on an advisory shows raw data in a popup table of fuel types are contributing based on their pixel counts:

e.g.

|  Fuel Type |  4K to 10K |  10K+ |
|---|---|---|
| 1  | 20  | 15  | 
| 2  | 73 | 31 | 
| 3  |  61 | 25  |
| 4 | 2 | 0 |

Fuel type are integer values from fuel type grid
4K to 10K is cell counts of HFI pixels in the range
10K+ cell counts of HFI pixels in that range

LATER:
- [ ] I can see on the map that a zone is under advisory, because it's coloured orange.
- [ ] I can see on the map that a zone is under warning, because it's coloured red.

**Definition of Done**
- Ready to Demo in Sprint Review
- Does what I have made have appropriate test coverage?
-  Documentation and/or scientific documentation exists and can be found
- Peer Reviewed by 2 people on the team
- Manual testing of all PRs in Dev and Prod
- Merged

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/2208?planning-poker) with Zenhub @conbrad @andrea-williams @dgboss
