### ISSUE TITLE
ASA: Selecting a Forecast OR Actual Date - UX Task

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#2218]
**As a** *qualified or trainee FBAN * **I want** *to be able to navigate forecasts/actuals * **So That** *I can use the appropriate information*

**Additional Context**
- Navigating forecasts/actuals is performed through frontend interface
- When a new issue date and forecast day are selected, the HFI input + advisory information displayed match the date selected
- For any given day, there can be multiple forecasts, in addition to an actual

**Acceptance Criteria**
- [ ] There should be a selector to select between actual & forecasts
- [ ] There should be a selector to select between forecasts, when specifying the issue date and the date it represents
- [ ] if 2 forecasts are issued on the same day, use the most current forecast

**Definition of Done**
- Ready to Demo in Sprint Review
- Does what I have made have appropriate test coverage?
-  Documentation and/or scientific documentation exists and can be found
- Peer Reviewed by 2 people on the team
- Manual testing of all PRs in Dev and Prod
- Merged

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/2218?planning-poker) with ZenHub @conbrad @andrea-williams @Sybrand

**Comment by conbrad** [comment]
https://wps-pr-2411.apps.silver.devops.gov.bc.ca/auto-spatial-advisory
