### ISSUE TITLE
Pipeline - OWASP and Other Security Scans

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/wps#226]
**Describe the task**
Add OWASP or a similar security assessment tool to the pipeline.

**Acceptance Criteria**
- [x] Assess tools
- [x] Run tools
- [ ] Incorporate tools into the pipline
- [x] Verify output is accessible in a practical way

**Comment by DerekRoberts** [comment]
Critical, but not urgent.

**Comment by Sybrand** [comment]
Have requested our project be added to sonarcloud:
https://github.com/BCDevOps/devops-requests/issues/365
