### ISSUE TITLE
FBP Go: Update iOS Distribution Certificate

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#2317]
**Describe the task**
FBP Go's distribution certificate for the Apple Store expires October 7. We will need to update the certificate before we can push any new changes to FBP Go (in the Apple Store). 

**Acceptance Criteria**
- [x] New distribution certificate created for Apple Store
    - [x] investigation spike: is there a way to automate the process of updating this cert?

**Additional context**
- See email fwd'ed from PO to devs Oct 5.

**Comment by conbrad** [comment]
Added spike ticket for fastlane automation: https://app.zenhub.com/workspaces/wildfire-predictive-services-5e321393e038fba5bbe203b8/issues/bcgov/wps/2377
Discussing with mobile app team if it's something they can do on their end or ours

**Comment by conbrad** [comment]
New build approved by Apple, currently waiting on reviewer for green light
