### ISSUE TITLE
ASA: Calculate and store area of High HFI per zone

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2318]
**Describe the task**
We calculate and store the area of high HFI per zone

**Acceptance Criteria**
- [ ] High HFI is calculated and stored per zone in the API database
- [ ] Units stored in m^2

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/2318?planning-poker) with Zenhub @andrea-williams @conbrad
