### ISSUE TITLE
Update Team "Room" board

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#2335]
**Describe the task**
Our Miro board for our Team "room" hasn't been updated for a while, but could be used as a introductory tool for onboarding new team members upcoming in the next weeks. 

**Acceptance Criteria**
- [x] staff bios
- [x] links to team-relevant docs (how to code review, governance, etc.)

**Additional context**
- [le board](https://miro.com/app/board/o9J_kuqXDEQ=/)

**Comment by NicolasLivanos** [comment]
Discussed w/ PO; he will task this out to a BCWS IT support team for completion. They will let us know inbox + pass
