### ISSUE TITLE
Postgres DB: Migrate to CrunchyDB operator

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2340]
**Describe the task**
We currently use a patroni template for deploying our database, but we could use the crunchyDB operator for easier deployment, as well as easier and faster tooling around restoring backups.

**Acceptance Criteria**
- [ ] #3305
- [ ] Point API/Backend services to CrunchyDB cluster
- [ ] Delete old patroni cluster
- [ ] Configure PVC to use NetApp-block-storage

**Additional context**
- See #1910

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/2340?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss
