### ISSUE TITLE
ASA: Resource Quota - Platform Services Review

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#2352]
**Describe the task**
Verify maximum storage space in OpenShift

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by conbrad** [comment]
Max storage quota is 512Gb: https://beta-docs.developer.gov.bc.ca/openshift-project-resource-quotas/#storage-quotas

See thread with follow up: https://chat.developer.gov.bc.ca/channel/devops-how-to?msg=icLDGqy6H9JSmjugL

**Comment by NicolasLivanos** [comment]
And where do we currently stand in terms of cpu, mem, storage, please?


Nicolas Livanos
Scrum Master
Natural Resource Information & Digital Services
Ministry of Lands, Water and Resource Stewardship

All my relations to the Kwakwa̱ka̱ʼwakw Peoples for their hospitality and tolerance on their Traditional, Ancestral, and Unceded Territories (Vancouver Island North) - Gilakas’la!

**Comment by conbrad** [comment]
You can check in realtime here: https://app.sysdigcloud.com/#/dashboards/324996?last=3600&maximizedPanelId=1

If it doesn't load I can add your account for access.

**Comment by NicolasLivanos** [comment]
Yes, pls add me!



Nicolas Livanos
Scrum Master
Natural Resource Information & Digital Services
Ministry of Lands, Water and Resource Stewardship

All my relations to the Kwakwa̱ka̱ʼwakw Peoples for their hospitality and tolerance on their Traditional, Ancestral, and Unceded Territories (Vancouver Island North) - Gilakas’la!

**Comment by conbrad** [comment]
This dashboard is better: https://app.sysdigcloud.com/#/dashboards/324979
