### ISSUE TITLE
FBP Go: Migrate web app to Openshift

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#2363]
**Describe the task**
Migrate web app away from SS's Github page to our standard Openshift platform.

**Acceptance Criteria**
- [x] Manual Flutter Deployment
- [x] FBP Go is available as a web app, with url that looks something like `psu.nrs.gov.bc.ca/fbp-go`
- [x] Update link on our PSU landing page
- [ ] (Optionally) notify SS that he can pull down his website if he wants

**Additional context**
- https://sybrand.github.io/#/
- Future Automated Pipeline TBD

**Comment by brettedw** [comment]
Use `haproxy.router.openshift.io/rewrite-target`

https://docs.openshift.com/container-platform/4.13/networking/routes/route-configuration.html#nw-route-specific-annotations_route-configuration
