### ISSUE TITLE
ASA: Prod tileserver deployed

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2367]
**Describe the task**
The dev tileserver is the only tileserver running in the cluster, and was manually deployed. We need it to be deployed for dev and prod through Infra as code.

**Acceptance Criteria**
- [ ] Tileserver is deployed in dev and prod
- [ ] Tileserver is deployed as part of deployment pipeline
- [x] PVC uses netapp-block-storage class
- [x] Have it hooked up to alembic migrations

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by nealmcloughlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/2367?planning-poker) with Zenhub @andrea-williams @conbrad
