### ISSUE TITLE
ASA: Manual process for HFI data script

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2380]
**Describe the task**
Write a script to manually impersonate SMFS for producing archived geospatial data in the production environment (or any environment).

**Acceptance Criteria**
- [x] Must pretend to issue forecasts from previous dates and times (morning versus afternoon).
- [x] Must pretend to issue actuals from previous dates.
- [x] Should be able to iterate over a range of dates and times for when SFMS would have produced both forecasts and actuals.
- [x] Tests are written for this script.

**Additional context**
- The script should only send messages and not upload data to the S3 store because it's already stored there.
- Actuals are straightforward as they are issued once per day after noon weather is recorded and FWI is calucualted.
- Forecasts are tricky as they extend 3 days into the future and are issued in the morning and updated in the afternoon. For any given forecast date there could be up to six issue dates and times.
- Forecasts are also tricky because they are dependent on how far into the future a weather forecaster pushes FWI indices. A forecast can extend from 1 to 3 days into the future, but is not necessarily consistent from day to day.

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/2380?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss
