### ISSUE TITLE
Workstation Upgrade: get errr'body set up

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#2395]
**Describe the task**
Have local development environments set up on all the developers' new workstations.

**Acceptance Criteria**
- [x] all required software packages installed
- [x] all devs can run all our apps natively on their local machines without any problems
- [ ] all devs can run all our apps containerized on their local machines without any problems
- [ ] any installation/setup problems encountered are documented in the readmes in our repo for future reference

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by NicolasLivanos** [comment]
Docker license pending for JAN '23
