### ISSUE TITLE
select weather data from API

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#240]
As a Fire weather forecaster I want a space to select weather stations So That I can see the actual data from the API

Additional Context

include all actual daily weather data from API (even the technical bits)

Wx Zone, Station Status, Temp, Relative Humidity, Wind Direction. Wind Speed. Precipitation. Grass Cure, FFMC, DMC, DC, ISI, BUI, FWI, Danger Class. Station Name, Station Number

Acceptance Criteria

 Given I am on the FWI Calculator, When I select any number of weather stations and press a button, Then the actual daily weather data for the past 5 days at each weather station is presented to the user

**Comment by jowand** [comment]
need more context - looks like a duplication of #238
