### ISSUE TITLE
ASA: Adding "Beta Version" reference

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#2419]
**Describe the task**
BCWS staff should be able to see that ASA is beta/work in progress

**Acceptance Criteria**
- [ ] Need to add a reference for product under development (beta)
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by andrea-williams** [comment]
![Screenshot 2022-12-21 at 2 01 09 PM](https://user-images.githubusercontent.com/54914403/209010852-2344ce47-4dc9-4fd9-a1fc-c08893ee1577.png)
