### ISSUE TITLE
Display imported forecast values for Temp and RH

### ISSUE THREAD

**Issue by jowand** [bcgov/wps#244]
**As a** *weather forecaster* **I want** *to select a weather station* **So That** *the next 10 days of forecast data is displayed graphically*

**Additional Context**
- it is not best practice for weather forecasting to download long range weather data and present them as specific values. An overloaded and tired forecaster might see the time save to just use these values if they're provided and not consider the inherent flaws.
- use 3hourly time steps (not just interpolated noon)
- Best practice is to use the models to indicate long term trends.

**Acceptance Criteria**
- [x] Given GDPS publishes 3 hourly data, When I select a weather station, Then three hourly datasets are graphed and the noon interpolated value is shown for each day out to 10 days
- [x] find good free graphing engine that works with React (think easy and quick, in case we pivot on the engine)
- [x] Design research on how to display Temp and RH values on a graph

**Comment by jowand** [comment]
![Capture.JPG](https://images.zenhubusercontent.com/5e8bcddb41fb38ef37045421/2b7f2964-af8d-4681-8b11-67369e714880)

**Comment by jowand** [comment]
better versions of the above: https://weather.gc.ca/ensemble/naefs/EPSgrams_e.html

**Comment by jowand** [comment]
@Sybrand 
Is pulling these two datasets together in a tabular format implied in their two separate tickets?

**Comment by Sybrand** [comment]
@jowand we wanted to give the developers and ux designer freedom w.r.t. to coming to a solution. Tabular format seems obvious - and is probably what they'll end up doing.

**Comment by PrakritiM** [comment]
![RH and TEMP (Foresight).jpeg](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/8ee6af20-0915-4177-932d-42290ae02576)

**Comment by PrakritiM** [comment]
https://spotwx.com/products/grib_index.php?model=gem_glb_25km&lat=50.70733&lon=-120.44621&tz=America/Vancouver
![Screen Shot 2020-05-14 at 10.57.26 PM.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/96725c36-0d82-4e4c-83f2-11a0de31082f)

**Comment by PrakritiM** [comment]
ENV Canada

![Screen Shot 2020-05-19 at 7.53.39 PM.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/6fa1ae6d-7a23-432a-825b-4cf56af715e7)

**Comment by PrakritiM** [comment]
https://akff.mesowest.org/map/#/c5377,-12041,4/g1/mc/vtemp/sAK/n/zt
![Screen Shot 2020-05-19 at 8.17.22 PM.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/dce79038-a4e7-420f-bfdf-0950bf37b6dc)

**Comment by PrakritiM** [comment]
Shared by forecaster:

[https://app.zenhub.com/files/235861506/0c019b9a-1eb1-42ef-82f0-2f25802582be/download](https://app.zenhub.com/files/235861506/0c019b9a-1eb1-42ef-82f0-2f25802582be/download)

**Comment by PrakritiM** [comment]
Comparison Chart:
https://miro.com/app/board/o9J_ksTKiW8=/
