### ISSUE TITLE
SSO: Final Migration Task

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2447]
**Describe the task**
Configuration change, see email for details, Subject: Final SSO Task, sent November 23

**Acceptance Criteria**
- [ ] Configuration is changed and works

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wildfire-Predictive-Services-5e321393e038fba5bbe203b8/issues/bcgov/wps/2447?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss
