### ISSUE TITLE
Update Shapely to v2

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2458]
**Describe the task**
Shapely v2 removes treating multipolygons as iterables, we need to reference those as `.geoms`

**Acceptance Criteria**
- [ ] https://github.com/bcgov/wps/pull/2456 builds and runs

**Additional context**
- https://shapely.readthedocs.io/en/latest/migration.html#migration

**Comment by dgboss** [comment]
This issue relates to updating Shapely in the tileserv module. We no longer use the tileserv module so no work needs to be done on this specific task.
