### ISSUE TITLE
Per PR NATS deployment config

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2462]
**Describe the task**
Nats backs message queue streams on disk and doesn't allow overlapping subjects. When new PRs are deployed containers are recreated with new PR streams that overlap and break the containers, devs need to manually delete the old stream for a new one to be created successfully if they want to test nats features. It should be a per PR deployment to avoid this overhead.

**Acceptance Criteria**
- [ ] Nats is deployed per PR
- [ ] PR dev deployment only spins up 1 node to save resources (discuss)
- [ ] Nats is deployed using a DeploymentConfig resource so that new deployments pull the latest image, currently the vanilla Deployment doesn't seem to be doing this

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2462?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss
