### ISSUE TITLE
Innovation: Machine-Learned Forecasts

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#2482]
**As a** fire weather forecaster

**I need** improved weather models tied to our weather stations

**So That** I can create daily weather forecasts with an acceptable level of accuracy more quickly than I can now

- [ ] apply linear regression algo on GDPS, RDPS, and HRDPS model data for fire season 2022. Result will be a ML model that can adjust biasses in each of the models
- [ ] compare bias-adjusted model data to hourly_actuals data. Forecasters want to know which EC model is the most accurate for each weather station and for each type of wx value (temp, RH, precip, wind speed, wind dir), and what value of bias adjustment should be applied to the raw output model data
- [ ] output will be ugly, un-snazzy tables for each wx station in some basic web UI that forecasters can click around and explore

**Additional Context**
- relevant to Morecast, but don't need to integrate this into Morecast for the innovation sprint
- see https://miro.com/app/board/o9J_ltNfSlY=/?moveToWidget=3458764541441658540&cot=14
- I'm thinking:
            + create Jupyter notebook for data analysis/ML
            + Streamlit app of CSVs/JSONs to view weather station data

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
https://andrea-williams-skillscore-weather-predictions-home-t285ot.streamlit.app/
