### ISSUE TITLE
ASA: Zonal summary (visual) for combustible land area in fire zone under advisory

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2519]
As a recipient of fire behaviour advisories

I need the ability to select a fire zone to open a text/graphical summary of the underlying fire environment associated with the advisory.

So That I know what conditions to watch out for to insure the safety of myself and coworkers.

Acceptance Criteria
- [ ] Summarize the percentage of combustible land area in the fire zone under advisory
- [ ] break down by 4,000 to 10,000 kW/m and > 10,000 kW/m categories 
- [ ] could be a stacked bar graph in the modal/popup when zone is selected

**Additional Context**
- enter text here
- enter text here

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2519?planning-poker) with Zenhub @conbrad @dgboss
