### ISSUE TITLE
ASA: Fuel Types

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#2521]
**As a** recipient of fire behaviour advisories

**I need** the ability to select a fire zone to open a text/graphical summary of the underlying fire environment associated with the advisory.

**So That** I know what conditions to watch out for to insure the safety of myself and coworkers.

**Acceptance Criteria**

- [ ] Show proportion % of area under advisory by Fuel Type: 4K to 10K, greater than 10K
- [ ] Fuel Type Labels instead of IDs 

**Additional Context**
- CSV mapping fuel type IDs in SFMS fuel type layer to fuel codes: [https://bcgov.sharepoint.com/❌/t/01324/EQVixiTNReFDh_Jhz8NTQVIBcSER2IT-5Ya15MX5kai6QQ?e=ndjmb3](https://bcgov.sharepoint.com/:x:/t/01324/EQVixiTNReFDh_Jhz8NTQVIBcSER2IT-5Ya15MX5kai6QQ?e=ndjmb3)

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2521?planning-poker) with Zenhub @conbrad @dgboss

**Comment by conbrad** [comment]
Break down by fuel type by HFI thresholds
