### ISSUE TITLE
ASA: Loading Indicator when Loading/Updating Tiles

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2533]
**As a** FBS **I need** to be able to monitor the loading progress of the fire zone data I selected **So That** i understand when the update process is completed

**Acceptance Criteria**
- [x] Loading Indicator when the requested tiles are in-flight
- [x] Loading Indicator disappears when tiles have arrived

**Additional Context**
- https://openlayers.org/en/latest/examples/tile-load-events.html

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2533?planning-poker) with Zenhub @andrea-williams @conbrad
