### ISSUE TITLE
ASA: HFI vector tiles only load at zonal extents, not provincially

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2534]
**As a** FBA **I need** to:

**Acceptance Criteria**
- [x] Given I am zoomed out at the Province level, I don't see and HFI Tiles
- [x] At the Zonal level, i can see the HFI Tiles
- [x] Given that I am zoomed in to a Xxxx % level, I CAN see the HFI Tiles
- [x] Given that I am zoomed in to a Xxxx % level, the map is updating as I move around the map

**Additional Context**
- enter text here
- enter text here

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2534?planning-poker) with Zenhub @andrea-williams @conbrad
