### ISSUE TITLE
ASA: Cleanup unused layers

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2537]
**As a** FBA **I need**  these removed:

**Acceptance Criteria**
- [x] Remove all layer options in the checkbox menu except for the high HFI
- [x] Remove Click Popup on Map

**Additional Context**
- enter text here
- enter text here

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2537?planning-poker) with Zenhub @andrea-williams @conbrad
