### ISSUE TITLE
ASA: User functionality to select a fire zone and view advisory information

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2545]
**As a** FBA **I need** to: 

**Acceptance Criteria**
- [ ] When I click on that fire zone, Then a information panel appears summarizing the fire behaviour environment and expected fire behaviour
- [ ] When I click on a fire zone, its boundaries are highlighted

**Additional Context**
- enter text here
- enter text here

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2545?planning-poker) with Zenhub @andrea-williams @conbrad
