### ISSUE TITLE
ASA: Advisory HFI Color Coding

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2546]
**Actual Behaviour**

It's not showing up

**Steps To Reproduce**

1. Load a date with lots of high HFI pixels
2. No advisory shows

**Screenshots**

**Expected Behaviour**
A clear and concise description of what you expected to happen:

- [x] Slider bar defaults to 20% 
- [x] Check and ensure slider bar works at the Zonal Level and not the Fire Centre level
- [x] Zone is coloured for a warning once 20% of the combustible land area is greater than 10K kW/m
- [x] Zone is coloured under advisory once 20% of the combustible land area is greater than 4K kW/m

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2546?planning-poker) with Zenhub @andrea-williams @conbrad
