### ISSUE TITLE
Calculator uses fire season based on Ecodivision

### ISSUE THREAD

**Issue by jowand** [bcgov/wps#255]
**As a** *user of 90th percentile calculator* **I want** *to know that the data used in the calculations is relevant to fire season* **So That** *I am not including irrelevant data*

**Additional Context**
- Advice from Dana Hicks is to use EcoDivision boundaries to assign BUI thresholds for weather stations.
- The core wildfire season was set for each Eco-division
- Eco-division                    Core Wildfire Season:
  - Sub-Arctic Highlands	June 1st to August 15th
  - Sub Arctic  	                June 1st to August 15th
  - Boreal	                            May 15th to August 31st 
  - Humid Continental Highlands	May 15th to August 31st
  - Humid Maritime and Highlands	May 15th to August 31st
  - Semi-Arid Steppe Highlands	        May 1st to September 15th 
  - Sub Arctic Pacific                      	June 1st to August 15th

- Eco-divisions: https://www.bctomorrow.ca/blog/natural-landscapes
- Use a shapefile of Eco Divisions

**Acceptance Criteria**
- [x] Given I want to only use data from the fire season each year, When I select a station, Then only 'fire season' data is used from each year
- [x] Given I want to know how fire season was defined, When I see the calculations, Then I want to see some text describing how we established the core fire season based on the eco division.
- [x] This is using pre-generated 90th Percentile Data

**Comment by jowand** [comment]
Update: 
'Fire season' in this sense is May to first of September 
There should be a BUI threshold to turn the season 'on' for stations in May.
All switch 'off' 1st Sept.

Dana is looking through climatology data to group our stations and assign BUI 'on' thresholds to groups. He's thinking something like a BUI of 40 in the north, something in the Cariboo, something in the south and coast and then just group stations into those zones.

**Comment by jakemorr** [comment]
review is "Zone" coule be used to group into the 3 threshold groups Dana is planning

**Comment by jakemorr** [comment]
Questions for @jowand and Dana

- Does fire season start at core fire season dates even if the BUI threshold has not been hit yet?
- Does fire season end at core fire season date if BUI is still above threshold?
- What is the BUI threshold for each Eco division?
- Do we show the Core Fire Season in the drop down or only in the Report?
- Where do we want to show the information regarding the BUI thresholds and fireseason dates for consultants?

**Comment by jowand** [comment]
@Kyubinhan 

Does fire season start at core fire season dates even if the BUI threshold has not been hit yet?
- we are going to stick with the dates, which are based off BUI threshold, hours of daylight and average climatic conditions. So don't worry about trying to calculate start on BUI, use the dates provided.

Does fire season end at core fire season date if BUI is still above threshold?
- yes

What is the BUI threshold for each Eco division?
- see point one, use the dates instead please.

Do we show the Core Fire Season in the drop down or only in the Report?
- in the report please

Where do we want to show the information regarding the BUI thresholds and fireseason dates for consultants?
- Can we have an info section? I've got a one pager in draft we can add? I'll put it on Teams
