### ISSUE TITLE
WF1: Test API for external clients to access weather data: Sanity Check

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2553]
**Describe the task**
Vivid has completed an API for external clients to consume weather data. They completed their own testing and would now like another round of internal UAT before making it available to external clients. 

**Acceptance Criteria**
- [x] Meet with Vivid to review the API and clarify UAT.
- [ ] Conduct UAT on weather API comparing daily fire weather records in the WildfireOne user interface against what is returned from the API.
 - [ ] Conduct UAT on weather API comparing hourly fire weather records in the WildfireOne user interface against what is returned from the API.
- [ ] Conduct UAT on weather API comparing fire danger summary in the WildfireOne user interface against what is returned from the API.
- [ ] In addition to verifying that the data is correct and in a useful format that can be easily consumed by industry, we'd like to get some verification on performance. There are connection limits in place via a wso2 gateway which may need some tuning.

**Additional context**
- Vivid provided API documentation in an email sent on January 26, 2023 at 4:25 PM. Look for the attached document "WE-WFWXDatamartAPI-270123-0021.pdf". The API can be accessed here: https://t1bcwsapi.nrs.gov.bc.ca/wfwx-datamart-api/v1/
- Vivid’s internal testing included hitting the end points and comparing those to data being returned in the environment we were working in. It was largely the integration environment where there is new data but a lower volume of stations. 
- Vivid also ran QA tests to make sure things such as not returning more than 31 days of data was working, the spatial query was returning the correct stations, the default end points were working correct with no parameters etc. 
- Additionally, Vivid developed some JMeter load testing scripts that we want to run in the TEST environment where there is more data.

**Comment by NicolasLivanos** [comment]
We will require the API specs/documentation + What needs to be tested @nealmcloughlin

**Comment by conbrad** [comment]
Preferably an API spec, so it automatically updated when things change. Here's ours: https://psu.nrs.gov.bc.ca/api/docs

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2553?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss
