### ISSUE TITLE
PWCO User Interview

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#256]
**Describe the task**
conduct interview and document results with Provincial Wildfire Coordination Officer

**Acceptance Criteria**
- [x] Conduct Interview
- [x] Workflow documented
- [x] list of data sources used by PWCO
- [x] list of preparedness decisions made by PWCO
- [x] how does a PWCO see their relationship with the Advanced Planner and the Provincial Weather Forecaster to get the data

**Additional context**
- Linked to RWCO and APL user research
- People to interview: Brad Litke, Todd Nessman, Derek Williams (Brady to confirm)

**Comment by PrakritiM** [comment]
[https://app.zenhub.com/files/235861506/c3b52c0d-6056-435d-9db7-3a409c6b06a8/download](https://app.zenhub.com/files/235861506/c3b52c0d-6056-435d-9db7-3a409c6b06a8/download)

**Comment by PrakritiM** [comment]
[https://app.zenhub.com/files/235861506/96b532d6-a947-40a2-872e-2e5539723cb9/download](https://app.zenhub.com/files/235861506/96b532d6-a947-40a2-872e-2e5539723cb9/download)

**Comment by PrakritiM** [comment]
User 3
[https://app.zenhub.com/files/235861506/1ffdefe9-cd8c-4adc-bd34-afe18529fcad/download](https://app.zenhub.com/files/235861506/1ffdefe9-cd8c-4adc-bd34-afe18529fcad/download)
