### ISSUE TITLE
Discuss: github actions - using actions in untrusted repositories.

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#258]
**Describe the task**
Using a GitHub action from another repo is a potential security risk. We need to assess and establish what risk mitigation steps to take.

**Acceptance Criteria**
- [ ] Decide as a team, what our stand is on this.
- [ ] Document process in contribution.md
- [ ] Create tasks to resolve issues on code base (if required)

**Comment by DerekRoberts** [comment]
I'd like to cut down on outside Actions, providing the more important functions with our own Actions.  There are also performance incentives for pulling down less Docker containers.  @Sybrand Meeting this up!

**Comment by DerekRoberts** [comment]
From: Strauss, Sybrand IIT:EX
Sent: May-04-20 14:40
To: Morris, Jake IIT:EX; Andrea Williams; Han, Kyubin IIT:EX; Roberts, Derek IIT:EX
Subject: GitHub actions - general discussion meeting notes
 
Notes from our GitHub actions meeting:

 

We want separate, fine grained tokens that whose names clearly indicate what rights they have and what their use is.
Forking GitHub actions is a lot of effort and manual maintenance, we prefer not to do that.
When using an external repository GitHub action we prefer to reference a particular commit point.
We prefer using GitHub actions that are trusted (we trust bcgov/* and built in github actions).
We dislike using “random” third part repository GitHub actions.
