### ISSUE TITLE
MoreCast 2.0: Add GFS weather model

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2584]
**As a** weather forecaster

**I need** additional weather models to chose from

**So That** I can provide the best possible weather forecast.

**Acceptance Criteria**
- [ ] Given I am creating a forecast, When I'm viewing and selecting what weather model to use, Then the Global Forecast System (GFS) is an added model option I can chose from.

**Additional Context**
- https://www.ncei.noaa.gov/products/weather-climate-models/global-forecast
- BCWS forecasters have requested that we select the nearest grid cell closest in elevation to a weather station. This will be completed in a separate task and will need to apply to all weather models. The focus here is to simply add all weather model data sources required by the forecasters.

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Darren: 
https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod

**Comment by NicolasLivanos** [comment]
Is this the correct forecast:
https://www.nco.ncep.noaa.gov/pmb/products/gfs/gfs.t00z.pgrb2.1p00.f003.shtml

**Comment by NicolasLivanos** [comment]
1![gfs.png](https://images.zenhubusercontent.com/629e41bedcfb3b5fdcef3008/575c87ad-a150-480c-af54-76ef54c0b60f))	You want the GFS model with 0.5 degrees resolution namely the one below. You want Temp, RH, Precip, Wind, Wind direction from the grid cell with the closest elevation to the station first, and then prioritize the grid cell with the closest lat long. Elevation representativeness is more important than proximity.

**Comment by andrea-williams** [comment]
List of raster bands for 000 forecast hour: https://www.nco.ncep.noaa.gov/pmb/products/gfs/gfs.t00z.pgrb2.0p50.f000.shtml

List of raster bands for 003+ forecast hours:
https://www.nco.ncep.noaa.gov/pmb/products/gfs/gfs.t00z.pgrb2.0p50.f003.shtml

Making assumption that we want to pull temp & RH values at 2m above ground level, and wind dir & speed values at 10m above ground level (this is what we're using for Env Can models)

NOTE: the raster band index docs suggest that temperature is reported in Kelvin (K). Based on the values I'm seeing, I think that's wrong and it's actually Celcius.
According to those same dodgy docs, U- and V-components of wind are reported in m/s - is there a way to confirm that's correct?

**Comment by nealmcloughlin** [comment]
Yes. pull temp and RH values at 2 m above ground and wind values at 10 m above ground. I have encountered weather models that report temp in Kelvin, but it's possible the documentation is out of date. Without documentation, I would assume the U- and V-components of wind are in m/s. You can use www.spotwx.com to confirm converted values for temp, wind speed, and wind direction are correct. Enter a coordinate for a station location and view select the GFS model. There are options to view the data in graphical or tabular formats.
