### ISSUE TITLE
MoreCast 2.0: Select/update data sources for each weather parameter in my forecast

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2585]
**As a** weather forecaster

**I need** the ability to select what combination of data sources to use

**So That** I provide the best possible information.

**Acceptance Criteria**
- [x] Given I'm selecting data sources for each weather parameter in my forecast (I.e. Temp, RH, Wind Direction, Wind Speed representing 1200 LST (or 1300 LDT), and precipitation from the past 24 hours), When I select a data source for a weather parameter, Then the values for that weather parameter auto-populate for each respective station and date in my forecast.

**Additional Context**
- It is possible that a weather forecaster may use different combinations of data sources (I.e. weather models, bias adjusted models, yesterday's weather, manual inputs) for each of the five weather parameters.
- Consider a drop down at the top of each column

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2585?planning-poker) with Zenhub @andrea-williams @dgboss
