### ISSUE TITLE
Discuss: branch naming conventions

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#259]
**Describe the task**
Contributors need to be consisting in the naming of their branches. Branches names should make it clear what ticket the branch relates to and what value the branch is adding.

**Acceptance Criteria**
- [x] Decide as a team on a branch naming convention.
- [x] Document the naming convention in contribution.md
- [x] Create any tasks that might flow from this discussion (e.g. enforcing branch naming conventions)

**Additional context**
- It's not helpful having a branch like: "ticket32", or "32" (oh great, now I have to go look for the ticket)
- It's not helpful having a branch like: "fixbug" (what bug?)

**Comment by DerekRoberts** [comment]
@Sybrand Let's do this!  Book a meeting and we get something decided in writing.
