### ISSUE TITLE
ASA: Colour-coded fuel types - Enhancement

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#2603]
**As an** FBAN

**I need** consistent colour-coding of fuel types in the pie charts for HFI Analysis by Fuel Type panel

**So That** I can more quickly recognize fuel types when I'm reading the charts

**Acceptance Criteria**
- [ ] Given I have selected a date of interest that has data available in ASA, When I select a fire zone, Then the pie charts that appear for the fuel type breakdown analysis should always use consistent colour styling for a given fuel type.
- [ ] Ensure the fuel type descriptions (C-2, etc) are accessible and do not overlap on the chart.

**Additional Context**
- RGB values for each of the fuel types are listed in this sheet ([https://bcgov.sharepoint.com/❌/t/01324/EQVixiTNReFDh_Jhz8NTQVIBcSER2IT-5Ya15MX5kai6QQ?e=ndjmb3](https://bcgov.sharepoint.com/:x:/t/01324/EQVixiTNReFDh_Jhz8NTQVIBcSER2IT-5Ya15MX5kai6QQ?e=ndjmb3)). These colour values are used consistently in BCWS so most users will be familiar with the fuel type colors.
- A provincial fuel map can be viewed in the WildfireOne WFWX - Fire Weather Info app. Click on the Fuel Types Map link in the header: https://wfapps.nrs.gov.bc.ca/pub/wfwx-info-war/sfms 

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by nealmcloughlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2603?planning-poker) with Zenhub @conbrad @dgboss @brettedw
