### ISSUE TITLE
Git: Cloning Repo on Windows Fails

### ISSUE THREAD

**Issue by agearhart** [bcgov/wps#2605]
**Actual Behaviour**

Running the command 
```
 git clone git@github.com:bcgov/wps.git
```
fails due to the illegal character `:` in the path
```
/api/app/tests/fixtures/console.pathfinder.gov.bc.ca:8443
```

**Steps To Reproduce**

1. On a Windows machine attempt to clone the repository.

**Screenshots**

![image](https://user-images.githubusercontent.com/2504116/217097450-82a7491b-d4e0-4c24-8aca-18015fcab19c.png)

**Expected Behaviour**

Cloning the repository on Windows should succeed.

**Comment by conbrad** [comment]
Hi there, please try checking out with:
```
git clone --sparse -c core.protectNTFS=false -n git@github.com:bcgov/wps.git
```

There is an old fixture in the git history that includes the ':' character.

See this for more details: https://github.com/git-for-windows/git/issues/2803

**Comment by agearhart** [comment]
![image](https://user-images.githubusercontent.com/2504116/218505405-827890de-adc9-43c9-9f29-d135b5719cbe.png)
I can confirm this resolves the issue.  Thanks so much for the help!
