### ISSUE TITLE
display past 5 days actual data for a given weather station

### ISSUE THREAD

**Issue by jowand** [bcgov/wps#261]
**As a** *FBAN or Forecaster* **I want** *to view historical weather datasets from the past 5 days from a given weather station* **So That** *I can compare the data for evaluation*

**Additional Context**
- historical weather datasets = actual, forecast and edited forecast data **(this ticket is only Actual)**
- this ticket is the first step for forecasters to be able to analyze this data. 
- authentication on API

**Acceptance Criteria**
- [x] Given I have selected a weather station, When I look at the forecasted values, Then I can also see the past 5 days actual values for the weather station.
- [x] Up to 3 weather stations at a time
- [x] Given I am not logged in using IDIR, When I try to access the app, Then I cannot see anything until I log in

**Comment by Sybrand** [comment]
@jowand is this story for actual noon values, or hourly values?

**Comment by jowand** [comment]
@Sybrand hourly
