### ISSUE TITLE
MoreCast: Request to develop WRITE WildfireOne API

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2618]
**Describe the task**
Submit a request to through WildfireOne project team to have Vivid develop an API so that MoreCast can **push** weather forecasts into the WildfireOne Weather App.

**Acceptance Criteria**
- [x] Meet with Vivid and BCWS weather forecasters to confirm data fields, time zone, and format for weather forecasts in WildfireOne Weather App.
- [x] Document requirements for a WildfireOne API that will allow MoreCast to push forecast data into the Weather App.
- [x] Submit a request to WildfireOne project team to have the API developed.

**Additional context**
- Development of an API is the top priority in the Weather App backlog.
- WildfireOne backlog work will not start until April 1, 2023.

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2618?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss

**Comment by conbrad** [comment]
From forecasters:
- temperature
- RH
- 24-hour precipitation to 12:00 LST in mm
- windspeed
- wind direction

**Comment by nealmcloughlin** [comment]
Note that temperature, RH, wind speed and wind direction are for 12:00 LST.

**Comment by conbrad** [comment]
@nealmcloughlin is LST equivalent to 13:00 noon?

Grass cure is another field that is manually entered by the RWCO.

Also cloud cover is something that is considered when forecasting but currently is looked up in an ad-hoc way.

**Comment by NicolasLivanos** [comment]
Hi @nealmcloughlin, 

Pls find below the API Request ready to be sent out (conbrad completed):

+++++++++

Hi **Business Owner**, 

The WF1 API already has an endpoint that can be used for saving forecasts on a forecaster’s behalf.

Currently, WPS has access only to read from the WF1 API, not write.

We have currently:
-	Access to read from WF1 API through a token with read access

We need:
-	Access to write to WF1 API by having them set our token with write access
o	This write access can be scoped to just write access on their /dailies endpoint for Morecast v2

-	An authorization from you as the **Business Owner** for Vivid to grant us write access

Let me know if you have any more questions.

Agile PSU

++++++++++++++++++++++
