### ISSUE TITLE
MoreCast 2.0: Auto-generate a HRDPS basic weather forecast (iteration 1)

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2619]
**As a** weather forecaster

**I need** basic configuration options

**So That** I can quickly auto-generate a forecast.

**Acceptance Criteria**
- [x] HRDPS model is the one to be used (iteration 1)
- [x] Given 1 configuration options (Fire Centre), When I select my Fire Centre, Then a weather forecast is auto-generated for the next three days (DAY1 is Today, DAY2 is 1 day out, DAY3 is 2 days out) for each of the weather stations located within my Fire Centre.
- [x] Show N/A values for the missing days.

**Additional Context**
- The format for a weather forecast can be viewed in the recorded session with BCWS forecasters available here:
https://bcgov.sharepoint.com/:v:/t/01324/ER0TyvQVpjdDgIz1Ibu_Lf4BZ_qH_MDC6RgC7UX2JlhSoA?e=R76bkg

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2619?planning-poker) with Zenhub @conbrad @andrea-williams @dgboss
