### ISSUE TITLE
Update team poster in Miro Sprint review

### ISSUE THREAD

**Issue by jowand** [bcgov/wps#266]
**Describe the task**
Replace Brady's picture wtih Jo and Remove Derek and Nithin.

https://miro.com/app/board/o9J_kvUSfDU=/

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by PrakritiM** [comment]
Updated poster:
![wildfire predictive.jpg](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/0f70302d-5fb6-46f7-843d-e22658d951f6)

**Comment by PrakritiM** [comment]
![wildfire predictive-2.jpg](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/9d94b6c5-be4f-42d7-abe8-f30737b37e30)
