### ISSUE TITLE
MoreCast 2.0: NAM Weather Model

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#2664]
As a weather forecaster

I need additional weather models to chose from

So That I can provide the best possible weather forecast.

Acceptance Criteria
Given I am creating a forecast, When I'm viewing and selecting what weather model to use, Then the NAM model is an added model option I can chose from.

Additional Context

Definition of Done
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by andrea-williams** [comment]
SpotWx uses this as their data source for NAM: https://www.nco.ncep.noaa.gov/pmb/products/nam/

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2664?planning-poker) with Zenhub @andrea-williams @conbrad
