### ISSUE TITLE
Agile PSU: Support Ticketing System | Timebox = 2 DAYS

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#2694]
**As a** valuable BCWS team member

**I need** to be able to fully communicate any and all technical issues I am having with all Agile PSU products/tools

**So That** I can get these acknowledged and resolved, right away and avoid email chains or multiple communications to resolve any issue

**Acceptance Criteria**
- [ ] A front end widget that posts tickets on Github Issues
- [ ] Given I submit a bug, When I also submit a screenshot, Then the Agile PSU can quickly identify the issue and triage severity and/or a solution
- [ ] Follow up on bug submission via private chat; status updates
- [ ] Searchable History of Reported Bugs
- [ ] Stats/Analytics/Classify/Label bugs?

**Additional Context**
- Sentry bug reporting / capture problems (user submitted bugs, session replaying, error reporting)
- Proposed TEAMS & GitHub integration:
https://github.com/integrations/microsoft-teams
- ChatGPT App Store: GPT-4 Turbo

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2694?planning-poker) with Zenhub @andrea-williams @dgboss

**Comment by conbrad** [comment]
To consider: https://submit.digital.gov.bc.ca/app/api/v1/docs
