### ISSUE TITLE
MoreCast 2.0: Filter for active weather stations

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2705]
**As a** weather forecaster

**I need** to filter the weather forecast table view to only show the active stations in my Fire Centre

**So That** I don't have to manually deselect in-active weather stations that I won't be providing forecasts for.

**Acceptance Criteria**
- [ ] Given I create a new forecast, When the table view populates stations for my Fire Centre, Then only the stations with an active attribute in WF1 are displayed.
- [ ] Given I have a toggle to "Display inactive stations", When this toggle is turned on, Then both active and inactive stations in my Fire Centre are displayed in the table view.

**Additional Context**
- The default is to only show active stations.

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2705?planning-poker) with Zenhub @andrea-williams @dgboss
