### ISSUE TITLE
MoreCast 2.0: Highlight manual edits

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2707]
**As a** weather forecaster

**I need** to see where I have made manual edits to raw model data sources

**So That** I can keep track of what I have modified.

**Acceptance Criteria**
- [ ] Given I select a cell in the forecast weather table, When I make a manual edit, Then the cell value should be highlighted with a different color or font.

**Additional Context**
- For consistency with other Agile products, the HFI Calculator uses bold font to highlight where edits have been made.
- If the selected model is changed, manual edits are not expected to persist.

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2707?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss
