### ISSUE TITLE
Pull a list of weather stations that are up to date from the API

### ISSUE THREAD

**Issue by jowand** [bcgov/wps#271]
**As a** *SME* **I want** *to know which weather stations have up to date data* **So That** *I know I am using the most up to date dataset in the 90th Percentile Calculator*

**Additional Context**
- currently we are using a snapshot of the 2019 weather database that is incomplete

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- "up to date data" includes all of the previous year's fire season (2019)

**Comment by Sybrand** [comment]
I've started implementing this..... oops: branch: feature/wf1_api_weather
