### ISSUE TITLE
Morecast 2.0: Use more up-to-date source for GFS model data

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#2734]
**Describe the task**
After discussion with SpotWx, found out there's a slightly different source for GFS model data (that's still from NOAA, just on different servers) that appears to be more up-to-date. We should replace the URL we use now to fetch GFS data with this improved data source, so that we can have the most recent data possible, and so that we can (hopefully) perform noon interpolation from a complete dataset.

**Acceptance Criteria**
- [x] URL for GFS data pulling is replaced with either https (https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/) or ftp (ftp://ftp.ncep.noaa.gov/pub/data/nccf/com/gfs/prod) server `nomads.noaa.gov`
- [ ] Confirm that `weather_station_model_predictions` database table is now being populated with GFS model data (requires interpolation to calculate noon values)
- [ ] Confirm that our machine learning is running successfully to calculate bias adjusted values for temp & RH from GFS model data

**Additional context**
- See https://www.nco.ncep.noaa.gov/pmb/products/gfs/ 
- We have been pulling data from `ncei.noaa.gov` - it is always a few days behind schedule and often has incomplete datasets. `nomads.noaa.gov` appears to be up-to-date

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2734?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss
