### ISSUE TITLE
MoreCast 2.0: Separate tabs for each weather parameter

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2736]
**As a** weather forecaster

**I need** to simply my display

**So That** I'm not overwhelmed by all of the data sources for each weather parameter on one screen.

**Acceptance Criteria**
- [ ] Given I have tab for each of weather parameters (temp, rh, wind speed, wind direction, precip), When I select a tab, Then I only see data sources for the selected weather parameter.
- [ ] Given I have a tab for my forecast, When I select this tab, Then I can see my comprehensive forecast values for temp, rh, wind speed, wind direction, and precip.

**Additional Context**
- For future consideration: These tabs could actually be toggles for what columns to turn off thereby allowing forecasters to add in other columns as they see fit. Eg.) Show Temperature, Relative Humidity, and Precip at the same time vs Wind Speed & Direction.

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
https://www.figma.com/file/VhTyJ9w0k8qSjdxAtSfdah/Untitled?t=N40nN7yvj2jeBpAJ-0

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2736?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss
