### ISSUE TITLE
MoreCast 2.0: Display all data sources simultaneously by tab

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2737]
**As a** weather forecaster

**I need** to see all data sources side by side

**So That** I don't have to flip back and forth to explore and compare what to use in my forecast.

**Acceptance Criteria**
- [ ] Given tabs for each of the weather parameters, When I select a tab, Then all of the possible data sources show up in the table but are not editable. Here is the suggested column order with non-editable data sources in bold (Station, Date, Forecast, **Actual, HRDPS, RDPS, GDPS, NAM, GFS**). 
- [ ] Given tabs for each of the weather parameters, When I select a tab, Then my first column is my editable forecast column that I use to select a data source using a drop down or manual input.

**Additional Context**
- The "Forecast" column is equivalent to current weather parameter column with a drop down to select a source and/or manually edit.
- For a future iteration we could include bias corrected outpu8ts beside each of the respective model options.
- Forecast cell value can be entered manually OR all values are updated from the weather model selected by the weather model selector menu

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2737?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss
