### ISSUE TITLE
Common repo. 2/3 investigate Serving static WEB up in API

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#274]
**Describe the task**
Goal is serving up static content, ideally can run on same pods as API.

**Acceptance Criteria**
- [ ] coming up with a decision on. technical solution to this issue that the team agrees on
- [ ] write the ticket for the solution

**Additional context**
- Having to separate kinds of pods deploy is overly complicated.

**Comment by Sybrand** [comment]
Looks pretty straight forward: https://fastapi.tiangolo.com/tutorial/static-files/

**Comment by Kyubinhan** [comment]
PRs(FE & API) have been merged instead of creating a ticket. These changes explain themselves how we are going to deploy FE and API together.
