### ISSUE TITLE
Morecast2: Refactor Actuals/Forecasts

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2778]
**Describe the task**
Lots of issues with the frontend implementation of actuals -- simplify the frontend by including actuals and forecasts together in the model request for a date range.

E.g. response could look like:

```
{
actuals: []
predictions: []
forecasts: []
}
```
**Acceptance Criteria**
- [ ] Actuals, Forecasts, Predictions and 1 response for date range and stations
- [ ] Has test coverage
- [ ] Return null values for predictions that don't have any data, e.g. RDPS on day 3 in range

**Additional context**
- Doesn't need to be hooked up to frontend

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2778?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss
