### ISSUE TITLE
MoreCast 2.0: Show/Hide Columns

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#2784]
As a Forecaster

I need the ability to select which columns I want to view in MoreCast

So that I can declutter the interface and see only the columns that are relevant to my work.

**Acceptance Criteria**
- [ ] Make the show/hide UI clearly evident on the front end
- [ ] We want fine grain control on which columns are displayed for each weather variable

**Additional Context**
- enter text here
- enter text here

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2784?planning-poker) with Zenhub @andrea-williams @dgboss

**Comment by rajpersram** [comment]
First draft of possible interaction design found on Figma at: https://www.figma.com/file/0iKI82NZZtYR8UrdTMdVLD/MoreCast-2.0?type=design&node-id=1-3&mode=design&t=APaKY6Ch3zylBaoG-4

**Comment by conbrad** [comment]
LGTM!
