### ISSUE TITLE
Pandas v2: Upgrade

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#2800]
**Describe the task**
Renovatebot opened up a new PR with an upgrade of our pandas dependency to v2. Since it's a major version upgrade, we'll need to invest some extra time and effort to ensure that it doesn't introduce breaking changes. From my memory, we only use pandas for cronjobs related to fetching weather model data, so testing will revolve around that rather than whether or not our apps are working. 

**Acceptance Criteria**
- [ ] Confirm where being used and how
- [ ] Determine value of upgrading to Pandas V2 - what other options exist to remove dependency
- [ ] If no other options upgrade to V2

**Additional context**
- See https://github.com/bcgov/wps/pull/2776
- weather model data from EC (for GDPS, RDPS, and HRDPS) is being fetched and written to our DB, including the bias adjusted temp and RH variables being calculated by our cronjobs
- weather model data from NOAA (for GFS and NAM) is being fetched and written to our DB.

**Comment by BAAlexK** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2800?planning-poker) with Zenhub @brettedw @conbrad @dgboss
