### ISSUE TITLE
MoreCast 2.0: Show Actual Values in Forecast Summary Tab

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2804]
**As a** Weather Forecaster, **I need** to see the Actual Values in the Forecast Summary Tab

 **So That** I can see the actual values trending into my forecast values

**Acceptance Criteria**
- [ ] Given I switch to the forecast summary tab, When actuals exist in the date range, Then I see those actual values for their dates/stations/weather parameters

**Additional Context**
- Combined View: 
- enter text here

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by conbrad** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2804?planning-poker) with Zenhub @dgboss
