### ISSUE TITLE
ASA: Advisory threshold for zones is treating 4K and 10K HFI areas separately

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2807]
**Actual Behaviour**

When ASA maps a zonal advisory (orange) or warning (red), the combustible land area threshold treats cells with HFI values 4,000 to 10,000 kW/m separate from cells with HFI values > 10,000 kW/m.

**Steps To Reproduce**

1. Set the date to April 26, 2023, the data source to ACTUAL, and zoom into the Chilcotin fire zone.
2. Click on the Chilcotin fire zone to open the left-hand data summary panel. The percentage of combustible land meeting advisory conditions is 13.71% and warning conditions is 5.79%.
3. Use the sliderbar to adjust the Advisory HFI Threshold of combustible area down to 19%. Notice there is no advisory mapped for this zone. Next adjust the sliderbar down to 13%. Notice the zone is mapped as under advisory. Last, adjust the sliderbar down to 5%. Notice the zone is mapped as under warning.

**Screenshots**

![image.png](https://images.zenhubusercontent.com/620bde3dcd6ceff7087c1f0d/3fac3d6b-1292-4251-8bb9-3e141815ac98)

**Expected Behaviour**

The Advisory HFI Threshold of combustible area sliderbar should be based on the cumulative area of both the 4K and 10K HFI  cells. In the example provided, these areas add up to 19.5% of the zone. The zone should be mapped as under advisory when the sliderbar is set to 19% as the cumulative area of 4K and 10K HFI cells exceeds 19%, but the 10K HFI cells are less than 19%. The logic would look something like this:

if( sum(4K HFI + 10K HFI) >= sliderbar & 10K HFI < sliderbar ) then map as orange advisory
  else
if( sum(4K HFI + 10K HFI) >= sliderbar & 10K HFI >= sliderbar ) then map as red warning
  else
do not map as advisory or warning

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2807?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss
