### ISSUE TITLE
HFI Calc: Configure Planning Areas based on Core vs Shoulder Season

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#2808]
**As a** HFI Calc user

**I need** to be able to easily adjust my fire centre's planning areas & weather stations

**So That** I can configure weather stations and fuel type combos appropriate to the time of year (core vs. shoulder fire season)

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Additional Context**
- will need to introduce versioning for planning area configurations for a fire centre
- based on GB's (from COFC) email request

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
duplicate 2845
