### ISSUE TITLE
Design pattern for app names on app page

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/wps#2814]
Currently PSU has three different ways to display an app name:

1. With Predictive Services Unit as the main header & app name as a secondary header.
![image.png](https://images.zenhubusercontent.com/6418c8e325e25077cfe5d6c2/d65a657f-10fa-4f23-96ba-02fb0152e5d0)

2. With just Predictive Services Unit as the main header and no app name
![image.png](https://images.zenhubusercontent.com/6418c8e325e25077cfe5d6c2/3d79ca29-8fbe-4837-8a68-bbb37cfbdac7)

3. With just the app name as the main header and no unit name
![image.png](https://images.zenhubusercontent.com/6418c8e325e25077cfe5d6c2/7ad903c2-872f-4ad1-95a7-308788a79682)

**Option 3 is the recommended solution.**
- The name of the app is the most important piece of information, not the business unit name
- You should have the name of the app displayed so you know which tool you are in especially as some are quite similar in look & feel
- The business unit name can change, requiring more on-going maintenance.

**Comment by NicolasLivanos** [comment]
https://developer.gov.bc.ca/Design-System/About-the-Design-System
