### ISSUE TITLE
Morecast 2.0: Bias-adjusted values for Precip

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#2816]
**As a** Fire Weather Forecaster

**I need** To see bias-adjusted values for precipitation for all 5 weather models (GDPS, RDPS, HRDPS, NAM, GFS)

**So That** I have more (and maybe smarter) options for data sources when making my weather forecasts

**Acceptance Criteria**
- [ ] Given I've logged in to Morecast 2.0, When the Precip tab is enabled, Then the 5 columns for GDPS Bias, RDPS Bias, HRDPS BIas, NAM Bias, and GFS Bias display values for any rows where the raw model has data available

**Additional Context**
- should be able to extend existing code (I think it's called `machine_learning.py`) to add in these 3 wx variables - bias adjusted values will be calculated as part of the grib file processing script when weather model data is fetched and stored in our DB
- Grib values: Linear Regression

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by dgboss** [comment]
Moving this into a blocked state. I'll need to incorporate significant changes made by Conor in the bias adjusted wind direction ticket when it is complete.
