### ISSUE TITLE
HFI Calculator: Change default fuel types for COFC

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2823]
**As a** User of HFI Calculator in COFC

**I need** to change the default fuel types assigned with stations

**So That** calculated values better represent spring fire hazard for prep planning

**Acceptance Criteria**
- [x] Assign HFI station admin permission to BCWS.COFCRWCO@gov.bc.ca. 
- [x] Work with COFC RWCO (GB) to use the HFI station admin permission to change stations and default fuel types to match what is described for shoulder season in the reference document.

**Additional Context**
See PDF document on SharePoint here: 
https://bcgov.sharepoint.com/:b:/r/teams/01324/Shared%20Documents/General/_Preparedness%20Products%20(HFI,%20Prep)/HFI%20Calculator/Design%20Docs/COFC%20Shoulder%20Season%20Prep.pdf?csf=1&web=1&e=a5VnKB

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by andrea-williams** [comment]
Had a quick call with GB. Necessary HFI permissions assigned to desired IDIR accounts related to COFC.
