### ISSUE TITLE
MoreCast 2.0: Station groups returning no data

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2830]
**Actual Behaviour**

Three weather station groups for the SEFC forecaster are returning no data.

**Steps To Reproduce**

1. Search for station groups associated with the SEFC forecaster IDIR.
2. Chose one of the following three groups: N7 Kootenay Lake, SEFC, x fx
3. The table loads no data and provides no message as to what's going on.

**Screenshots**

![image.png](https://images.zenhubusercontent.com/620bde3dcd6ceff7087c1f0d/600d381d-b6f2-4938-8317-859d77c3b7ed)If applicable, add screenshots to help explain your problem.

**Expected Behaviour**

The station groups should load the associated weather stations and populate data in the table. If there is a legitimate reason as to why stations are not loading from the group then an error message should appear.

**Comment by dgboss** [comment]
The root of the problem is that one (or more) of the stations in these groups does not have a fire zone property. We don't really need the fire zone so we can add a null check and avoid the issue.
