### ISSUE TITLE
MoreCast 2.0: PSU DEV Environment setups + Pairing to test, dev, prod, WF1

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#2842]
**Describe the task**

Aligning our Environments w/ WF1

**Acceptance Criteria**
- [ ] Dev authenticates and posts data to WF1 Integration (or dev?) 
- [ ] Test authenticates and posts data to WF1 Test 
- [ ] Prod authenticates and posts data to WF1 Prod 

**Additional context**
- 1:1 mapping to WF1 
- WF1: Integration, DEV, Test, Prod
- Or here

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2842?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss

**Comment by conbrad** [comment]
Duplicated in #2843
