### ISSUE TITLE
MoreCast 2.0: Simulated Indices Experiment - TIMEBOX = 1/2 Day

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#2844]
Investigate the use of the WildfireOne Simulate Indices endpoint in MoreCast 2.0.

**Acceptance Criteria**
- [x] Test endpoint and determine if it can be used for multiple days
- [x] Can we provide calculated indices in the endpoint or does it reference only WF1

**Additional context**
- /Weather/SimulateIndices 
- Option for Daily Indices

**Comment by conbrad** [comment]
Answers to AC above

>  Test endpoint and determine if it can be used for multiple days

No, currently just a single day/hour

> Can we provide calculated indices in the endpoint or does it reference only WF1

No, but you can always just ignore values from the internal implementation if you don't want them. Note that the internal implementation is following a specific spec that is used throughout the WFWX systems so not sure why you would want to supersede them.
