### ISSUE TITLE
90th Percentile Calculator: Update Weather Data to End of 2023

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2847]
**Describe the task**
Weather data are now a couple years out of date: we need to update the weather data used by 90th Percentile Calculator to the end of 2023: go back 30 years from 2023 for the stations that do have 30 yr data; otherwise report N/A, perhaps? DEVs to decide

**Acceptance Criteria**
- [ ] Weather data are updated to end of 2023 on Datamart
- [ ] 90th percentile calculations reference the new date range.
- [ ] remove quick deploy (QD = non-permanent) and Environment Canada (EC) stations
- [ ] Include all historical stations including active.

**Additional context**
- Documentation for the Datamart and API options for accessing BCWS weather data can be found here: https://bcgov.sharepoint.com/:b:/r/teams/01324/Shared%20Documents/General/_Prevention%20Products%20(90th%20Percentile)/Percentile%20Calculator/BCWS%20Datamart%20and%20API%20%20V2.pdf?csf=1&web=1&e=QQBryt 
- Don't rely on the pre-existing weather_stations.json file as a source of weather station info.

**Comment by BAAlexK** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2847?planning-poker) with Zenhub @brettedw @conbrad @dgboss

**Comment by brettedw** [comment]
![Image](https://github.com/bcgov/wps/assets/42357257/b24163b6-05af-4ae5-8cb3-a10c6b5d352a)
