### ISSUE TITLE
All products: Update header

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/wps#2862]
Update all PSU app headers to match the PSU header pattern.

**Acceptance Criteria**
- [x] BC gov logo links to the PSU app landing page
- [x] Header text is the app name, not the business unit name
- [x] Add Beta to headers for products with 'Beta' (see [design system](https://developer.gov.bc.ca/Design-System/Beta-Status))
- [x] Remove any subheaders with app names

https://www.figma.com/file/P9X1mPB5pfipJ6S3IQETEk/PS-Pattern-Library?type=design&node-id=12-40&t=2IKxzcI5eHZdqsBt-0

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2862?planning-poker) with Zenhub @dgboss @conbrad
