### ISSUE TITLE
ASA: Map toggle for advisory polygons

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2882]
**Describe the task**
Add a map toggle to turn on/off the fire zone advisory polygons similar to how there is a map toggle for High HFI.

**Acceptance Criteria**
- [ ] Toggle checked on displays orange/red polygons for zones under advisory/warning.
- [ ] Toggle not checked turns off display of zone advisory polygons.

**Additional context**
- Just a toggle to accompany the HFI toggle in the upper left corner; 
- Further refinement + symbology + placement in # 2824

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2882?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss
