### ISSUE TITLE
ASA: UI text refinement

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2887]
**Describe the task**
Refinements to the text surrounding dropdowns, date selectors, and slider bar so it makes more sense to the user.

**Acceptance Criteria**
- [x] The "Date of Interest" text does not require a time zone in brackets. Remove the time zone.
- [x] The text for the "Fire Center" drop down is replaced with the Canadian spelling "Fire Centre".
- [x] The text above the slider bar can be revised to say "Percentage of combustible land threshold".

**Additional context**
- N/A

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2887?planning-poker) with Zenhub @andrea-williams @conbrad @dgboss
