### ISSUE TITLE
ASA: Implement Map Legend

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#2896]
**Describe the task**
As a ASA User I want to have a legend in order to understand the map layers so that I can toggle these ON and OFF

**Acceptance Criteria**
- [ ] Use existing color palette
- [ ] On first login: only show advisory polygons w/ HFI pixels turned off as the default setting
- [ ] Add toggle to turn on + off the Advisory Polygons; keep the boundaries, remove the color styling
- [ ] Both the Advisory Polygons + HFI layers, add a legend of what the colors represent

**Additional context**
- https://www.figma.com/file/YbTS5mEgXgCApFkGnZqvfj/ASA-Desktop?type=design&node-id=55-1824&mode=design&t=3BZMpHzoclnTlrEd-4 
- legend location + placement: bottom left, white background

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2896?planning-poker) with Zenhub @brettedw @dgboss

**Comment by rajpersram** [comment]
Nicely done! The positioning is bang on, and I like that you left HFI off by default. I guess the displaying of the layers is yet to come, as I didn’t notice any change when toggling the checkboxes.

Is there an existing colour palette for the oranges and reds? If we don't have a style guide (I haven't come across one so far), I can start to put one together in Figma.

A few picky design notes…(sorry!). Here are some CSS suggestions but feel free to use anything else that seems more appropriate:

Main Title:
-	In a h1 tag
-	Can remove the font weight and it should default to bold
-	Font-size: 1.2rem
-	Margin: 0.8em 0.6rem

Subtitles (Zone Status, HFI):
-	h2
-	font-size: 1rem
-	can remove the font-weight 

Color boxes:
-	The span that showns the color boxes needs a style of: outline: 1px solid black;
-	Orange: rgba(255, 187, 78, 1)
-	Red: rgba(255, 63, 60, 1)
