### ISSUE TITLE
ASA: Spike for zone units (Timebox 1 day)

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2898]
**Describe the task**
Figure out what is possible with the new zone unit shapefile(s). Can we reuse our existing database architecture/frontend assumptions for including zone units, or do we need to restructure one or both?

**Acceptance Criteria**
- [ ] Answer the question: what work, if any refactoring our database architecture / app to be done to support zone units (maybe nothing! maybe a lot!) 
- [ ] Answer the question: Do we have/need zone labels?
- [ ] Answer the question: Can we pre-compute combustible area/stats per zone unit as defined in: https://app.zenhub.com/workspaces/bcws---agile-psu-5e321393e038fba5bbe203b8/issues/gh/bcgov/wps/2897
- [ ] Be able to estimate: https://app.zenhub.com/workspaces/bcws---agile-psu-5e321393e038fba5bbe203b8/issues/gh/bcgov/wps/2387

**Additional context**
- Shapefiles: https://bcgov.sharepoint.com/:f:/t/01324/Egon3hGO2QZFg2XANSQ9suwBvj04HIPqX5bnA8f7u0SAIg?e=FmXB8U

**Comment by dgboss** [comment]
List of required front-end changes (not exhaustive):
 - create new pmtiles layer from shapefile (done)
 - create new pmtiles layer for zone unit labels based on centroid of polygons (done)
 - field names in the new pmtiles files differ from the old files, so updating field names in order to access property values on the front-end is required
 - No longer using the 'mof fire zone id' field, instead use 'objectid'
 -

**Comment by dgboss** [comment]
List of required back-end changes:
 - Update ShapeTypeEnum to include value of 'fire_zone_unit'
 - Drop rows from Shape table (ie. advisory_shapes). Populate Shape table from geojson (derived from the shape file using QGIS). Note that source-Identifier will now be the OBJECTID values.
 -  Alternatively, just add new rows to the Shape table using the OBJECTIDs and new shape type enum value of fire_zone_unit
 -  rename `FireZoneArea` schema to `FireShapeArea` and change `mof_fire_zone_id` property name to `fire_shape_id` (front-end work required to match this change when parsing API responses
 -  rename `FireZoneHighHfiAreas` to `FireShapeHighHfiAreas' and change name of `mof_fire_zone_id' property
