### ISSUE TITLE
WF1 Phase 3 API Access

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/wps#29]
**Describe the task**
Learn how to gain access to the API

**Acceptance Criteria**
- [x] Align with Selkirk on how to get access from our servers to their servers
- [x] Determine how authentication to their servers works
- [ ] make tickets for each step required for authentication to required servers

**Additional context**
- who is our main contact with Selkirk? Brady to confirm

**Comment by jowand** [comment]
Hi @Sybrand, did Jerald send you the document with credential access discussed at our meeting with WF1 weather team, on the 16th?

**Comment by Sybrand** [comment]
@jowand yes he did - got sidetracked with silviculture and didn't take it further. We're ready to start integrating from our development environment to their development environment.
