### ISSUE TITLE
Introduce Storybook (UI development tool) to Web

### ISSUE THREAD

**Issue by Kyubinhan** [bcgov/wps#291]
**Describe the task**
Add [Storybook](https://storybook.js.org/) to the web project in order to improve UI development. The tool enables developers to create components independently and showcase components interactively in an isolated development environment.

**Acceptance Criteria**
- [x] Add storybook for React/Typescript
- [x] Add stories for some of our reusable components (`src/components`)

**Comment by Sybrand** [comment]
Don't tell @jakemorr that we pulled this in! Shhhh.
