### ISSUE TITLE
MoreCast 2.0: Grass Curing

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#2914]
**As a** Weather Forecaster 

**I need** an optional column to enter Grass Curing Values

**So That** I can complete my forecast, if I need to forecast a value

**Acceptance Criteria**
- [ ] Given I am in the Forecast Summary Table, Then there's an option to add a Grass Curing numerical value: 0-100
- [ ] Grass Curing Value updates both WF1 and MoreCast 2.0 Databases

**Additional Context**
- Optional Column similar to Wind Direction
- Expected Behavior: If a value isn't entered, previous value persists (WF1 is source of truth)
- WF1 value storing + Retrieving previous values?

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by brettedw** [comment]
https://cwfis.cfs.nrcan.gc.ca/downloads/pcuring/Percent_curing_metadata_NAP_ISO_19115_2003.pdf

**Comment by rajpersram** [comment]
Initial design [draft 1 available in Figma](https://www.figma.com/file/0iKI82NZZtYR8UrdTMdVLD/MoreCast-2.0?type=design&node-id=30-42&mode=design&t=7dWHMdfDr5hEbMC1-4).
