### ISSUE TITLE
Update npm frontend dependencies

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2931]
**Describe the task**
npm dependencies are up to date, building and running correctly

**Acceptance Criteria**
- [ ] frontend builds and runs correctly across all apps

**Additional context**
- Punting many updates including: https://github.com/bcgov/wps/pull/2930

**Comment by jmetev1** [comment]
are you looking for help on this? i enjoy updating dependencies. but to me "up to date" is too ambiguous. do you want to go minor version updates? updating to latest major versions seems like a lot of work.

**Comment by jmetev1** [comment]
if yes, do you think readmes are up to date? i've been trying to get this running and running into difficulties. I ran docker compose commands which took a lifetime and then ended up with ` The Poetry configuration is invalid:` For instance i see `- Note: We are using Node 14 as a base image on our pipeline.` which doesn't look to be true.

**Comment by conbrad** [comment]
> are you looking for help on this? i enjoy updating dependencies. not sure what the punting additional context mean. you don't want to do those?

Sure! We've been deprioritizing this in favor of other tasks for a while now, help would be welcome :)
The Typescript update causes a bunch of compilation issues that needs to be addressed.

> if yes, do you think readmes are up to date?
https://github.com/bcgov/wps/blob/main/api/README.md and https://github.com/bcgov/wps/blob/main/web/README.md should be up to date. It's unlikely that the local docker README is up to date as you've noticed, we don't use local docker builds much anymore.

**Comment by jmetev1** [comment]
cool cool. do you want to do major version upgrades like axios and react?

**Comment by conbrad** [comment]
@jmetev1 I've send you an invite for write access to the repo, let me know once you've been able to accept

**Comment by jmetev1** [comment]
invitation accepted
