### ISSUE TITLE
Can we use Common Services Team DB template with Post GIS?

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#295]
**Describe the task**
Can we use Common Services Team DB template with Post GIS?

**Acceptance Criteria**
- [x] is it possible?
- [x] if it is possible, how should we do it
- [x] how much effort would it be to do

**Additional context**
- prefer to use PostGIS DB from the start

**Comment by Sybrand** [comment]
I've sent rocketchat messages to Gary and Mat asking: "Who's the best resource to ask questions about getting that HA postgresql database into our project? Specifically - we'd want it with PostGIS and wonder how much work it would be making that happen." - waiting for response.

**Comment by Sybrand** [comment]
- I've reached out to #general on rocketchat  re. PostGIS in general - Steve Hillier has responded and is sending me a HA PostGis template.
- Mat hall also sent this: https://github.com/bcgov/nr-get-token/wiki/High-Availability

**Comment by Sybrand** [comment]
Steve Hillier: 
"It would be nice to maybe make a PR to the BCDevOps repo but for now I uploaded a Dockerfile here https://gist.github.com/stephenhillier/17bf0a7365f00c916d80733028f34ae9

gist.github.com
PostGIS Patroni Dockerfile
PostGIS Patroni Dockerfile. GitHub Gist: instantly share code, notes, and snippets.
It uses the Docker hub Postgres because I based it off the Dockerfile in the BCDevOps repo"

**Comment by Sybrand** [comment]
Seems very do-able - the platform team has a patroni templates and docker files: https://github.com/BCDevOps/platform-services/tree/master/apps/pgsql/patroni/ and the water team has experience applying PostGIS on top of what they have.

**Comment by Sybrand** [comment]
I've started exploring this on branch: task/postgis_ha
Following the platform teams instructions I easily deployed an instance in our openshift project.

Next steps:
- Modify the platform teams code using code from Steve to deploy HA PostGIS.
- Deploy ephemeral instance on every dev PR.
- Deploy persistance instance in production.
