### ISSUE TITLE
Setup SQLchemy for Predictive DB

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#296]
**Describe the task**
Learn SQLchemy and hook in to our Postgres DB

**Acceptance Criteria**
- [x] hook in SQLchemy 
- [ ] initial migration with SQLchemy (run a script and it creates the first table from a schema)

**Additional context**
- use work done for EPR
- Or here
- dummy table

**Comment by andrea-williams** [comment]
Installing psycopg2 is required for SQLAlchemy to work, however `pipenv install psycopg2` persistently fails. I found out online that a lot of people have had issues installing psycopg2 with pipenv, and the suggested workaround that was successful for me was to run `pipenv run pip install psycopg2-binary`. However, according to Psycopg2 (https://pypi.org/project/psycopg2/) the binary package is only recommended for dev and testing, not production. But I don't know how we can install psycopg2 without taking the binary route.
