### ISSUE TITLE
Postgres running in docker

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#297]
**Describe the task**
modify a docker compose to include a postgres DB 

**Acceptance Criteria**
- [x] get PostGres running in Docker
- [x] include commands in readme file
- [x] include commands in makefile

**Additional context**
- https://github.com/bcgov/epr/blob/master/docker-compose.dev.yml

**Comment by Sybrand** [comment]
Whoever does this - if you use https://hub.docker.com/r/mdillon/postgis/ - then we'll have postgis running locally.

**Comment by andrea-williams** [comment]
Although there's also this one from the official PostGis people:
[https://hub.docker.com/r/postgis/postgis](https://hub.docker.com/r/postgis/postgis)

**Comment by Sybrand** [comment]
Super sweet! Didn't know about that one!

> Although there's also this one from the official PostGis people:
> https://hub.docker.com/r/postgis/postgis
