### ISSUE TITLE
MoreCast 2.0: Wind Speed values inconsistent with SpotWx.com

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#2978]
**Actual Behaviour**

Forecasted windspeed values do not align with values for the same model and location in SpotWx.com. Wind speed in MoreCast appears to be slower than the 13:00 PDT value in SpotWx.com. 

**Steps To Reproduce**

1. Load MoreCast values for the Noel station (use the PGFC HFI station group).
2. Open SpotWx.com and enter coordinates for Noel station (55.2958, -120.4861).
3. View 13:00 PDT windspeed in Spotwx.com and compare to MoreCast for a given weather model.

**Screenshots**

**Expected Behaviour**

Values should be identical or within reasonable rounding, i.e.) one decimal place.

**Comment by conbrad** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2978?planning-poker) with Zenhub @brettedw
