### ISSUE TITLE
Research on displaying forecasted values on a graph

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#298]
**Describe the Task**
Design research on how to display some of the forecasted values on graph

**Additional Context**
- Temp and RH are covered in a different ticket
- can copy design of some of the existing tools they use
- no mock-up required, we just want enough to describe to the Devs what we are looking for

**Acceptance Criteria**
- [ ] Design research on how to display Wind Speed (10m) on a graph
- [ ] Design research on how to display Wind Direction on a graph
- [ ] Design research on how to display Precipitation on a graph 
- [ ] Design research on how to display Dew Point on a graph

**Comment by PrakritiM** [comment]
https://akff.mesowest.org/map/#/c5375,-12041,4/g1/mc/vtemp/sAK/n/zt

**Comment by PrakritiM** [comment]
SPOTWx 
https://spotwx.com/products/grib_index.php?model=gem_glb_25km&lat=50.70733&lon=-120.44621&tz=America/Vancouver
[Uploading... Screen Shot 2020-05-14 at 10.57.26 PM.png ]

**Comment by PrakritiM** [comment]
ENVIROMANT CANADA

https://weather.gc.ca/ensemble/naefs/EPSgrams_e.html

**Comment by jowand** [comment]
FORESIGHT (Victoria, Australia)

![Foresight_screenshot.JPG](https://images.zenhubusercontent.com/5e8bcddb41fb38ef37045421/d4596a61-9d2c-4241-aad2-bfd629139e7a)

**Comment by jowand** [comment]
![Foresight_screenshot2.JPG](https://images.zenhubusercontent.com/5e8bcddb41fb38ef37045421/ee80d353-cbcf-41d1-82a2-550add4935ef)

**Comment by PrakritiM** [comment]
Comparison chart:
https://miro.com/app/board/o9J_ksTKiW8=/
