### ISSUE TITLE
Morecast 2: Show error when WF1 post fails

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#2993]
**Actual Behaviour**

We show a success message when saving a forecast even when the WF1 POST fails

**Steps To Reproduce**

1. Log in to morecast2
2. Create forecast but don't save it
3. Wait 24 hours until WF1 token expires
4. Attempt to save forecast
5. Forecast doesn't show in WF1

**Screenshots**

**Expected Behaviour**

We should show an error message when the post to WF1 fails

**Comment by NicolasLivanos** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2993?planning-poker) with Zenhub @conbrad
