### ISSUE TITLE
MoreCast 2.0: Draft Forecast/Save on Browser

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#2995]
**As a** Weather Forecaster

**I need** an auto-save as draft feature for any of my in-progress forecast dates that don't yet have actuals

**So That** I can retrieve my draft forecast if my token expires and continue amending or submit to WF1. 

**Acceptance Criteria**
- [ ] Given that I have edited a forecast cell, Then a draft is auto-saved and there's a msg: "Saved Locally OR Last Saved @ XX:XX"
- [ ] Given that a draft forecast has been auto-saved but not published to WF1, When an actual weather observation exists, the draft forecast values are deleted and replaced with actual values.
- [ ] Given that I have a draft forecast auto-saved, If I want to delete it, Then there's an option to: "Reset OR Clear ALL Drafts"
- [ ] Given that I have cleared all drafts, Then values from the previously published forecast load.
- [ ] Rename the "Save Forecast" button so it is clear this button is for publishing a draft forecast to WF1.

**Additional Context**
- Day by Day forecast drafts saved
- Notification that draft forecast will expire within the day
- Cutoff time = 1 PT
- Client ID Secret pending from Vendor

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/2995?planning-poker) with Zenhub @conbrad @dgboss

**Comment by rajpersram** [comment]
Figma mockup here:
https://www.figma.com/file/0iKI82NZZtYR8UrdTMdVLD/MoreCast-2.0?type=design&node-id=337-1908&mode=design&t=B1iHaHrSeJYHtpyt-4
