### ISSUE TITLE
Dev review of STRA

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#302]
**Describe the task**
Developer review of STRA Draft and provide feedback, suggest changes/additions

**Acceptance Criteria**
- [x] STRA reviewed
- [x] recommendations added
- [ ] reviewed with PO

**Additional context**

**Comment by jakemorr** [comment]
the file is too big to add to zenhub, reach out to Jake if you pull this ticket.

**Comment by Sybrand** [comment]
Looking at the mail thread from invasivs, I'd say we need a Deployment diagram to answer some of the openshift specific questions.
I'm going to complete the HA tasks before doing that.

**Comment by jowand** [comment]
@Sybrand  and @jakemorr  I put the file on Teams - if you updated it yesterday then please replace it with the newest version.
