### ISSUE TITLE
implement website analytics for 90th percentile calc.

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#303]
**Describe the task**
implement a web analytics tool so we can start to answer questions like: What is a simple way we can measure added value of this product to the Prevention program? Number of reports printed? Number of hits to the site? 

**Acceptance Criteria**
- [x] implement web analytics with 90th percentile calculator
- [x] implement at least one metric as a trial to measure implementation of this calculator

**Additional context**
- we assume we are using matomo as we are setting it up in #393
- how is this going to affect our DB?

**Comment by jowand** [comment]
See notes from Lindsay Macfarlane attached

[https://app.zenhub.com/files/235861506/207e069f-1ab3-41a4-a033-ba73b3ae7456/download](https://app.zenhub.com/files/235861506/207e069f-1ab3-41a4-a033-ba73b3ae7456/download)

**Comment by PrakritiM** [comment]
Metabase and Snowplow (alternative platform)

**Comment by jowand** [comment]
Ideas for metrics to capture:
- Capture number of hits to the web application (can we break down by month? Will be used more in CRI Program bid applicationsend of the year/early next year)
- most used features
