### ISSUE TITLE
Security Threat Risk Assessment STRA

### ISSUE THREAD

**Issue by jowand** [bcgov/wps#306]
**Describe the task**
Complete STRA documentation below.
[https://app.zenhub.com/files/235861506/e4ea1f74-e6d7-4ed9-8a3f-e3c7b7290b9f/download](https://app.zenhub.com/files/235861506/e4ea1f74-e6d7-4ed9-8a3f-e3c7b7290b9f/download)

**Acceptance Criteria**
- Complete STRA submitted to NRM.InfoSecurity@gov.bc.ca

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by jakemorr** [comment]
Reached out to Jeff de Castro (IIT) to see if the project has an assigned security officer

**Comment by jakemorr** [comment]
Jeff De Castro is the Security Analyst

**Comment by jowand** [comment]
Jeff currently has the STRA. I've asked him to keep you in the loop as well @jakemorr
