### ISSUE TITLE
Morecast 2: Bias Adjusted Wind Direction

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#3065]
**As a** Fire Weather Forecaster

**I need** To see bias-adjusted values for wind direction for all 5 weather models (GDPS, RDPS, HRDPS, NAM, GFS)

**So That** I have more (and maybe smarter) options for data sources when making my weather forecasts

**Acceptance Criteria**
- [ ] Given I've logged in to Morecast 2.0, When the Wind Direction tab is enabled, Then the 5 columns for GDPS Bias, RDPS Bias, HRDPS BIas, NAM Bias, and GFS Bias display values for any rows where the raw model has data available

**Additional Context**
- should be able to extend existing code (I think it's called `machine_learning.py`) to add in these 3 wx variables - bias adjusted values will be calculated as part of the grib file processing script when weather model data is fetched and stored in our DB
- Green Light to remove Spatial Interpolation component
- Grib values: Linear Regression

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/3065?planning-poker) with Zenhub @dgboss @brettedw @conbrad
