### ISSUE TITLE
FireBAT: Same adjusted windspeed produces different values - Frontend

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#3066]
**Actual Behaviour**

The same adjusted wind speed input produces different critical hours.

**Steps To Reproduce**

1. On a station in FireBAT with weather data, adjust the wind speed from the default value using the up arrow
   - In the video, from 5km/hr to 10km/hr
2. After the data is loaded, make note of the critical hours result
3. Adjust the wind speed again by one, wait until data finishes loading, disregard result
4. Adjust the wind speed back to the adjusted value in step 1, note the critical hours are different compared to those in step 2

**Screenshots**

**Expected Behaviour**

The same input to FireBAT should produce the same (critical hours) output

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/3066?planning-poker) with Zenhub @brettedw @conbrad @dgboss
