### ISSUE TITLE
MoreCast 2.0: Display FWI System values

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#3081]
**Describe the task**
Display calculated FWI System values (actuals) from the WildfireOne API in the Forecast Summary tab for all previous days.

**Acceptance Criteria**
- [ ] Show FFMC, DMC, DC, ISI, BUI, FWI, DGR values (just numbers)

**Additional context**
- N/A

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/3081?planning-poker) with Zenhub @dgboss @conbrad
