### ISSUE TITLE
MoreCast 2.0: Persistence options doesn't work on Forecast Summary tab

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#3090]
**Actual Behaviour**

This bug was reported on the Sprint 84 Miro board.

Attempting to apply persistence to a weather element in the forecast summary section did not seem to work.  (worked well doing this in each of the weather tabs).

Actually, I got a bulk 'persistence' forecast to work once, on one group, but now it doesn't seem to want to work.

**Steps To Reproduce**

1. ...
2. 
3. 

**Screenshots**

**Expected Behaviour**

**Comment by brettedw** [comment]
I haven't been able to reproduce this

**Comment by brettedw** [comment]
Went through this with Jesse and it doesn't appear to be an issue anymore
