### ISSUE TITLE
Forecast Validation Questionnaire

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#311]
**Describe the task**
Reach out to other provinces to determine how other provinces assess the accuracy/validation of fire weather forecasts

**Acceptance Criteria**
- [x] Drafting an email to other provinces
- [x] Drafting a questionnaire regarding accuracy/validation of forecasts
- [x] Sending the the email and questionnaire
- [x] environmental scan of other areas methods for assessing accuracy/validation of fire weather forecasts

**Additional context**
- Jo to provide list of contacts
- Mike Smith in the Yukon: Michael.Smith@gov.yk.ca
- Bill Cole in Ontario: bill.cole@ontario.ca
- Colin McFayden: colin.mcfayden@ontario.ca
- Jerry Shields as back up in Ontario (try Bill and Colin first): Jerry.Shields@ontario.ca
- James Schofield in Alberta: james.schofield@gov.ab.ca
- Claudia Vaillancourt in Quebec: cvaillancourt@sopfeu.qc.ca

**Comment by PrakritiM** [comment]
Google spreadsheet for calculations:
https://blog.asmartbear.com/forecast.html
