### ISSUE TITLE
Display a warning header to IE(11+) users on the webpage

### ISSUE THREAD

**Issue by Kyubinhan** [bcgov/wps#313]
**Describe the task**
Display a simple header on the top stating that the page currently supports Chrome, Safari, and Firefox if users are from IE browser.

**Acceptance Criteria**
- [ ] Show a header if users visit the webpage with IE(11+)

**Additional context**
- Currently, our webpage doesn't support old IE browsers which means only thing users will see is a blank page which is not a great UX
- might be worth waiting to confirm if we have any IE users

**Comment by Sybrand** [comment]
@conbrad - agreed.
