### ISSUE TITLE
MoreCast 2.0: Implement Grass Curing

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#3139]
Review + Implement the Designs:
https://www.figma.com/file/0iKI82NZZtYR8UrdTMdVLD/MoreCast-2.0?type=design&node-id=30-42&mode=design&t=fsOwRgSB8C5zoEK0-4

task: #2914

**Acceptance Criteria**
- [x] Show GREYED (disabled but displayed) out last value that was entered in WF1 for actual rows
- [x] Prepopulate last value that was entered for forecast rows that can be changed (not greyed out)
- [x] Column will be after Precip but before the FWI in the Forecast Summary Tab
- [x] Previous dates will show WF1 data, but future dates will carry forward the last entered grass curing value. 
- [x] Grass Curing value will be stored both in WF1 and the MoreCast database
- [x] Add option to edit a cell or set as N/A

**Additional context**
-

**Comment by NicolasLivanos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/3139?planning-poker) with Zenhub @brettedw @conbrad

**Comment by conbrad** [comment]
This isn't exposed by WF1 api, so we'll revisit this when we take on SFMS
