### ISSUE TITLE
Update Sprint Review team poster

### ISSUE THREAD

**Issue by jowand** [bcgov/wps#315]
**Describe the task**
Update Sprint Review team poster to remove Derek.

**Acceptance Criteria**
- [x] poster has Ben
- [x] poster doesn't have Derek
- [x] Sy's picture is smaller than everyone else's
- [x] the whole team is displayed

**Comment by PrakritiM** [comment]
![wildfire predictive-3.jpg](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/deb550dc-3fcd-4d81-87d8-0ee1ec1584c8)


Editing link:
https://www.canva.com/design/DADxrsTnSw8/share/preview?token=uRwgEj8STrz4WaU-Vkvesg&role=EDITOR&utm_content=DADxrsTnSw8&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by PrakritiM** [comment]
[Uploading... wildfire predictive-4.pdf ]

**Comment by PrakritiM** [comment]
[https://app.zenhub.com/files/235861506/df966c00-793f-4725-a037-9f428531292b/download](https://app.zenhub.com/files/235861506/df966c00-793f-4725-a037-9f428531292b/download)
