### ISSUE TITLE
FBPGo: Set up Cloud Managed Distribution Certificate for iOS builds

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#3160]
**Describe the task**
Update expired iOS cert using Cloud Managed Distribution Certificate. Instructions in additional context below.

**Acceptance Criteria**
- [x] FBPGo for iOS can be built and released using Cloud Managed Distribution Certificate

**Additional context**
- Instructions: https://mvp.developer.gov.bc.ca/docs/default/component/mobile-developer-guide/apple_app_signing/#laptop-build

**Comment by BAAlexK** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/3160?planning-poker) with Zenhub @brettedw @conbrad @dgboss
