### ISSUE TITLE
[TASK] Migrate and build BCWS Predictive Services Rocket Chat

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/wps#32]
Build BCWS Rocket Chat space and Migrate Predictive Services Slack work space into Rocket Chat

**Comment by DerekRoberts** [comment]
@bradyholliday is this still required?

**Comment by bradyholliday** [comment]
Yes. I still want to explore this at some point. I think it is an easy feature that can bring value to our organization.

**Comment by DerekRoberts** [comment]
If we're providing our own service, then Slack sounds a lot more tempting.  It'll be nice to throw this one to the team when in hits our queue.
