### ISSUE TITLE
SPIKE: Hourly FFMC Calculations; TIMEBOX = 4 Days

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#3228]
**As a** Fire Behaviour Specialist

**I need** forecasted hourly Fine Fuel Moisture Code (FFMC) values

**So That** I can calculate expected fire behaviour over the next diurnal period and identify peak burning hours and conditions that could result in overnight burning.

**Acceptance Criteria**
- [x] This Spike is a test implementation of hourly Fine Fuel Moisture Code calculations on a tabular weather forecast for a station location obtained from MoreCast 2.0. Consider using either the the WF1 API or the hffmc function in the R cffdrs package (https://github.com/cran/cffdrs/blob/master/R/hffmc.r).  
- [x] The starting FFMC starting value for the previous hour can be obtained from WildfireOne. Make sure to specify a date within the fire season as FFMC is not calculated from November to ~May. You won't be able to pull hourly forecasts from the 2023 fire season. That's okay. Just pretend the currently available forecasts represent the fire season.
- [x] This Spike should also answer questions about code and data requirements for a spatial implementation of hourly FFMC calculations.

**Additional Context**
- Use the Van Wagner (1977) method of computing FFMC throughout the diurnal cycle: https://bcgov.sharepoint.com/:b:/r/teams/01324/Shared%20Documents/General/CFFDRS%20Documents/Van%20Wagner%20(1977)%20A%20method%20of%20computing%20fine%20fuel%20moisture%20content%20throughout%20the%20diurnal%20cycle.pdf?csf=1&web=1&e=zKH2ak
- Inputs for the Van Wagner (1977) method include a starting FFMC value for the previous hour, and forecast/actual temperature, relative humidity, wind speed, and precipitation values for the current hour. The algorithm must be run iteratively to calculate hourly FFMC values over a 24-hour period.

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by brettedw** [comment]
**Data Requirements**

- Previous FFMC
           - From WF1 if station is being calculated 
           - SFMS if calculation occurs elsewhere in the province (not at a station)

- Hourly weather forecast (temp, rh, precip, wind speed)
           - Available from some weather models (not GDPS)
           - NAM model makes predictions for every hour for the first 36 hours, and then on a 3- 
              hourly schedule to 84 hours
           - HRDPS/RDPS/GFS

- Dates/times and IDs

**Additional Info**
- CFFDRS R library provides a `calc_step` parameter for when input time intervals are not uniform in the input. Might be of use for various weather models
- CFFDRS lib can also calculate hourly ISI, FWI, and DSR. Daily BUI is required

**Comment by brettedw** [comment]
For performing this spatially, another potential option is the CFFDRS R library `hffmcRaster` function which takes takes rasterized inputs and generates raster as outputs. This option hasn't been explored yet, and I'm unsure about requirements for the rasters
