### ISSUE TITLE
Review Preparedness tools and tool pain points

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#329]
**Describe the task**
review preparedness systems/ pain points with Andrea and Brad (focus is on Tools, the information they use,  and how they use them, pain points with the tools they use)

**Acceptance Criteria**
- [x] Meet with Andrea
- [x] Meet with Brad
- [x] "how does each tool affect their decisions" answered
- [x] "how do you want to measure the success of your prep levels?" answered
- [x] create an boiled down output on the tools and pain points to share with the dev team
- [x] definition of what prep is for team what are the boundaries on this

**Comment by PrakritiM** [comment]
Andrea's chat summary

https://miro.com/app/board/o9J_ksTQpME=/
