### ISSUE TITLE
Understand and document prep workflow

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#330]
**Describe the task**
now that we understand the tools, and information they use and the pain points. To understand the workflow 
we should draft what we understand the workflow to be, and provide it to our users to correct. then next step would be to understand the users journey through the workflow.

**Acceptance Criteria**
- [x] Draft of Prep workflow (Miro)
- [x] Send workflow out to Andrea and Brad for feedback/review

**Comment by PrakritiM** [comment]
Andrea Rainey on maternity leave, point of contact until then is Darrell Johnston.

**Comment by PrakritiM** [comment]
https://miro.com/app/board/o9J_ku7DTZQ=/
