### ISSUE TITLE
SFMS: Research how to access gridded grass curing from CWFIS SPIKE: 2 days

### ISSUE THREAD

**Issue by BAAlexK** [bcgov/wps#3320]
**Describe the task**
How to access CWFIS data so we can implement the data into our tools 

**Acceptance Criteria**
- [ ] Determine how to access data (API, DL, Subset?)
- [ ] Investigate what spatial data looks like (Projection, resolution), and how it aligns with SFMS
- [ ] Determine if need account to access data
- [ ] Determine update frequency of data (how do we schedule updates, what are CWFIS update schedule)

**Additional context**
- https://cwfis.cfs.nrcan.gc.ca/home?
- Or here https://cwfis.cfs.nrcan.gc.ca/datamart?
- https://cwfis.cfs.nrcan.gc.ca/downloads/pcuring/
- https://cwfis.cfs.nrcan.gc.ca/downloads/pcuring/Percent_curing_metadata_NAP_ISO_19115_2003.pdf

**Comment by dgboss** [comment]
- WMS GetCapabilities request: https://cwfis.cfs.nrcan.gc.ca/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities&layers=public:pc_current&legend_format=image/png&feature_info_type=text/plain
- WMS is not useful to us for gridded data as values are classified buckets
- WMS service can be used for GetFeatureInfo request to get actual percent grass curing values at point locations
- Gridded data can be obtained from the Web Coverage Service with a GetGoverage request. eg. https://cwfis.cfs.nrcan.gc.ca/geoserver/public/wcs?service=WCS&version=2.0.0&request=GetCoverage&format=image/geotiff&coverageId=public:pc_current&subset=Long(-139.06,-114.03)&subset=Lat(48.3,60.0)&subsettingCRS=EPSG:4326&filename=BC_pcuring_20240124.tif
- The range of values should be 0-100, but the subsetting the coverage in EPSG:4326 gives values with a range of 0-129. I mentioned this in email communication with
