### ISSUE TITLE
MoreCast 2.0: Freeze Station and Date columns

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#3336]
**Describe the task**
Freeze the Station and Date columns in the MoreCast table so they are always visible.

**Acceptance Criteria**
- [ ] The Station and Date columns remain visible in the MoreCast table when displaying multiple tabs and scrolling all the way to the right.

**Additional context**
- Pricing https://mui.com/pricing/

Blocked by #3356

**Comment by NicolasLivanos** [comment]
https://mui.com/pricing/
