### ISSUE TITLE
1st cut at defining Prep space and PSU opportunities

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#335]
**Describe the task**
how can we compile/translate the interview & timeline work on Prep into opportunities for the team
- primary goal is to inform how we move forward as a team
- secondary is to share with stakeholders so they can see the whole prep space

**Acceptance Criteria**
- [x] get creative with how we can use the information we have gotten so far
- [x] demo-able output
- [x] determine areas where we can have the most impact on Prep

**Additional context**
- if you are stuck reach out to Jo
- we want to put a decent amount of energy/effort into this without it taking up your entire sprint

**Comment by jakemorr** [comment]
Prakriti feels this is something that needs to be created over time, being unsure o fthe end state of what is being asked.

**Comment by PrakritiM** [comment]
PDF Draft of the defining prep space:
[https://app.zenhub.com/files/235861506/5982433f-f036-455b-9f10-680e19fe9d2e/download](https://app.zenhub.com/files/235861506/5982433f-f036-455b-9f10-680e19fe9d2e/download)[https://app.zenhub.com/files/235861506/8d9fed2f-6b28-49a4-92cd-25a409dce0a0/download](https://app.zenhub.com/files/235861506/8d9fed2f-6b28-49a4-92cd-25a409dce0a0/download)[https://app.zenhub.com/files/235861506/77bc8b15-9914-476d-a172-f61caf6b8fc7/download](https://app.zenhub.com/files/235861506/77bc8b15-9914-476d-a172-f61caf6b8fc7/download)[https://app.zenhub.com/files/235861506/86b18048-ef0c-4dff-9de7-1db3ff105ea5/download](https://app.zenhub.com/files/235861506/86b18048-ef0c-4dff-9de7-1db3ff105ea5/download)[https://app.zenhub.com/files/235861506/573507d3-33a3-45ec-9f9b-a75da402fbf6/download](https://app.zenhub.com/files/235861506/573507d3-33a3-45ec-9f9b-a75da402fbf6/download)[https://app.zenhub.com/files/235861506/e1719519-ac36-4294-a177-2f66b9436ca4/download](https://app.zenhub.com/files/235861506/e1719519-ac36-4294-a177-2f66b9436ca4/download)[https://app.zenhub.com/files/235861506/53f2ffad-1238-444b-89c9-8ef16932e11b/download](https://app.zenhub.com/files/235861506/53f2ffad-1238-444b-89c9-8ef16932e11b/download)[https://app.zenhub.com/files/235861506/932cbad6-f5ca-4521-bc65-47ccf97057c1/download](https://app.zenhub.com/files/235861506/932cbad6-f5ca-4521-bc65-47ccf97057c1/download)[https://app.zenhub.com/files/235861506/3ca79bfe-b03f-4067-a98c-d4502197fa8a/download](https://app.zenhub.com/files/235861506/3ca79bfe-b03f-4067-a98c-d4502197fa8a/download)

**Comment by PrakritiM** [comment]
Draft of the defining prep space (and other tools moving forward) :
![Name of tool.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/44cd9763-9ebc-4b2b-b6f8-3866e33db30f)
![Elevator Pitch.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/912ca373-5911-4660-8c6e-c308da083979)
![Users.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/d2c8615d-d8ab-44d2-aa35-3a8a7820fe6b)
![Persona and Journey mapping.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/36bdea10-831b-4924-a042-80d17e05a392)
![Brain storming.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/cea60703-b680-4713-89ae-257a27751072)
![Details of what, how, why.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/a5699320-afb8-4ea7-a2ed-663d4d4907d9)
![Feature list and value.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/a02b94a4-0581-4b14-bb8a-3dc6bbb698c9)
![Precedent Review.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/ae63792c-a016-40c3-95b6-712b8f33eb26)
![Logo:branding .png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/8971c86f-bcdc-496c-8247-cb5dad5c4dc7)

**Comment by PrakritiM** [comment]
https://miro.com/app/board/o9J_kvf9lAQ=/

**Comment by jowand** [comment]
@PrakritiM feedback added!
