### ISSUE TITLE
RWCO Interview Prepped and booked

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#339]
**Describe the task**
user research with Regional Wildfire Coordination Officers (RWCO) regarding preparedness workflow, what decisions the make, data they are interested in and how they currently get that data

this ticket is to book the interviews and prep the questionnaire

**Acceptance Criteria**
- [x] Contact RWCO's
- [x] create questionnaire for interview

**Additional context**
- Linked with the ZWCO research
- People to Interview: Brad Litke, Dale Bojhara, Shelly Harnden, Derek Williams

**Comment by PrakritiM** [comment]
Questionnaire:
https://miro.com/app/board/o9J_ku7DTZQ=/
