### ISSUE TITLE
FBAN preparedness User research Prep

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#340]
**Describe the task**
user research with Fire Behaviour Analyst regarding preparedness products and workflow, what data they are interested in and how they currently get that data -  book interviews and create questionnaire

**Acceptance Criteria**
- [x] Contact FBAN's
- [x] create questionnaire for interview

**Additional context**
- Linked to RWCO and APL user research
- People to interview: Dana Hicks, Marc Simpson...

**Comment by PrakritiM** [comment]
Contact:
Bradley Martin, Bryan Holman(N-West)
Rory Colwell, Eric Kopetski (Cariboo)
Chris Spronken (Coastal)
Steve Levitt, Mike Morrow (South East)
Dana Hicks (Kamploops)

**Comment by PrakritiM** [comment]
https://miro.com/app/board/o9J_ku7DTZQ=/

[https://app.zenhub.com/files/235861506/0dc2ff97-0e58-4e09-a6ab-cd9f38cd4495/download](https://app.zenhub.com/files/235861506/0dc2ff97-0e58-4e09-a6ab-cd9f38cd4495/download)
