### ISSUE TITLE
Only allow deployment to production after all github actions have completed successfully.

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#344]
**Describe the task**
A developer should only be able to deploy a PR to production once all automated tests and checks have completed successfully - and the PR has been approved for deployment.

Currently it is up to the developer, to honour our deployment process (using github flow), and only deploy to production once the feature is fully developed, approved for deployment by someone, and has completed all tests successfully.

**Acceptance Criteria**
- [ ] Ability to someone flag the PR as approved for deployment.
- [ ] Developers/PO is unable to deploy to production until all checks have passed.

**Additional context**
- Maybe this could be done using deployments? https://developer.github.com/v3/repos/deployments/

**Comment by andrea-williams** [comment]
This has already been done. Closing.
