### ISSUE TITLE
SFMS: Hourly FFMC

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#3517]
**As a** Fire Behaviour Specialist
**I need** to project the FFMC hourly in the future
**So That** I can specify what times of day Fire Behaviour Advisories apply

**Acceptance Criteria**
- [ ] Given we have a SFMS grid output for the previous hour's observed Hourly Fine Fuel Moisture Code (HFFMC), when a new weather forecast arrives, then we can use this as an input to iteratively calculate HFFMC intro the future.
- [ ] The HFFMC calculations should only be applied when a weather forecast is issued at 00Z and 12Z.
- [ ] For the 00Z forecast interval, grab the 4 PM Pacific observed HFFMC as the starting condition and calculate forecasted HFMMC values at least 43 hours into the future from 00Z (or 5 PM Pacific today)
- [ ] For the 12Z forecast interval, we will grab the 4 AM Pacific observed HFFMC as the starting condition and calculate forecasted HFMMC values at least 31 hours into the future from 12Z (or 5 AM Pacific tomorrow). Overwrite/replace all previous HFFMC forecast grids since actuals and a new forecast are available.

**Additional Context**
- HFFMC Raster calculations require hour by hour grid inputs for: temperature, relative humidity, wind speed, and precipitation. A starting HFFMC grid is also required for the first calculation: https://cwfis.cfs.nrcan.gc.ca/background/summary/fwi
- The Regional weather forecast has data 48 hours into the future. If data storage is not an issue, then run the HFFMC calculations 48 hours into the future. The 43 and 31-hour acceptance criteria for 00Z and 12Z forecast intervals are the minimum requirements to ensure  there are HFFMC data for all of DAY 1 and the overnight/early morning period into DAY 2.
> - 00Z Forecast: Day 0 at 5PM + 43 hours = DAY 2 at 12 Noon
> - 12Z Forecast: Day 1 at 5AM + 31 hours = DAY 2 at 12 Noon
- Archiving & Retention Needs: everything will need to be stored + saved; Leapfrogging Policy
- We may need to produce our own actuals, given that SFMS is not producing outputs currently 

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by conbrad** [comment]
Drew up a diagram as we were discussing:
![HourlyFFMC](https://github.com/bcgov/wps/assets/1447136/95b13b5e-c771-4fc8-8ba8-9a71359fbffe)
