### ISSUE TITLE
FBAN User Journey Map

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#353]
**Describe the task**
create a user journey on Miro to highlight the successes and failures of the current prep workflow

**Acceptance Criteria**
- [x] review workflow with users to understand the cognitive energy used in each step
- [x] combine the user journeys of the FBANs onto a journey map
- [x] highlight findings (opportunities, areas that are already working well)
- [x] how their workload/tools that they use connects with MoreCast, Daily Prep (HFI calc)
- [x] how they use the SFMS, Fire Shed and other tools such as the old weatherpro tool for daily prep and operational needs
- [x] Journey map documented on Miro

**Comment by PrakritiM** [comment]
https://miro.com/app/board/o9J_ku7DTZQ=/


Point of interest:

"SFMS- Have never used/ used as an RWCO but not as a FBAN.
 
Fire Shed- Have not heard of it.
 
Old Weather Pro tool(for daily prep/operational needs)- Use as a “first filter” to identify areas, quickly, that could be in need of a Fire Behaviour Advisory. Looking at 50 stations individually is very onerous and time consuming.
 
Other tools of interest: New to Kestrel Drops, will be using it this summer for the first time."
