### ISSUE TITLE
environmental scan of UX techniques 

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#356]
**Describe the task**
explore what other teams and others in the trade are doing to unveil constraints and opportunities

**Acceptance Criteria**
- [x] reaching out to specific individuals in Govt to have a chat
- [x] highlighting 1 or 2 things other teams are doing in the UX space that could be valuable for us
- [x] researching what others in the UX trade are doing, (what are the new bleeding edge techniques)

**Comment by PrakritiM** [comment]
https://www.optimalworkshop.com

**Comment by PrakritiM** [comment]
GRAPHIC JAM https://gamestorming.com/graphic-jam/

**Comment by PrakritiM** [comment]
plus/delta feedback template
https://fhop.ucsf.edu/sites/fhop.ucsf.edu/files/custom_download/ACPS_Plus_Delta_Template.pdf

**Comment by PrakritiM** [comment]
Stake holder Interest Mapping for Mines Digital Services
![Screen Shot 2020-06-23 at 3.02.02 AM.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/5bb6912c-b4e4-4213-bbb6-6ac05d20fb59)
