### ISSUE TITLE
Handle API Server Error gracefully

### ISSUE THREAD

**Issue by Kyubinhan** [bcgov/wps#357]
**Describe the task**
Catch any exceptions and send an error response with 500 instead of failing silently and sending CORS error

**Acceptance Criteria**
- [ ] Make sure to fix this by removing the root cause

**Additional context**
- It seems that if Pydantic type was not correctly typed, then this CORS error comes up, so we can start investigating from there

**Comment by conbrad** [comment]
@Sybrand pretty sure that exception handler registered in main achieves this already.

**Comment by Sybrand** [comment]
@conbrad agreed - we've done this one, it's a duplicate.
