### ISSUE TITLE
Morecast 2.0: Grass curing not pulling from WF1

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#3573]
**Actual Behaviour**

Submitting a forecast to WF1 doesn't pull the latest grass curing in morecast

**Steps To Reproduce**

1. Go to morecast
2. Submit forecast for grass curing
3. Grass curing value does not show the latest forecasted value

**Screenshots**

**Expected Behaviour**

A submitted forecast for grass curing should show up in Morecast

**Comment by dgboss** [comment]
We don't actually store grass curing values in our API database.
- we always pull GC from WF1
- edits made and save in WF1 are reflected in Morecast when you refresh the page
- edits made in Morecast and published to WF1 are reflected when you refresh the page

The only thing I can think of is that the individual experiencing an issue has a draft forecast locally that contains their amended GC values. These values will overwrite the data coming in from WF1.

**Comment by dgboss** [comment]
The user figured out the issue on their own.
