### ISSUE TITLE
Mock-up of WFV Tool

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#366]
**Describe the task**
a mock up of the weather forecast and validation tool MVP

**Acceptance Criteria**
- [x] map for selecting multiple weather stations each with their own data
- [x] graph shows actuals, Model, and forecast (present and historical)
- [x] Table shows the same data
- [x] 3 options for an app name for the product (WFV is too much)
- [x] PO review for feedback

**Additional context**
-

**Comment by PrakritiM** [comment]
https://miro.com/app/board/o9J_ksTKiW8=/

**Comment by PrakritiM** [comment]
MoreCast it is!

![Screen Shot 2020-07-14 at 11.49.53 PM.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/713d231c-6c6d-448a-9b62-ea8239700fe6)

**Comment by PrakritiM** [comment]
Mock up
https://invis.io/N7W38PR8936
