### ISSUE TITLE
SFMS: Implement BUI gridded function for py_cffdrs

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#3662]
**Describe the task**
Accepts n `numpy` array of inputs (that will eventually be sourced from the raster) to compute and return a `numpy` array.

**Acceptance Criteria**
- [x] Reuse tests from CFFDRS R library
- [x] Use old SFMS BUI tiffs as inputs to the calculation, with faked weather inputs to sanity check
    - e.g. grab today's (dmc, dc) grids, apply BUI calculation, verify the same (similar? within a decimal place) BUI output as old SFMS' BUI
 - [ ] Use today's temp, rh, acc 24 hour precip, to calculate DMC grid, today's temp, rh to calculate DC grid, use both as inputs to calculate BUI, and again verify the same (similar? within a decimal place) BUI output against
     - static calculations
     - input grids for old SFMS BUI (request from geospatial)

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by NicolasLivanos** [comment]
![Image](https://github.com/bcgov/wps/assets/106993095/7d68ed72-7730-4dd7-adff-a802fb657f82)
