### ISSUE TITLE
Use Marvin to get hourly actuals for all weather stations

### ISSUE THREAD

**Issue by jowand** [bcgov/wps#376]
**Describe the task**
We need to add the capability to our bot to access the FireWeather website hourly to retrieve actuals data for all weather stations. (The frequency of access will depend on how often we can access the data and still be confident we will not impact the FireWeather website capacity.)

**Acceptance Criteria**
- [x] add the ability to pull actuals hourly for all weather stations 
- [x] test the bot to ensure no impact on FireWeather website (meet with Matthew Barnes)
- [x] bot runs 15 minutes after the hour (to be confirmed with Jo)

**Additional context**
- FireWeather website: https://bcfireweatherp1.nrs.gov.bc.ca/scripts/menu/BC/ShowPage.asp?page=fireweather
- we might need to create a filter to access all prep wx stations at once
- download as CSV and store in our SQL database
- to have a look at the website, all our IDIRs will work. The website was designed for explorer but may work on Firefox for Macs
- it is easier to pull all the actuals for Temp, RH, Windspeed, direction, Precip, and Dew point than to filter it down and pull less.

**Comment by jakemorr** [comment]
this is already included in a current sprint ticket but we can use this ticket to shape the next iteration of the bot, whether it be getting more fire weather forecast data (wind speed, direction etc) or adding the hourly pulls to the bot.
