### ISSUE TITLE
ASA: User configured top 3 fuels for advisories

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#3774]
**Describe the task**
Allow FBAN to configure top 3 fuels for advisories

**Acceptance Criteria**
- [ ] Given there are All Fuels that exist and available in a Zone Unit, I can select AND unselect the top 3 Fuels to include in my Advisory

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by conbrad** [comment]
Duplicate of #3745

**Comment by rajpersram** [comment]
Represented in Figma mockup: [ASA - Single Select Fire Zone with Provincial Summary](https://www.figma.com/design/YbTS5mEgXgCApFkGnZqvfj/Auto-Spatial-Advisory?node-id=1527-4333&t=8ZzhhubV54OMno3S-4)
