### ISSUE TITLE
SFMS: Calculate forecast and outlook BUI rasters

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#3775]
**Describe the task**
We want to calculate forecast and outlook BUI rasters to feed into hourly FFMC.

**Acceptance Criteria**
 - [ ] Use today's temp, rh, acc 24 hour precip, to calculate DMC grid, today's temp, rh to calculate DC grid, use both as inputs to calculate BUI, and again verify the same (similar? within a decimal place) BUI output against
     - static calculations
     - input grids for old SFMS BUI (request from geospatial)

**Additional context**
- Previous day DMC, DC, BUI comes from SFMS
- New forecast grid/values is the trigger for updating indices
- As with all indices, noon forecast values (20:00UTC) are used to push out daily indices

- Update Schedule

![Image](https://github.com/user-attachments/assets/aec039f9-8391-41e1-85c5-d2dc0da9712b)

**Comment by dgboss** [comment]
![Image](https://github.com/user-attachments/assets/5f187140-2196-44ba-a050-72e44d0d8924)
