### ISSUE TITLE
Migrate frontend build to vite

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#3785]
**Describe the task**
To speed up builds and reloading we can migrate to vite and away from crac: https://vitejs.dev/

**Acceptance Criteria**
- [x] Frontend builds and deploys with vite as the build tool
- [x] All tests pass (may require migrating from jest to vitest: https://vitest.dev/)
- [x] All code coverage from jest and cypress tests are reported to codecov still

**Additional context**
- You can take a look at a previous attempt here: https://github.com/bcgov/wps/tree/experiment/migrate-to-vite, it's missing the last AC above requiring code coverage.

**Comment by jmetev1** [comment]
(almost) all tests pass. src/features/auth/slices/authenticationSlice.test.ts

**Comment by NicolasLivanos** [comment]
@jmetev1 Thanks for everything you're doing for the BC Wildfire Predictive Services Unit.

@nealmclough and his staff really appreciate you! 

Have a great weekend!

Nicolas
