### ISSUE TITLE
ASA: Fire Center Auto-generated Advisory

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#3787]
**Describe the task**
Create a Simple, Auto-generated Advisory for a specific Zone

**Acceptance Criteria**
- [x] When I select a zone unit, I see the advisory text in a textbox, for the fire center it belongs to
- [x] The fire center dropdown populates the advisory report for the fire center
- [x] Copy the advisory date and issue date and time in the top header of the ASA page into the information panel above the advisory text
- [x] Remove the 'Combustible Land Under Advisory or Warning' infographic
- [x] Remove the FOR Date and ISSUE Date in the Header

**Additional context**
- We're not archiving any advisories text, but we already store the data that makes up the sentence
- Or here

**Comment by rajpersram** [comment]
Figma mockup example [found here](https://www.figma.com/design/YbTS5mEgXgCApFkGnZqvfj/ASA-Desktop?node-id=534-152&t=P07c3l8ObIwR5gls-4):
