### ISSUE TITLE
Bare Bones Dev Pipeline

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/wps#38]
**Describe the task**
Build a basic pipeline, documenting steps and collaborating with team to ensure knowledge-sharing.

**Acceptance Criteria**
- [x] Basic pipeline capable of deploying a Hello World-level app.
- [x] Needs to hit any Dev environment
- [x] Needs to be transparent and usable by WPS dev team
- [x] Templates created

**Comment by jakemorr** [comment]
Banana
