### ISSUE TITLE
ASA: Convert the Forecast OR Actual Dropdown to a Radio Button Group

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#3814]
**Describe the task**
Convert the Forecast OR Actual Dropdown to a Radio Button Group

**Acceptance Criteria**
- [ ]  Actual versus Forecast is selected via a radio button
- [ ] The radio button group is situated between the date selector and fire zone selector.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by rajpersram** [comment]
Illustrated in Figma: [ASA - FBA Draft 4 - MVP 1](https://www.figma.com/design/YbTS5mEgXgCApFkGnZqvfj/ASA-Desktop?node-id=534-152&t=3KlnGZTcqLW1n3VM-4)
