### ISSUE TITLE
define WFV tool value

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#382]
**Describe the task**
how can we compile/translate the interview & timeline work on Weather Forecast and Validation Tool into a deck that overviews the tool and its value to the stakeholders
- share with stakeholders so they can see the value of the tool

**Acceptance Criteria**
- [x] get creative with how we can use the information we have gotten so far
- [x] demo-able output

**Additional context**

**Comment by PrakritiM** [comment]
https://miro.com/app/board/o9J_kvf9lAQ=/
