### ISSUE TITLE
ASA: Disclaimer - About this data

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#3854]
**Describe the task**
As a FBAN, I need to see where the data comes from and how thresholds are calculated so that I can understand how the Advisories are derived.

**Acceptance Criteria**
- [x] Data disclaimer is accessible by any user viewing ASA
- [x] A discrete rolloever tooltip is present at the top right of the screen 
- [x] Content to be easily interpreted by any user ( Intermediate/Conversational Reading Level)
- [x] Remove 'Percentage of combustible land threshold' slider

**Additional context**
- Inspired from the tooltip in the top right of the [HFI calculator](https://psu.nrs.gov.bc.ca/hfi-calculator)
- 20% threshold info for Advisories needs to be mentioned (Eric K to provide exact wording)
- [Figma mockup for MVP1 for this feature found here](https://www.figma.com/design/YbTS5mEgXgCApFkGnZqvfj/ASA-Desktop?node-id=904-233&t=KaVmeW3alFa8MIQi-4).

**Comment by rajpersram** [comment]
Regarding Threshold considerations (from Eric K):

A Fire Zone is considered to be under a Fire Behaviour Advisory if greater than 20% of the combustible land (trees, grass, slash) is forecast to have a Head Fire Intensity (HFI) between 4,000 and 10,000 kilowatts per metre (kw/m).
A Fire Zone is considered to be under a Fire Behaviour Warning if greater than 20% of the combustible land is forecast to have a Head Fire Intensity greater then 10,000 kw/m.
The fuel types chosen for the text bulletin are the three most common fuel types in a zone that meet the Fire Behaviour Advisory threshold (4,000 kw/m).

**Comment by NicolasLivanos** [comment]
Revised copy from Eric: https://bcgov-my.sharepoint.com/:w:/g/personal/eric_kopetski_gov_bc_ca/Ec_OUwLKxIFEs8Uow8JeQmYBquBZ3eo-NJbSBO8-WcxoXQ?wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1724960415203&web=1
