### ISSUE TITLE
ASA: Map Tiles on Provincial Scale Not Rendering

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#3878]
**Actual Behaviour**

When opening to the Provincial Extent, the upper left + bottom right map tiles are not displaying 

**Steps To Reproduce**

1. BCWS WIN10 & Chrome Version 128.0.6613.85 (Official Build) (32-bit)
2. Opening to ASA to the Provincial extent in Forecast tab> Not all tiles are showing
3. Zoom one level down> All Tiles appear 
4. Seems to be resolved in Chrome Version 128.0.6613.114 (Official Build) (32-bit)
5. Sentry on MON AUG 26 9AM-915 (PO accessed + reported)

This issue was replicated on Sep 3, 2024 with the following steps:

1.) Open ASA with the Prince George Fire Centre selected.
2.) Set the forecast date to Aug 8, 2024
3.) Upper left quadrant of HFI tile does not appear
4.) Zoom in/out and the HFI tile appears
5.) Zoom back to default zoom level and the HFI tile does not display in the upper left quadrant.

 **Screenshots**

![Image](https://github.com/user-attachments/assets/16fe076b-81a9-4746-8922-a996fe126b69)

**Expected Behaviour**

The entire map tile should load regardless of the zoom level

**Comment by conbrad** [comment]
It looks like this is a deep Chromium bug on Windows and the workaround suggested by PMTiles maintainers are to disable the cache: https://github.com/protomaps/PMTiles/issues/445#issuecomment-2350830976

Chromium bug: https://issues.chromium.org/issues/40542704

**Comment by NicolasLivanos** [comment]
Thanks for looking into this, Conor!

Regards,

Nicolas Livanos
Sr. Scrum Master
***@***.***<https://certification.scrumalliance.org/accounts/1439478-nicolas-livanos/certifications/1737636-advcsm>
Natural Resource Information & Digital Services
Ministry of Water, Land and Resource Stewardship
Decision Support Tools | BCWS PSU (gov.bc.ca)<https://psu.nrs.gov.bc.ca/>

All my relations to the Syilx Okanagan People for their hospitality and tolerance on their Traditional, Ancestral, Unceded, and Transnational Territories

**Comment by conbrad** [comment]
Looks like one of the maintainers is actively working on a branch to allow us to configure no caching for pmtiles on windows: https://github.com/protomaps/PMTiles/commit/5bc651d2a86f4007a11d005b3ec59a008acdcd1e

I imagine their next release may contain the fix for this.
