### ISSUE TITLE
Innovation: Generate values threatened details

### ISSUE THREAD

**Issue by conbrad** [bcgov/wps#3906]
**As an** FBAN

**I need** a way to generates values threatened on a specific date based on active heat, forecasted weather and spread criteria

**So That** I can see which values are at risk for a given day to inform preparation and triage.

**Acceptance Criteria**
would use those indices
- [ ] #3937
- [ ] #3938
- [ ] #3942
- [ ] #3941
- [ ] #3940

**Additional Context**
- Minimal end user product could be a date picker and a button to generate values on a given future date
- Current local script is here: https://github.com/emillan-gov/gis-pantry/blob/master/recipes/Wildfire_Values_Mapping/main.py
- See email thread for more details
- Concept diagram:
![Image](https://github.com/user-attachments/assets/8c4d24dc-44e6-4f64-875b-9979fe5d9e43)

**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by conbrad** [comment]
Provide way to allow user to enter values, drawing on map? Inputting geojson, kml, shapefiles.

**Comment by conbrad** [comment]
MODIS values are hotspots within or around a fire perimeter, looks like the data is available here: https://firms.modaps.eosdis.nasa.gov/usfs/active_fire/

**Comment by nealmcloughlin** [comment]
Yes, you can register for a Map Key using the link above which allows you to access active fire detection data using a WFS or API call. You can access current fire perimeters from the BC Geo Warehouse here: 
https://catalogue.data.gov.bc.ca/dataset/bc-wildfire-fire-perimeters-current

The WFS is not advertised, but you can access it using the WMS getCapabilities URL, but change the "WMS" to "WFS".

**Comment by NicolasLivanos** [comment]
Q: Heuristics Rules vs How the system works and enable this app to be used in any part of the Province
