### ISSUE TITLE
plan to get qualitative feedback from users

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#394]
**Describe the task**
we need a plan to get qualitative feedback from actual users who have used our 90th percentile calculator to help them create funding proposals, we also want to get qualitative feedback from the people who currently review those proposals and use the calculator to confirm the values

**Acceptance Criteria**
- [x] plan for engagement
- [x] questions to be asked
- [x] list of contacts (people who have already used the app)
- [x] where/how we will capture this information (quotes, who said it, were they staff or industry members, nature of the quote (good/bad)

**Additional context**
- contacts could be acquired by contacting the wildfire prevention officers in each of the fire centres (Matthew Lees - Caribou, Jo to provide more contacts)
- Dana has asked many users to provide feedback, so reaching out to him should provide as a good starting point

**Comment by jakemorr** [comment]
@jowand please update contacts

**Comment by PrakritiM** [comment]
Hi,


I am the User Experience Researcher on the Predictive Services Agile Software development team that is building intelligence products related to fire weather and fire behaviour. I may have reached out to you earlier regarding your needs while we were building the 90th Percentile calculator software.
 As we have now built the software, we want to keep all users in mind and would love subject matter experts as yourself to give us your honest feedback on how it has or has not helped to streamline your process.

Here’s the link to the calculator:
https://wps-web-prod.pathfinder.gov.bc.ca/percentile-calculator/


And here’s the link to the survey:
https://www.surveymonkey.com/r/WZGFZGF
   
     The survey session should take about 10 mins.
     
    
    Feel free to ask questions anytime and reach out if you have any additional comments/concerns.
   
    Talk soon,
   Cheers,
    Prak.

**Comment by PrakritiM** [comment]
Contacts shared by Brady/Dana during research:
Consultant-
Tove : tove.pashkowski@gmail.com

BCWS:
Rainey, Andrea FLNR:EX Andrea.Rainey@gov.bc.ca;
Irvine, Shannon FLNR:EX Shannon.Irvine@gov.bc.ca;
Duncan, Jessica FLNR:EX Jessica.Duncan@gov.bc.ca

**Comment by PrakritiM** [comment]
Jo Shared:
Internal staff (Wildfire Prevention Officers):
Andrea Rainey (on mat leave but email her and see what her auto reply says)
Shannon Irvine
Matt Lees
Steve Richburg
Mike Morrow
Michael Aldred
Tony Botica

External staff (but still within the Prevention program):
Reg Nolander (Mountain Resorts Branch) Reg.Nolander@gov.bc.ca
Lindsay Vandersteeg (BC Parks - she will probably forward to an appropriate person) Lindsay.Vandesteeg@gov.bc.ca

Contractors: (hold on this one while I ask around - it is probably best to ask the WPOs to see if they can nominate a contractor for us to contact)
