### ISSUE TITLE
ASA Hashing

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#3963]
**Implement the Red & Orange Hashing for Advisories**

Acceptance Criteria
- [x] No Advisory = No Hashing
- [x] Warning = Red Hashing
- [x] Advisory = Orange Hashing
- [x] Hashing persists irrespective of open or not dropdown

**Comment by rajpersram** [comment]
Refer to Figma ASA 14D, T, and M mockups [found here](https://www.figma.com/design/YbTS5mEgXgCApFkGnZqvfj/ASA-Desktop?node-id=1056-1721&t=BdZLFMo5FMaM14gf-4).
