### ISSUE TITLE
Request more space for DB Back Up

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#397]
**Describe the task**
establish a reasonable size requirement for our backup disk and proceed with requesting it

**Acceptance Criteria**
- [ ] determine who we request space from
- [ ] submit a request for additional back up space

**Additional context**
- "If you're managing your storage appropriately, and can fit all your needs into the 200Gi quota, you should have no issues.
Backup quotas are a trickier beast (for OCP3) as the implementation of that storage is NOT highly available, so we like to see your operational design before we increase that specific quota to double check that you're not creating an unexpected dependency that may cause issues later. Once you can show your application has a reliable backup operation in place, it's not generally an issue to bump that up. This restriction will be going away with the OCP4 implementation as we have been able to integrate the enterprise backups directly into the storage service." -Jeff Kelly

**Comment by Sybrand** [comment]
I'm not going to pick up this ticket, I don't want to be a contact point since I'm going to be out of the game for much of the month. Anyone can pick up this ticket (don't have to be technical - we're looking at having increase our backup allocation from 5GB to - I would say, a nice round 150GB.
