### ISSUE TITLE
Notification if DB is low on space (2GB)

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#408]
**Describe the task**
If the database is running out of space a mechanism to alert maintainers is required.

**Acceptance Criteria**

- [ ] OpenShift health check for patroni database that disk space is low
- [ ] notifies maintainers if database is low on space (less than 2GB available)

**Additional context**
- consider low space to mean theres enough time for us to increase disk space for DB in the next sprint

**Comment by Sybrand** [comment]
Remember to update global config - let's check if our template is up to date.
