### ISSUE TITLE
[ADMIN] PIA and STRA

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/wps#41]
Complete PIA and STRA for Predicitive Services project including Weather Phase 3
Narrow scope to just weather calculator

- [x] Invite Pawan to Alignment Session
- [ ] Fill out PIA Template (Word Document)
- [ ] Fill out STRA Intake (PDF)
- [ ] Identify technical advisor for Predicitive Services (Agile Team)
- [ ] Touch base with Kevin H, Tech adv for WxPh 3)
- [ ] Review WxPh3 PIA from 2016

**Comment by jowand** [comment]
@jakemorr is it one STRA for the entire suit of products or one per product? It looks like it depends if they are all using the same platform or not? I'm going to turn this into two tickets: PIA and STRA.
