### ISSUE TITLE
Refactor out pytz

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#411]
**Describe the task**
There's been some use of pytz in the code to set timezone utc on dates - it's inclusion in the project is redundant as the same functionality can be achieved using pythons datetime.timezone.

**Acceptance Criteria**
- [ ] no reference to pytz in our code
- [ ] pytz not referenced in pyproject.toml

**Additional context**
- This is not to say we might not need pytz at some point in the future, but if we don't need a library, rather leave it out.
- "With the addition of the zoneinfo module in Python 3.9 (PEP 615), there has never been a better time to migrate away from pytz." : from https://pypi.org/project/pytz-deprecation-shim/

**Comment by conbrad** [comment]
Found it is only included as a dependency for the Babel package we use.
