### ISSUE TITLE
Validate interpolation method

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#412]
Describe the Task:
we want to validate our interpolation method with forecasters

**Additional Context**
- interpolation is using degrees and not using distance, not sure if this matters
- The crux of the matter is this: We're currently doing linear interpolate between grid points to establish values for a station. HOWEVER - I don't know that we're interpolating correctly - will taking geographic coordinates and interpolating, without taking into account projection work?  Or do we need to take in account the some other fancy things?
- using lat long gets more inaccuarate the farther north the spot is

e.g.: if we have point top_left, top_right, bottom_right, bottom_left - it may be (I don't have the gis knowledge) that the distance between top_left and top right, isn't the same as bottom_left and bottom_right because how how things get projected. I simply don't know if that's an issue when interpolating for some point within those bounds.

**Acceptance Criteria**
- [ ] Meet with the Forecasters/someone who is an expert in Mapping and GIS 
- [ ] we are interpolating correctly or we know what we need to change

**Comment by jakemorr** [comment]
@jowand basically we want to ask the forecasters this to see if we can be interpolating more correctly

**Comment by jowand** [comment]
@jakemorr  and @Sybrand I have a feeling the forecaster response will be "it's more complicated than interpolation". So let's be ready for that and see if we can tease out some more useful information.
