### ISSUE TITLE
Display Weather Stations on a Map

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#415]
**As a** *(User Type/Persona)* **I want** *see the weather stations in their location on a map* **So That** *I can select weather stations relevant to the location I am analyzing*

**Additional Context**
- Layer with BC data warehouse that has weather stations: https://catalogue.data.gov.bc.ca/dataset/bc-wildfire-active-weather-stations

**Acceptance Criteria**
- [ ] Given I am looking at a map, When I look at a given weather station , Then I can identify which weather station it is

**Comment by Sybrand** [comment]
If we modify our stations endpoint (https://wps-api-prod.pathfinder.gov.bc.ca/stations/) to return geojson - we could load our dropdown and stations in one call. (Just an idea - might not be practical)
