### ISSUE TITLE
Update our patroni instance with latest updates from the devops/platform

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#438]
**Describe the task**
The devops/platform team has updated some of their patroni code (docker and openshift templates) - we should incorporate those latest changes. (Notably upgrade to postgres:12)

**Acceptance Criteria**
- [x] Upgrade to match postgresql version. (version 12)
- [x] Update dockerfile as needed.
- [x] Update templates as needed.

**Additional context**
-

**Comment by jakemorr** [comment]
"- most current version of Postgres is v.13 (released Sept 2020). We're using v10.14
- BC devops/Platform Service's [https://github.com/bcgov/patroni-postgres-container](Patroni-postgres-container) (which we use) is now based on Postgres v12.4, so we should aim to update to Postgres 12, not 11
- from Postgres docs: migration to version 11: A dump/restore using pg_dumpall or use of pg_upgrade or logical replication is required for those wishing to migrate data from any previous release.
- doesn't appear to be any breaking changes between versions 10 and 11
- from Postgres docs: migration to version 12: A dump/restore using pg_dumpall or use of pg_upgrade or logical replication is required for those wishing to migrate data from any previous release.
- noteworthy change in Postgres 12:
  - Refactor code for geometric functions and operators (Emre Hasegeli)
    This could lead to more accurate, but slightly different, results compared to previous releases. Notably, cases involving NaN, underflow, overflow, and division by zero are handled more consistently than before.

It doesn't appear to be a requirement to do incremental upgrades - i.e., we should be able to upgrade from version 10 directly to version 12."

- Andrea
