### ISSUE TITLE
research postgres upgrade

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#439]
**Describe the task**
research if there are any significant amount of work upgrading from PostGres 10 and 11

**Acceptance Criteria**
- [ ] Ensure upgrading from 10 to 11 is relatively easy

**Comment by andrea-williams** [comment]
- most current version of Postgres is v.13 (released Sept 2020). We're using v10.14
- BC devops/Platform Service's [https://github.com/bcgov/patroni-postgres-container](Patroni-postgres-container) (which we use) is now based on Postgres v12.4, so we should aim to update to Postgres 12, not 11
- from Postgres docs: migration to version 11: A dump/restore using pg_dumpall or use of pg_upgrade or logical replication is required for those wishing to migrate data from any previous release.
- doesn't appear to be any breaking changes between versions 10 and 11
- from Postgres docs: migration to version 12: A dump/restore using pg_dumpall or use of pg_upgrade or logical replication is required for those wishing to migrate data from any previous release.
- noteworthy change in Postgres 12:
  - Refactor code for geometric functions and operators (Emre Hasegeli)
    This could lead to more accurate, but slightly different, results compared to previous releases. Notably, cases involving NaN, underflow, overflow, and division by zero are handled more consistently than before.

It doesn't appear to be a requirement to do incremental upgrades - i.e., we should be able to upgrade from version 10 directly to version 12.
