### ISSUE TITLE
use Machine Learning to determine likely fire locations in 2020 using 2019 data

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#482]
**Most likely fire locations in 2020 as lat long according to Roberto Roboto (Andrea's Machine learning bot) using data up to and including 2019**

**Additional Context**
- BC Data Catalog Fire Incident locations
- lat/long, date, cause of fire, shape of the burn space, size of burn, etc.
- try to determine where future fires will be
- BC data catalog has HFI Dataset (Dana Hicks)
- Most likely fire locations in 2020 as lat long according to Roberto Roboto (Andrea's Machine learning bot)using data up to and including 2019

**Acceptance Criteria**
- [ ] a grid system and a probability of a fire occurring in a given grid

**next steps:**
- find another weather data set that overlaps with the fire data to incorporate
- plug numbers into a map display
- do it all for 2021

**Comment by ashlinrichardson** [comment]
Ooh @jakemorr I like this one!!!!!!!!

**Comment by andrea-williams** [comment]
Notes to self - to do list:
[ ] split into training set (-2017) and test dataset (2018-2019)
[ ] split province into grid
[ ] add fire incident data from training set into appropriate square of grid
[ ] train machine (neural net?) using training dataset
[ ] use machine to output predicted fire probabilities for 2018-2019
[ ] compare machine's predictions against test dataset - higher probability grids should generally equate to more frequent fires in 2018-2019 actuals
