### ISSUE TITLE
Display weather model temperature layer form Env Canada using a mapping tool

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#483]
**Display weather model temperature layer using a mapping tool and create UI interaction for them**

**Additional Context**
- IIT Web mapping frameworks is available but don't be beholden to it https://bcgov.github.io/BCWebMaps-Options/
- Weather stations layer: https://catalogue.data.gov.bc.ca/dataset/bc-wildfire-active-weather-stations
- https://www.canada.ca/en/environment-climate-change/services/weather-general-tools-resources/weather-tools-specialized-data/geospatial-web-services.html
- https://eccc-msc.github.io/open-data/usage/tutorial_web-maps_en/

**Acceptance Criteria**
- [ ] a map with visualization of the weather model for temperature

**Next Steps**
- toggle other layers (RH)
- display weather stations

**Comment by Kyubinhan** [comment]
Was able to render a map with the temperature layer using the Leaflet library
