### ISSUE TITLE
Wire in data with Redux to Storybook

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#491]
**Describe the task**
this task will allow devs to render the entire application in storybook instead of just a component

**Acceptance Criteria**
- [ ] Create a 'Storybook Story' for the whole MoreCast web page
- [ ] Create mock data for Redux state

**Additional context**
- https://www.learnstorybook.com/intro-to-storybook/react/en/data/

**Comment by Kyubinhan** [comment]
Decided this is not the way we want to go. Instead of adding redux into Storybook, we are going to decouple our components from Redux. And write Storybook stories for these decoupled ones.
