### ISSUE TITLE
Slide Bar for the Graph

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#492]
**Describe the task**
**As Hagrid**, **I want** the ability to slide through the time range on the graph **So That** the data is not too condensed when historical and future toggles are active

**Acceptance Criteria**
- [ ] when looking at the graph a slide bar is on the bottom
- [ ] when looking at the graph with both future and historical toggles active the graph does not condense but rather allows you to slide to other parts of it

**Additional context**
- zoom level is fixed

**Comment by andrea-williams** [comment]
This repo [https://github.com/bcgov/air-monitoring-visualization](https://github.com/bcgov/air-monitoring-visualization) contains the source code for this super cool graph scroll bar [http://www.env.gov.bc.ca/epd/bcairquality/data/station.html?id=E231866](http://www.env.gov.bc.ca/epd/bcairquality/data/station.html?id=E231866)
