### ISSUE TITLE
Select Weather Stations using Map and Lasso

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#503]
**As a** *Hagrid* **I want** *to select the weather stations using a Lasso* **So That** *I can easily select relevant stations without referencing another site*

**Additional Context**
- this is the work to implement Kyubin's Experimentation on the map.
- do not remove the station dropdown allow the option
- limit on amount of stations that can be selected will be established in previous ticket

**Acceptance Criteria**
- [ ] Given I am on MoreCast and looking to select a group of weather stations, When I select the lasso tool and drag a loop around some stations, Then those stations are selected for MoreCast to display the graphs and data
- [ ] Given I am on MoreCast and looking to select a group of weather stations, When I select the lasso tool and drag a loop around no stations, Then no stations are selected

**Comment by Sybrand** [comment]
For OpenLayers - this could be a starting point: https://openlayers.org/en/latest/examples/tracing.html
