### ISSUE TITLE
Clean up Model Run Predictions in Prod DB

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#514]
**Describe the task**
Production DB seems to contain some invalid data. For example, the `prediction_model_grid_subsets` table has grid polygons defined only with latitude coordinates (longs are missing). There are also rows in the `model_run_grid_subset_predictions` table that have FK references to the invalid `prediction_model_grid_subsets` rows.

Not a super high priority issue but it means that we're storing useless data in our DB, and given our storage shortage, deleting the useless data could help create more space.

**Acceptance Criteria**
- [ ] Delete all invalid data from prod DB
- [ ] Maintain all valid data in DB

**Additional context**
- Deleting rows from a prod DB is SCARY!

**Comment by conbrad** [comment]
Table not used anymore
