### ISSUE TITLE
MoreCast Demo for Executive Leadership - **cancelled pending reschedule**

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#516]
**Describe the task**
we want to tailor a demo for the exec leadership group. we are unsure what the time we will get is, and what the audience will look like at this point but we will need to smooth out out demo for that audience (less technical, more value focused)

**Acceptance Criteria**
- [x] Book Demo
- [ ] Demo Product
- [ ] walkthrough of our next steps with MoreCast
- [ ] walkthrough of our next steps with a Prep calc

**Additional context**
- looking for the demo to take place Sprint 18

**Comment by jakemorr** [comment]
request is in for either the 29th or following week, waiting to hear back.

**Comment by jowand** [comment]
Power point is ready and in the Teams 'files'

**Comment by jowand** [comment]
Date locked in for the 29th Oct

**Comment by jowand** [comment]
Date moved to Nov 2.
Jo presenting and Bob supporting.

**Comment by jakemorr** [comment]
using monthly updates to fulfill the need to demo to
