### ISSUE TITLE
Determine which Fire centre will serve as our "base" 

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#522]
**Describe the task**
need to meet with FBANs for stakeholders to determine which fire center we should base the MVP of the HFI Calc tool on, from there we can then determine the different needs of other fire centres and add them as features.

**Acceptance Criteria**
- [x] first
- [x] second
- [x] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by jowand** [comment]
Kamploops is the 'chosen' one
