### ISSUE TITLE
Analytics for Morecast using Matomo

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#533]
**Describe the task**
implement a web analytics tool so we can start to answer questions like: What is a simple way we can measure added value of this product to the Prevention program? Number of reports printed? Number of hits to the site? 

**Acceptance Criteria**
- [ ] implement web analytics with MoreCast
- [ ] implement at least one metric as a trial to measure implementation of this calculator

**Additional context**
- we assume we are using matomo as we are setting it up in #393
- how is this going to affect our DB?

**Comment by jowand** [comment]
Have a look at MoreCast Phase 3 for questions we are trying to answer by using Matomo:
https://miro.com/app/board/o9J_kwtmuro=/
