### ISSUE TITLE
Submit a request for specialised/custom web property

### ISSUE THREAD

**Issue by jowand** [bcgov/wps#543]
**Describe the task**
To link with Incident Manager, we will need MoreCast to have URL that won't change as OpenShift is upgraded. Ideally, we will have a URL that we can nest future products under:

https://psu.nrs.gov.bc.ca/

**Acceptance Criteria**
- [x] Jo to fill out form to: 
    https://www2.gov.bc.ca/gov/content/governments/services-for-government/service-experience-digital-delivery/digital-delivery/web-property-process/web-property-applications

https://apps.nrs.gov.bc.ca/int/confluence/display/DEVGUILD/gov.bc.ca+URLs

- [ ] Dev to review form if needed
- [ ] Jo to attain approval from ministry senior executive/project sponsor and your GCPE Ministry Communications Shop representative
- [ ] Jo to submit form
- [ ] let Paul Pilon from Incident Manager know when complete

**Comment by Sybrand** [comment]
@jowand just edited it to say "can nest future products under:
https://psu.gov.bc.ca/" instead of "https://psu.gov.bc.ca/"

**Comment by jowand** [comment]
had a crack, in need of dev help:
[https://app.zenhub.com/files/235861506/380dcdea-b39f-4d26-87b2-e5991153f8f2/download](https://app.zenhub.com/files/235861506/380dcdea-b39f-4d26-87b2-e5991153f8f2/download)

**Comment by andrea-williams** [comment]
route request logged on Jira: https://apps.nrs.gov.bc.ca/int/jira/browse/INFRA-12089
