### ISSUE TITLE
Check in with early access teams on the switch to OpenShift 4

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#546]
**Describe the task**
we want to reach out to the teams with early access to OS4 to see if there are any known complications, issues, or instructions on how to make the switch so we can better estimate the work and be prepared to do it when the time comes.

**Acceptance Criteria**
- [x] find out which teams have early access
- [ ] reach out to meet with each teams devs (if necessary, meet with 1 team minimum)
- [ ] document the takeaways and create tickets if necessary 

**Additional context**
- Platform services will know which teams have early access

**Comment by Sybrand** [comment]
Reaching to Kuan is a good idea.
