### ISSUE TITLE
Update Storybook and Create-React-App library versions in Frontend

### ISSUE THREAD

**Issue by Kyubinhan** [bcgov/wps#570]
**Describe the task**
Storybook has released version 6 (we are currently using 5.3.19) with some breaking changes and Create-React-App released version 4 (we are using 3.4). Since these are essential dependencies to our project, let's update them!

**Acceptance Criteria**
- [ ] Update Storybook to version 6
- [ ] Update CRA to version 4

**Additional context**
- Here is a migration guide for Storybook https://storybook.js.org/blog/storybook-6-migration-guide/
- Or here

**Comment by jowand** [comment]
@jakemorr we re-estimated this ticket as a 2 (was 1)
