### ISSUE TITLE
Make actuals more prominent in Temp/RH graphics

### ISSUE THREAD

**Issue by jowand** [bcgov/wps#576]
**As a** *Hagrid* **I want** *the actuals to be more prominent* **So That** *I can see them easier in graphics*

**Additional Context**
- actuals are the most important data

**Acceptance Criteria**
- [ ] Given I am looking at the Temp/RH graph in MoreCast, Then the actuals are the clearest data on the graph
- [ ] drop screenshot of prototype in weather channel for Jesse, Brett, and Matt to see and ask them what would make it stand out more.

**Comment by Kyubinhan** [comment]
Some ideas on displaying lines
https://datawanderings.com/2019/11/01/tutorial-making-an-interactive-line-chart-in-d3-js-v-5/
