### ISSUE TITLE
Basic Uptime Tracking

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/wps#58]
**Describe the task**
Basic uptime tracking for our first deliverable.

**Expected behaviour**
Probably a quick monitoring and rights setup of Uptime Robot or a similar service.

**Acceptance Criteria**
- [x] Sybrand and Derek are notified by uptime robot when the site is down
- [x] anyone on the team can check the uptime robot site to see uptime info

**Comment by Sybrand** [comment]
- Is this something we need right away?
- Does this ticket include an ability to report on uptime (e.g. pull reports to establish uptime percentage or report on downtime instances)
- Does this include notifications that the site is down?

**Comment by DerekRoberts** [comment]
@Sybrand 
- Not useful until we have something deployed and semi-stable
- Yes, although not specified
- Yes, although not specified
