### ISSUE TITLE
[STORY] Display Web Disclaimer

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#59]
**As Provincial Government I want a Disclaimer on the Web side of the Application so that we are protected against any lawsuits based on the information in the application and its use.**

**Acceptance Criteria:**
- When anyone opens or navigates to the 90th percentile calculator application they are presented with a disclaimer with some messaging about the precision of the calculator and its use

- when someone closes the disclaimer by clicking on an accept button, they are presented with the 90th percentile calculator

- Displaying a draft version of the disclaimer is acceptable in order to complete this story

- Access to the calculator is blocked until the user clicks on the accept button.

- Disclaimer is shown every time a user opens the page. (The intention of this criteria is to simplify the development by removing any concern to managing state).

**Related**
- Content for disclaimer to be provided

**Comment by PrakritiM** [comment]
wireframe of the disclaimer:

https://invis.io/N7W38PR8936#/406095733_1

**Comment by Kyubinhan** [comment]
@bradyholliday do we have the wording ready to use?

**Comment by Sybrand** [comment]
Disclaimer
Warranty Disclaimer
This 90th Percentile Forest Fire Weather Index (FWI) system software and related documentation is provided as a public service by the Government of British Columbia, Box 9411, Victoria, British Columbia, Canada V8W 9V1.
This 90th Percentile Forest Fire Weather Index (FWI) system software and related documentation are provided "as is" without warranty of any kind, whether express or implied. Users of this software and documentation do so at their own risk. All implied warranties, including, without limitation, implied warranties of merchantability, fitness for a particular purpose, and non-infringement, are hereby expressly disclaimed. Links and references to any other websites or software are provided for information only and listing shall not be taken as endorsement of any kind. The Government of British Columbia is not responsible for the content or reliability of any linked software and websites and does not endorse the content, products, services or views expressed within them.
It is the responsibility of all persons who use 90th Percentile Forest Fire Weather Index (FWI) system software and related documentation to independently confirm the accuracy of the data, information, or results obtained through their use.
Limitation of Liabilities
Under no circumstances will the Government of British Columbia be liable to any person or business entity for any direct, indirect, special, incidental, consequential, or other damages based on any use of this software and documentation or any other software to which this site is linked, including, without limitation, any lost profits, business interruption, or loss of programs or information, even if the Government of British Columbia has been specifically advised of the possibility of such damages.

**Comment by Kyubinhan** [comment]
Done. The change can be found here
https://wps-web-pr-42.pathfinder.gov.bc.ca/
