### ISSUE TITLE
"Expected length, "NaN"" console error messages in prod

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#608]
**Describe the Bug**
There's d3-related error messages appearing in the console for TempRH graph, related to the models summary slices.

**Expected Behaviour**
No console error messages.

**Actual Behaviour**
Console error messages. See screenshot.

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to Morecast and select any station
2. Open up the Console tab in Developer Tools
3. See error:
```
<line> attribute x1: Expected length, "NaN".
<line> attribute x2: Expected length, "NaN".
<text> attribute x: Expected length, "NaN".
```

These 3 error messages will appear immediately when you try to load the Morecast page, but will sometimes also appear again (so that there's 6+ error messages), based on user activity that I haven't been able to identify.

**Screenshots**
![Screen Shot 2020-12-08 at 3.26.49 PM.png](https://images.zenhubusercontent.com/5e331ea54a0d32f8650c9a25/8088abca-6726-410a-ace3-25527694d2b3)

**Comment by Kyubinhan** [comment]
I actually fixed this issue in my current PR, but good catch!
