### ISSUE TITLE
Weather Station Dropdown

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#61]
**As a Consultant or BCWS Staff member I want to select 1 to 3 weather stations so that I can get data relevant to the location I am surveying/application I am reviewing**

**Acceptance Criteria:**

- [x] when the user selects the weather stations they are displayed as the user uses different parts of the application
- [x] If the user tries to calculate without selecting weather stations they are informed they must select at least 1 weather station
- [x] user can see the station name and code in the dropdown.

**Comment by Sybrand** [comment]
After chatting with @bradyholliday , I've added that the station name and station code must be visible as acceptance critery. Brady mentioned he'd like to see it in the format "Name(code)" e.g. "ASHNOLA(331)".

TAKE NOTE OF THE DIFFERENCE BETWEEN A **code** and an **id** when dealing with weather stations.

**Comment by bradyholliday** [comment]
@Sybrand for the MVP are we just building a drop down box with a long list of all the available weather stations? Based on what is being done I will look at the need for an additional user story to be able to search and filter in order to find the desired station(s) easier.

**Comment by Sybrand** [comment]
@bradyholliday yep - mvp is going to be a normal dropdown. There are a number of easy ways to make it better, so we should certainly iterate on that.

**Comment by Kyubinhan** [comment]
@bradyholliday I actually implemented a searchable dropdown because it was fairly easy to do and I wasn't aware of this conversation 😅

**Comment by Sybrand** [comment]
From Dana: "archived stations in the database are denoted by “ZZ” and anything that has a “QD” at the end is a quick deploy station that is placed for short term work. Neither of these types of station need to be included in this work"

**Comment by Kyubinhan** [comment]
@bradyholliday we need your feedback on this acceptance criteria 
`If the user tries to calculate without selecting weather stations they are informed they must select at least 1 weather station`

Can we instead disable the calculate button when there is no weather stations selected?

**Comment by bradyholliday** [comment]
Yes that will work.

Sent from Workspace ONE Boxer

On Feb. 26, 2020 12:26 p.m., Kyubinhan <notifications@github.com> wrote:

@bradyholliday<https://github.com/bradyholliday> we need your feedback on this acceptance criteria
If the user tries to calculate without selecting weather stations they are informed they must select at least 1 weather station

Can we instead disable the calculate button when there is no weather stations selected?

-
