### ISSUE TITLE
Get rid of alchemy-mock

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#651]
**Describe the task**
Using alchemy-mock, in retrospect, was a bad idea. Rather just mock out the crud calls.

**Acceptance Criteria**
- [ ] alchemy-mock removed as dependency.
- [ ] tests mock out crud calls instead.

**Additional context**
- Having a mocked out database, that doesn't behave the same way a real database does, doesn't actually help much - and actually causes some confusion. Rather get rid of it as a dependency, and just mocked out calls to the crud layer.

**Comment by conbrad** [comment]
No uses of alchemy-mock anymore
