### ISSUE TITLE
Large backups becoming impractical

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#654]
**Describe the task**
We need to figure out how to manage our data by either
- Using differential backups
- Warehouse old data
- Something else

**Acceptance Criteria**
- [ ] Investigate, and decide on solution.

**Additional context**
- Examples of differential backups: https://pgbackrest.org/ or https://www.pgbarman.org/
- As of Jan 2021, backups are taking in excess of 15 minutes to complete:
```
Backup written to /backups/daily/2021-01-04/patroni-leader-wps-prod-wps-prod_2021-01-04_03-00-11.sql.gz.
Database Size: 7856 MB
Backup Size: 2.0G

Elapsed time: 0h:15m:27s - Status Code: 0
```

**Comment by conbrad** [comment]
Is this still an issue with s3 backups?

**Comment by Sybrand** [comment]
Doesn't seem to be an issue any more. We could probably close this.

Some time ago I gave the backup process a lot more CPU (the gzip took a lot of time) and that seemed to resolve it.
