### ISSUE TITLE
App Skeleton

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/wps#69]
**Describe the task**
App skeleton for the Front end and skeleton for the back-end, provided to be run and have a process that exists in a docker container
**Acceptance Criteria**
- [x] it runs in the docker container
- [x] sufficiently documented for hand-off to Derek/other Dev-ops team members
- [x] team members agree on the skeleton
- [x]  simple as possible (Agile principle 11)

**Comment by jakemorr** [comment]
Tomato

**Comment by DerekRoberts** [comment]
@Kyubinhan @Nkuruba Please state which repos and branches (hopefully master) are to be consumed by the pipelines.  wps-web/master is almost done.
