### ISSUE TITLE
Updating our Team Graphic

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#692]
**Describe the task**
Update the Team graphic to include Ambrose, and Eric

**Acceptance Criteria**
- [x] remove former team members
- [x] add new ones
- [x] replace on miro for the next sprint review

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ambroseyau** [comment]
Team Graphic Poster has now been updated:
https://miro.com/app/board/o9J_kvUSfDU=/
