### ISSUE TITLE
Evaluate our options for a mapping engine for Morecast

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#698]
**Describe the task**
Determine what mapping engines are available and how they align wiht the vision for mapping for Predictive services

**Acceptance Criteria**
- [x] determine what mapping engines we can use.
- [x] understand pros and cons of the choices.
- [x] make decision on what mapping tool we use with rationale.
- [x] list of bc map layers that we would want to show, and if we can show them.

**Additional context**
- Visions for mapping tool: https://akff.mesowest.org/map/#/c5490,-12722,5/g1/mc/vtemp/sAK/n/zt
- https://foresight.ffm.vic.gov.au/ (Login info Pinned in Teams)
- https://bcgov.github.io/bcwebmaps-options/
- We need to understand what map layers we can access free;y, what we need licensing for, what we can access with a open source tool, and what we can only access if we're entirely within the esri ecosystem.

**Comment by Kyubinhan** [comment]
The question was narrowed down to "Leaflet vs OpenLayers".
We've already used Leaflet in the past and have a good grasp of how to use it, however, we also discovered some shortcomings along the way (such as no functionality to order multiple layers, short maintenance activities compared to OpenLayers).
After spending some time playing with OpenLayers, my finding is following:
it has a smaller community size with a lack of documentation and examples, however, surprisingly it works well with React(we can modularize components easily - maybe it goes the same way with Leaflet) and it actually can handle ordering in layers, and it will work well with various type of map resources(GeoJSON, GeoRSS, KML, GML). Therefore we think it's worth giving it a shot for the coming map features.

Useful links in the future:
Leaflet vs OL
https://www.geoapify.com/leaflet-vs-openlayers

OpenLayers with React
https://medium.com/swlh/how-to-incorporate-openlayers-maps-into-react-65b411985744

https://github.com/mbrown3321/openlayers-react-map/tree/e6e62453a258d843b1867ebed6a2060219125f8c

OpenLayers + GeoJson Features + Popup
https://embed.plnkr.co/plunk/GvdVNE

Select Features by Hover
https://openlayers.org/en/latest/examples/select-hover-features.html

**Comment by Kyubinhan** [comment]
As long as we include attributions in our map we can use ArcGIS Rest API to pull map layers

Topographic layer from ArcGIS
https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}

Satellite layer from ArcGIS
https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}

Terrain layer from ArcGIS
https://server.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer/tile/{z}/{y}/{x}
