### ISSUE TITLE
Handle timezone issue in our application

### ISSUE THREAD

**Issue by Kyubinhan** [bcgov/wps#756]
**Describe the task**
Lately, there was a discovery that we are actually not fixating our date in PST in MoreCast when the timezone is different(ex, someone in Alberta accesses our app). It may seem to be working fine from users perspective who are in PST(which is most of our users), but it will be a problem when we transition to PDT again. So let's fix this!

**Acceptance Criteria**
- [ ] Set our dates in PST
- [ ] Replace moment(date/time handler library) with an alternative

**Additional context**
- https://moment.github.io/luxon/

**Comment by dthicks** [comment]
Is PST the time zone we want to focus on, given the bulk or all of wildfire season occurs in PDT? The legislation which may occur will also enact PDT as the standard.
