### ISSUE TITLE
Wireframe of MoreCast Mapping with multiple weather stations

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#758]
**Describe the task**
basic wireframe showing how we will display the map plus multiple weather stations data

**Acceptance Criteria**
- [x] Review wireframe with the Forecasters for feedback
- [x] wireframe reflect user feedback that has been collected so far

**Additional context**
- Wireframes built in Figma

**Comment by ambroseyau** [comment]
View Miro Link for Finished User Story:
https://miro.com/app/board/o9J_ktow2OY=/
