### ISSUE TITLE
Create Basic Style Guide for Wildfire Predictive Services

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#76]
**Describe the task**
Create a Style guide to support the initial work being undertaken by the development team.

**Acceptance Criteria**
- [x] Meets Government Design Standards
- [x] Uses Material designs
- [x] Typography
- [x] Color Palette
- [x] Form Elements
- [x] Basic Symbols

**Comment by PrakritiM** [comment]
Design Guide

https://invis.io/JGVV9HBH6KX



Link to understand how to give feedback/comments:

https://support.invisionapp.com/hc/en-us/articles/115000634946

**Comment by PrakritiM** [comment]
Accessibility reference:

https://invis.io/UDW4L2BZRPN
