### ISSUE TITLE
Initial success Metrics for Prep tool/HFI Calc

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#764]
**Describe the task**
we need to develop metrics of the current process, so when we develop our solution we have something to compare it to and ensure we have made a difference for the better.

**Acceptance Criteria**
Initial Success Metrics Documentation
https://teams.microsoft.com/l/file/1C897725-8CC5-4357-A13F-AB2E8933C3FC?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01324%2FShared%20Documents%2FGeneral%2FUX%2FHFI-Prep%20Tool%2FInitial%20success%20Metrics%20for%20Prep%20tool.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01324&serviceName=teams&threadId=19:61ee3cf6291249ef849064eb2748c6e7@thread.tacv2&groupId=23431815-15c2-4928-9839-d8878e46b956

**Additional context**
- We need to have something to compare against once we have an MVP otherwise we cant prove that we added value
- e.g. How many of the worksheets are put together each week for prep total and the total time spent on that across the province and use this to show how much total time/taxpayer dollars are used on prep right now.
- Video footage of someone doing the data entry  and how long its takes for example’s sake, Instead of just asking them so we can do a video comparison later prompt could be like “Give us the preparedness levels for this area as if it were fire season”

**Comment by ambroseyau** [comment]
**Initial Success Metrics Documentation**
https://teams.microsoft.com/l/file/1C897725-8CC5-4357-A13F-AB2E8933C3FC?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01324%2FShared%20Documents%2FGeneral%2FUX%2FHFI-Prep%20Tool%2FInitial%20success%20Metrics%20for%20Prep%20tool.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01324&serviceName=teams&threadId=19:61ee3cf6291249ef849064eb2748c6e7@thread.tacv2&groupId=23431815-15c2-4928-9839-d8878e46b956
