### ISSUE TITLE
Precipitation hover for mm vs cm

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#767]
**As a** *Forecaster* **I want** *to hover over the precip column with additional information* **So That** *I know why some measurements are in mm and other measurements are in cm*

**Additional Context**
- mm is for rain, cm is for snow

**Acceptance Criteria**
- [ ] Given I am looking at the tables, When I hover the precipitation column, Then a tool tip is displayed showing the different measurements used for precip and why

**Comment by andrea-williams** [comment]
Feedback received from Jesse and Matt on Mar. 4 is that we shouldn't use precip units of "mm/cm", we should just use mm. This ticket therefore no longer involves making a tooltip, just updating the precip labels (in tables and graphs) to be "mm".
