### ISSUE TITLE
Prototyping Workshop

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#77]
**Describe the task**
Facilitate a workshop to inform developers how to create adequate prototypes for designing feature wireframes

**Acceptance Criteria**
- [x] Team feels comfortable designing their own prototypes

**Comment by PrakritiM** [comment]
https://www.canva.com/design/DAD0I-NkRzI/EL7DXEX-0N01ZWRmMZ2mow/view?website#4

**Comment by PrakritiM** [comment]
Final sketches:

https://miro.com/app/board/o9J_kvR3PRw=/

-Key takeaways:
-More time for prototyping workshops
-Miro for PO feedback and stakeholder interaction
-Team preference for paper prototyping
