### ISSUE TITLE
Long Term Storage 

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#778]
**Context:**
Can we please schedule a meeting to discuss potential solutions to our long term storage problem. I’ve broken down what I see as our 3 options below
 
In a nutshell:
We can only store so many years worth of weather model data in the database. I think we have to shoot for at least option 2 (big openshift + OCIO object storage) – but man oh man oh man – it would be SOOOOO awesome to have access to AWS S3.
 
**Options**
Option 1:
What: Only store interpolated weather model values for weather stations and only a few months worth of historic c-haines data.
Why: Bare minimum.
How: We just need to upgrade our openshift to a bigger size, and we can store a few year’s worth of data.
Cost: Free. We just have to do some admin.
 
Option 2:
What: Store a subset of data (4 points surrounding a weather station) & store historic c-haines data. 
Why: We can re-generate data for our weather stations. E.g. re-calculate model temperature taking altitude into account. We can store many years worth of animated c-haines data.
How: Get OCIO object storage: https://apps.nrs.gov.bc.ca/int/confluence/display/OPTIMIZE/How+to+Request+Object+Storage?
Cost: $2410 once off cost for a namespace, $0.07 GB/Month. Looking at about $70 for storage of every years worth of data. (Based on what we’re currently storing – this is excluding c-haines data)
 
Option 3:
What: Store ALL the data we use. (Raw GRIB files). This is awesome. We get to re-process old data and generate any kind of scenario we want using historic data. (Getting historic data from environment Canada is possible, but it’s a very costly and manual process. Once you have that data, you’d have to store it somewhere anyway!)
How: Get AWS storage.
Cost: For about 330 USD, we can store an entire years’ worth of model data for GDPS, RDPS, HRDPS for 8 different layers (e.g. temp, rh, precip, wind speed, wind direction, temp 850hPa, temp 700hPa and dew point 850hPa)
Issues: This falls outside of normal process, and you’re going to need someone to pay Amazon manually.

**Comment by jakemorr** [comment]
Option 2 was decided on by Robert and Dana

**Comment by conbrad** [comment]
We use internal object store now, other long term questions to be brought up in more relevant tickets
