### ISSUE TITLE
Basic Persona: Consultants - 90 Percentile Calculator

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#79]
**Describe the task**
create a Persona for the consultants who create fire funding proposals for local governments in BC

**Acceptance Criteria**
- [x] represents consultant workflow 
- [x] captures their needs
- [x] Considers GBA+
- [x] Personality traits of Consultants
- [x] 1-2 Consultants Interviewed
- [x] user Persona Document

**Comment by PrakritiM** [comment]
https://miro.com/app/board/o9J_kvWpUq0=/

**Comment by PrakritiM** [comment]
https://miro.com/app/board/o9J_kuLhZgY=/
Consultant persona documented
