### ISSUE TITLE
Basic Persona - Wildfire staff (reviews funding proposal) - 90 Percentile Calculator

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#80]
**Description**
Create a Persona for the Wildfires staff who review fire funding proposals from consultants on behalf of local governments in BC

**Acceptance Criteria**
- [x] represents Wildfire staff workflow 
- [x] captures their needs
- [x] Considers GBA+
- [x] Personality traits of Wildfire Staff member responsible for reviewing funding proposals
- [x] 1-2 Consultants Interviewed
- [x] User persona documented

**Comment by PrakritiM** [comment]
contact:
Andrea Rainey - andrea.rainey@gov.bc.ca
Shannon Irvine – shannon.irvine@gov.bc.ca
Jessica Duncan – Jessica.duncan@gov.bc.ca

**Comment by PrakritiM** [comment]
https://miro.com/app/board/o9J_kvWpUq0=/

**Comment by PrakritiM** [comment]
[https://app.zenhub.com/files/235861506/9484be72-5bfe-480d-873a-a7fc6f63fe32/download](https://app.zenhub.com/files/235861506/9484be72-5bfe-480d-873a-a7fc6f63fe32/download)

**Comment by PrakritiM** [comment]
User 2 Questionnaire filled
[https://app.zenhub.com/files/235861506/e8d7324a-9bd0-4498-9786-d552d1a5b739/download](https://app.zenhub.com/files/235861506/e8d7324a-9bd0-4498-9786-d552d1a5b739/download)

**Comment by PrakritiM** [comment]
Persona

https://miro.com/app/board/o9J_kvWpUq0=/
