### ISSUE TITLE
Decide base Layers for map view in MoreCast

### ISSUE THREAD

**Issue by Kyubinhan** [bcgov/wps#801]
**Describe the task**
It seems that ArcGIS base layers (ex. http://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer) are meant to be used internally by their products(ArcGIS Pro, ArcGIS Javascript, etc). So we need to figure out how to use them in a way that we won't get in trouble in the future.

According to this [pricing](https://developers.arcgis.com/pricing/) they want to charge us based on the number of tiles we request. If we are going to use their base layers, we need to sign up for a developer account for the team and attach the given api key to the request url whenever we use their location services so that they can keep track of the usage.

Use [this](https://developers.arcgis.com/documentation/mapping-apis-and-location-services/maps/services/basemap-layer-service/#tile-service-urls) link as a starting point (Image tiles specifically). I haven't been able to find the list of available service name(I am starting to hate ArcGIS) but I did find the satellite image tile url that we are interested https://ibasemaps-api.arcgis.com/arcgis/rest/services/World_Imagery/MapServer/tile/x/y/z?token=YOUR_API_KEY

Michelle Douville told me to contact Meg Hoole to set up the account which I did, but haven't heard back from her yet as of writing (Mar 17)

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by Sybrand** [comment]
@jakemorr this could also be phrased as a story - in terms of "as a <user> I want to see a satellite map when..."

**Comment by jakemorr** [comment]
@Sybrand i think this is 2 parts and we will break it out. 

1. Decision on whether we want to use ArcGIS layers and pay for them or an open source alternative (research alternatives, make decision ticket)

2. Once we have decided on where the layers are coming from we make a user story for the base layers as you mentioned. (but i think we need to invest a small amount of time in seeing what we can do before committing to ArcGIS
