### ISSUE TITLE
Select a Weather Station using the Map

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#817]
**As a** *forecaster* **I want** *to select a weather station by clicking on the station on the map* **So That** *I don't have to go through the drop down list and find the weather station I have clicked on to see the name*

**Additional Context**
- to deselect a station use current functionality in the selected stations list(next to dropdown)

**Acceptance Criteria**
- [ ] Given I clicked on a weather station, When I click the button in the pop up, Then it adds it to the selected stations

**Comment by andrea-williams** [comment]
Blocked for the moment: React is complicated and confusing. Map re-renders every time the list of selected station codes is updated, which is unnecessary and irritating. Have not been able to figure out why re-render happens so often.

Things we've tried:
- switched from useState() for selectedStationCodes to storing the selected codes in the stationsSlice, then dispatching updates whenever a station is selected or deselected. Map still re-renders
- hard-coding the value for `redrawFlag` to `undefined` - map still re-renders
