### ISSUE TITLE
Create "Bug" Ticket

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#82]
**As a** *consultant or BCWS employee* **I want** *to be able to get to Fider from the Calculator* **So That** *I can report bugs or other issues that I am experiencing while using the 90% weather calculator*

**Additional Context**
- 

**Acceptance Criteria**
- [x] User can navigate to report the bug at any point
- [x] Given I am on the calculator app when i navigate to fider to report a bug or request an enhancement, Fider **opens in a new tab** (we do not want it to open in the current tab as they may have made a calculation and need to copy some of the information)

**Comment by Sybrand** [comment]
I'm moving this ticket back (out of in progress) - since it makes more sense to attack the running in developer mode task right now. What I've done thus far (not much) is in branch story/82/create_bug

**Comment by Sybrand** [comment]
@jakemorr @bradyholliday I would love to change the scope of this ticket to be 1) a link to a fider instance and 2) a spin fider instance. Maybe two different tickets?

**Comment by jakemorr** [comment]
I'll add a spin up ticket for Fider, i'll change this one to link to Fider
