### ISSUE TITLE
Map only displays stations we have data for

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#833]
**As a** *Forecaster* **I want** *to know that when i am looking at the map we have data on all of the stations shown * **So That** *I'm not looking around the drop down for a station that isn't there*

**Additional Context**
- currently pulling stations on map from BC data catalog and we need to make sure those match the ones coming from our API or change it
- might be worth having an architecture session before kicking off this ticket

**Acceptance Criteria**
- [ ] The stations shown on the map are the same as the stations in the drop down

**Comment by dthicks** [comment]
Can we pull this information from the "new" Oracle Database? This information will be updated daily in the database.

**Comment by Sybrand** [comment]
@dthicks - yep - that's partly implied by this ticket. We'll be pulling it from WFWX API - which pulls from the new Oracle DB. (There's a bit of magic in the background - in that while we're transitioning to the API, it will be pulling from our snapshot last year in dev and prod, but pull from the WFWX API in our test environment).
