### ISSUE TITLE
RH forecast accuracy on the map (1 day)

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#849]
**As a** *Forecaster or Forecast lead* **I want** *to be able to look at the map and determine which weather stations have accurate RH forecasts, which stations high/low forecasts* **So That** *I can target my efforts to improve my forecasting and learn how i am doing overall*

**Additional Context**
- warm (orange) colours mean the RH was lower than forecasted, cool colours (green) mean the RH was higher than forecasted 
- if the data is missing it should not look like a "good" station, it should be noticeable, perhaps as black
- within 3% in either direction should be recognized as accurate, and then the colours should get darker in 3% increments
- https://miro.com/app/board/o9J_ktow2OY=/
- https://www.figma.com/file/2VuF3FNyhuf5gKD7jqEbeR/MoreCast?node-id=193%3A2
- want to see coloured dots at scale of Fire Centre (entire fire centre is visible in one screen - approx. 2 + clicks in)
- **this is a stormable ticket!!**

**Acceptance Criteria**
- [ ] Given I am on the map, When I look at a weather station, Then I can tell how accurate the forecast is for the today at any given weather station
- [ ] Given I am on the map, When I look at a weather station that is missing either observed or forecast data, Then I can tell that the station i doesn't have the needed data to make an accuracy rating
- [ ] anytime before 13:00 on the selected day should show the previous day observed for everything, any time after 13:00  should reflect the selected day for everything
- [ ] Given I am on the test site (using WFWX API), When I refresh the map in Morecast, Then the accuracy of the stations' forecasts is immediately reflected *(this only applies if the WFWX API is performant)*

**Comment by conbrad** [comment]
Also address double calls to station endpoint as described here: https://github.com/bcgov/wps/pull/860#discussion_r610750918
