### ISSUE TITLE
90% ISI, BUI, & FFMC Displayed

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#85]
**As a** *Consultant or Wildfire Staff* **I want** *to see the calculated 90% value for ISI, BUI, & FFMC* **So That** *I can accurately document it/confirm it is correct based on the input parameters*

**Additional Context**
- value is clearly displayed
- input parameters are displayed alongside the calculated value

**Acceptance Criteria**
- [x] Given all the required inputs are selected, When the user clicks calculate, Then a 90% FFMC, BUI, & ISI values are generated and displayed
- [x] Given all the required inputs are selected, When the used clicks calculate, Then the input parameters are displayed alongside the calculated values
- [x] the calculations used to determine the 90th percentile values are verified with Dana
- [x] Values may be sourced from pre-calculated values based on a copy of daily weather data until such time as the API becomes available.
- [x] Display FFMC, BUI, & ISI mean values

**Comment by andrea-williams** [comment]
90th percentiles have been calculated offline, and a .json has been created with the info for each weather station. 

Have merged the code & JSONs to master branch - handing over to @Kyubinhan for FE implementation

**Comment by andrea-williams** [comment]
Received email confirmation from Dana this morning that our results for 90th percentiles for each weather station are all good.
(Also noted that station names prefixed with ZZ or suffixed with QD don't need to be included in calculations)

**Comment by Kyubinhan** [comment]
Front end progress:
We have met the acceptance criteria but we haven't written any tests yet
