### ISSUE TITLE
Add Authentication to Prepski

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#862]
**As a** *Predictive Services Superintendent* **I want** *to ensure that only IDIR users can access the Prepski* **So That** *those outside government cannot access the app without credentials*

**Additional Context**
- If you have an IDIR your in with this authentication
- the audit should include the unique identifier from keycloak, the IDIR, the email address, the first name, last name
- Call to the API has to be made in order for the audit entry to occur e.g. hello world message is sent from API
- Compliance with BC Gov Database Standards (contact our DB Architect)

**Acceptance Criteria**
- [x] Given someone attempts to navigate to Prepski, When they successfully authenticate, Then the attempt is logged and an audit trail is created
- [x] Given someone attempts to navigate to Prepski, When they attempt a log in with a valid credentials, Then the can go to the application
- [x] Given someone attempts to navigate to Prepski, When they attempt a log in with a invalid credentials, Then they are not allowed in
- [ ] Review new DB tables with DB Architect

**Comment by ccrocker1** [comment]
Here is the link to the audit column standards.  Let me know if there are any questions or need for clarification.  https://apps.nrs.gov.bc.ca/int/confluence/display/NRMDDDG/Logging+Auditing+and+Archiving .
