### ISSUE TITLE
color gradient highlighting on forecast vs observation table

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#879]
**As a** *Forecaster* **I want** *difference between the observed and forecast values highlighted in the table* **So That** *I can focus on the days with the biggest differentials in my analysis*

**Additional Context**
- use the same gradients as we are using for the map, this will require deciding on the gradients for temp and Windspeed, as they have not been implemented yet
Gradient for RH is orange to green in 3% increments
Gradient for Temp is red to blue in 2 degree increments
Gradient for Wind is Yellow - Purple in 4 kmph increments (TG: forecasted within 4kmph is good, +/- 8, 12, 16)
-this is for RH, Temp, and Windspeed only

**Acceptance Criteria**
- [ ] Given I am looking at the tables tab, When I look at the forecast vs observed table, Then colors highlight the differentials based on how far off the forecast is from the observed value for Temp
- [ ] Given I am looking at the tables tab, When I look at the forecast vs observed table, Then colors highlight the differentials based on how far off the forecast is from the observed value for RH
- [ ] Given I am looking at the tables tab, When I look at the forecast vs observed table, Then colors highlight the differentials based on how far off the forecast is from the observed value for Windspeed

**Comment by conbrad** [comment]
Make sure to fix `web/src/features/fireWeather/components/maps/stationAccuracy.ts` `computeAccuracyColors` for temperature, not just 3% difference for RH.
