### ISSUE TITLE
Set up Enzyme for front-end component testing

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#885]
**Describe the task**
Use Enzyme (https://devhints.io/enzyme) to test some of our React components that are difficult to test in Cypress/Jest.
e.g., wasn't able to write unit tests for `getCellClassNameAndTestId()` in `utils/table.ts` because it needs to call `makeStyles()`, and that's complicated to do in Jest.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by Sybrand** [comment]
@andrea-williams would this be captured in the coverage by sonarcloud?
