### ISSUE TITLE
HFI Calculator Review Round 6 with D.B

### ISSUE THREAD

**Issue by ambroseyau** [bcgov/wps#889]
**Describe the task**
Collect User feedback and gather specs from D.B. using the HFI Cal wireframe walkthrough prototype.

**Additional Context**
Wireframes built in Figma
 
**Acceptance Criteria**
- [x] Review wireframe with D.B. for feedback
- [x] Validate if the design solves all major user pain points
- [x] Identify additional major business requirements

**Comment by tessmgood** [comment]
Value of HFI (DB)
1. time saved and error prevention compared to current copy/paste csv workflow 
-- next step: test with actual users (not DB)
2. graph adds value (education, new/junior hires) 
-- next step: TG to support this work, building on AY wires 
2. (tied) future request:
"at some point I want to click a prep level 3 and see my ops plan - here's everything I need (resources) for level 3"
- linking HFI to the prep process:
-- shared drive/excel workbook > preloaded with staff, tick who's assigned that week and who's on standby, filter > someone at KFC collects the sheet for each zone > copies and pastes / consolidates to PDF > DH signs it electronically > print: "we have our prep" > if errors: revise excel sheet, PDF it, re-sign, print again (pain)
-- DB and AY worked on this
