### ISSUE TITLE
BCWS Internal link to 90% Weather Calculator

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#90]
**As a** *BCWS or government employee* **I want** *to be able to navigate to the 90% weather calculator from the BCWS Intranet page* **So That** *I do not need to navigate to an external page in order to find it*

**Additional Context**
- should be linked off of the Prevention CRI Program external page: https://www2.gov.bc.ca/gov/content/safety/wildfire-status/prevention/vegetation-and-fuel-management/fire-fuel-management/fuel-management
- need to email FireInfo@gov.bc.ca with link for them to edit the webpage

**Acceptance Criteria**
- [ ] Given I am on the right page, When the link is clicked, Then the 90% weather calculator opens
- [ ] Link to https://wps-web-prod.pathfinder.gov.bc.ca/percentile-calculator/

**Comment by bradyholliday** [comment]
This is not required until we have a final version ready for production

**Comment by jowand** [comment]
I spoke with Matthew Barnes re OpenShift URL link and he didn't think we needed approval to create a link.

**Comment by jakemorr** [comment]
because this is a request to another group we are estimating it as a 0 so it does not impact our velocity as there is no dev work from our end. we are pulling the ticket in so it stays top of mind and is monitored.

**Comment by jowand** [comment]
PIA/STRA approved. Let's get this done asap!
