### ISSUE TITLE
Assign WPS shared email account Account to BCGov-WPS Github Service account

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#92]
**Describe the task**
Assign WPS shared email account Account to BCGov-WPS Github Service account

**Acceptance Criteria**
- [x] Service account uses assigned team email address

**Comment by DerekRoberts** [comment]
Waiting on access to email address.  Already requested by Brady.

**Comment by DerekRoberts** [comment]
bcgov-wps using BCWS.PredictiveServices@gov.bc.ca

**Comment by bradyholliday** [comment]
@DerekRoberts can we please ensure that any accounts that are linked to this email are documented so that there is good continuity and awareness of what is in place. Thanks

**Comment by DerekRoberts** [comment]
@bradyholliday I'll pass the buck to @jakemorr
