### ISSUE TITLE
Explore NRS Sector URL to link off of the public website

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#93]
**Describe the task**
A clear and concise description of what the task is.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Talk to external comms, BCWS public website to see about housing one layer down from link.
- Or here

**Comment by bradyholliday** [comment]
Follow up with Derek on this

**Comment by bradyholliday** [comment]
Set up call with Ashley Davidoff to discuss options

**Comment by jowand** [comment]
@Sybrand this is the original task. I'll close it as a duplicate.
