### ISSUE TITLE
Time Range Selection Tool enhancement

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#95]
**As a** *Consultant and as a BCWS Employee* **I want** *to be able to select a time range for analysis* **So That** *I can limit the calculated data to be most representative of current conditions and threat*

**Additional Context**
- 0-10 years (default time range)
- 0-20 years
- Full data range 
- We are operating in full fire seasons, so when selecting data, only completed fire seasons are selected. E.g. if we're in July 2020, we'd only be using data from 2019 and earlier.

**Acceptance Criteria**
- [x] Given I select a time range, when I click on the calculate button, then the 90% value is calculated and the display updated.

**Comment by Nkuruba** [comment]
Feature added to master and tested in local. Need to test this feature in DEV environment to close this ticket.
