### ISSUE TITLE
Admin access to BCWS Intranet page for Dev Team

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#97]
**Describe the task**
we need admin access so the team can update information relating to the apps we are developing and maintaining, and the links to those apps through the intranet page.

**Acceptance Criteria**
- [ ] Team can make changes to predictive services intranet page

**Comment by bradyholliday** [comment]
Email to Internal Comms to explore access

**Comment by jowand** [comment]
Internal Comms emailed several weeks ago.
