### ISSUE TITLE
Map jumps around when selecting a station.

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#990]
**Describe the Bug**
Map jumps around when selecting a station.

**Expected Behaviour**
map stays where it has been positioned (zoom, and position) after selecting a weather station

**Actual Behaviour**
after selecting a weather station the map zooms out to the default full province view

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to Morecast
2. zoom in on the map and select a weather station
3. observe the map revert to default zoom/position

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tessmgood** [comment]
+1 (I think this is the same thing?)
When selecting multiple stations they're likely in the same zone (e.g. PG). 
Pain point: I zoom in to my area of the map, select first station, but then then map zooms out and re-centers. I lost my place and need to zoom in again.
